s=require "simphonie_lua"
sim=s.Simphonie.Simulator.new("luaSim")
sim:Run()
print("Simulator name: "..sim.Name)
sim:LoadLibrary("simphonie_umdl",0)
tk=sim:GetTimeKeeper()
print("Timekeeper simulation time: "..tk:GetSimulationTime())
print("Timekeeper state: "..tk.State)
sched=sim:GetScheduler()
print("Scheduler name: "..sched.Name)
res=sim:GetResolver()
print("resolver name: "..res.Name)
print("timekeeper state / simulation time:"..tk.State.."/"..tk:GetSimulationTime())
sim.testTK=tk;
print("scheduler description: "..sim.Scheduler.Description)
print("scheduler state: "..sim.Scheduler.State)
print("simulator state "..sim.State)
sim.Resolver.dump:Execute()
