variables:
    GIT_SSL_NO_VERIFY: "true"
    ABS_REPO: "https://www.eduvax.net/dist"
    DIST_HOST: "www.eduvax.net"

stages:
    - test
    - deploy
    - tag

.task:
    variables:
       GIT_STRATEGY: clone
       GIT_CHECKOUT: "true"
       GIT_CLEAN_FLAGS: -ffdx -e cache/
       GIT_DEPTH: "3"
       GIT_CLONE_PATH: $CI_BUILDS_DIR/build
    before_script:
      - echo "before_script"
      
.test_base:
    extends: .task
    stage: test
    variables:
        # FIXME: abs workaround to force MODE env var value when calling test target
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST"
    script: 
        - echo HOME=`pwd` make test $TASK_OPTVAR `test -n "$VABS" && echo "VABS=$VABS"`
        # change HOME to have a new ABS directory to avoid impacting others compilations.
        - HOME=`pwd` make test $TASK_OPTVAR `test -n "$VABS" && echo "VABS=$VABS"` | tee execution.log
        - egrep -ri 'errors="[1-9]+' build/unit_test_results && exit 1 || echo "ok"
        - egrep -ri 'failures="[1-9]+' build/unit_test_results && exit 1 || echo "ok"
    only:
        - branches
    artifacts:
        paths:
            - build/unit_test_results/*.xml
        reports:
            junit: build/unit_test_results/*.xml

.deploy_base:
    extends: .task
    stage: deploy
    only:
        - tags
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST"
    script:
        - echo HOME=`pwd` make pubdist $TASK_OPTVAR `test -n "$VABS" && echo "VABS=$VABS"`
        # change HOME to have a new ABS directory to avoid impacting others compilations.
        - HOME=`pwd` make pubdist $TASK_OPTVAR `test -n "$VABS" && echo "VABS=$VABS"`

# Test jobs triggered only at branch push
sanitize_debian11:
    extends: .task
    stage: test
    variables:
        # FIXME: abs workaround to force MODE env var value when calling cint target
        TASK_OPTVAR: "$USER_TASK_OPTVAR MAXJOBS=8 MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST ACTIVATE_SANITIZER=true"
    script: 
        - echo HOME=`pwd` make test $TASK_OPTVAR `test -n "$VABS" && echo "VABS=$VABS"`
        # change HOME to have a new ABS directory to avoid impacting others compilations.
        - HOME=`pwd` make test $TASK_OPTVAR `test -n "$VABS" && echo "VABS=$VABS"` | tee execution.log
        - egrep -E -q "(LeakSanitizer)|(AddressSanitizer)" execution.log && grep -E "(Starting test suite:)|(LeakSanitizer)|(AddressSanitizer)" execution.log && echo "See execution.log for more details"
        - egrep -E -q "(LeakSanitizer)|(AddressSanitizer)" execution.log && exit 1 || echo "OK"
    only:
        - branches
    tags:
        - debian_11
    artifacts:
        paths:
            - execution.log


test_mingw:
    extends: .test_base
    tags:
        - debian_12_mingw
        
test_debian11:
    extends: .test_base
    tags:
        - debian_11
        
test_debian12:
    extends: .test_base
    tags:
        - debian_12
        
test_debian12_arm64:
    extends: .test_base
    tags:
        - debian_12_arm64

test_debian9:
    extends: .test_base
    tags:
        - debian_9
        
test_suse12:
    extends: .test_base
    tags:
        - suse_12
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST CC=../gcc-4.9.4/bin/gcc CPPC=../gcc-4.9.4/bin/g++"
    before_script:
        # need a more recent version of gcc
        - wget --no-check-certificate $ABS_REPO/SUSE_12_x86_64/gcc-4.9.4.SUSE_12_x86_64.tar.gz
        - tar -xf gcc-4.9.4.SUSE_12_x86_64.tar.gz
        
test_redhawk7_clang13:
    extends: .test_base
    tags:
        - redhawk_7
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST BUILDCHAIN=clang-13"

test_suse15sp5:
    extends: .test_base
    tags:
        - suse_15sp5

# Main Deployment job triggered only at new tag push
deploy_debian11:
    extends: .deploy_base
    tags:
        - debian_11

deploy_debian12:
    extends: .deploy_base
    tags:
        - debian_12

deploy_debian12_arm64:
    extends: .deploy_base
    tags:
        - debian_12_arm64

deploy_suse12:
    extends: .deploy_base
    tags:
        - suse_12
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST CC=../gcc-4.9.4/bin/gcc CPPC=../gcc-4.9.4/bin/g++"
    before_script:
        # need a more recent version of gcc
        - wget --no-check-certificate $ABS_REPO/SUSE_12_x86_64/gcc-4.9.4.SUSE_12_x86_64.tar.gz
        - tar -xf gcc-4.9.4.SUSE_12_x86_64.tar.gz

deploy_debian9:
    extends: .deploy_base
    tags:
        - debian_9

deploy_redhawk7_clang13:
    extends: .deploy_base
    tags:
        - redhawk_7
    variables:
        TASK_OPTVAR: "$USER_TASK_OPTVAR MODE=release ABS_REPO=$ABS_REPO DISTHOST=$DIST_HOST BUILDCHAIN=clang-13"

deploy_suse15sp5:
    extends: .deploy_base
    tags:
        - suse_15sp5

