/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_CANNOTSTORE_H
#define CWRAPPER_CANNOTSTORE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(CannotStore);

#undef CW_SPACE


/* ### Smp::CannotStore ### */
#ifndef CW_root_Smp_CannotStore
#define CW_root_Smp_CannotStore CW_BUILD_SPACE(CW_root_Smp, CannotStore)
#endif /* CW_root_Smp_CannotStore */
#define CW_SPACE CW_root_Smp_CannotStore

void
CW(_CannotStore)
(
    CW() * self
);

/* Error while processing function "CannotStore" at Smp/./CannotStore.h:29:11 (exported to Smp-C/CannotStore.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotStore.h:29:11 (exported to Smp-C/CannotStore.h) : Reference type is not supported: CannotStore & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_CANNOTSTORE_H */
