/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_CANNOTDELETE_H
#define CWRAPPER_CANNOTDELETE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(CannotDelete);

#undef CW_SPACE


/* ### Smp::CannotDelete ### */
#ifndef CW_root_Smp_CannotDelete
#define CW_root_Smp_CannotDelete CW_BUILD_SPACE(CW_root_Smp, CannotDelete)
#endif /* CW_root_Smp_CannotDelete */
#define CW_SPACE CW_root_Smp_CannotDelete

void
CW(_CannotDelete)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetContainerName)
(
    CW() * self
);

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetLowerLimit)
(
    CW() * self
);

/* Error while processing function "CannotDelete" at Smp/./CannotDelete.h:39:11 (exported to Smp-C/CannotDelete.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotDelete.h:39:11 (exported to Smp-C/CannotDelete.h) : Reference type is not supported: CannotDelete & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_CANNOTDELETE_H */
