/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_CANNOTRESTORE_H
#define CWRAPPER_CANNOTRESTORE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(CannotRestore);

#undef CW_SPACE


/* ### Smp::CannotRestore ### */
#ifndef CW_root_Smp_CannotRestore
#define CW_root_Smp_CannotRestore CW_BUILD_SPACE(CW_root_Smp, CannotRestore)
#endif /* CW_root_Smp_CannotRestore */
#define CW_SPACE CW_root_Smp_CannotRestore

void
CW(_CannotRestore)
(
    CW() * self
);

/* Error while processing function "CannotRestore" at Smp/./CannotRestore.h:30:11 (exported to Smp-C/CannotRestore.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotRestore.h:30:11 (exported to Smp-C/CannotRestore.h) : Reference type is not supported: CannotRestore & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_CANNOTRESTORE_H */
