/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_CANNOTREMOVE_H
#define CWRAPPER_CANNOTREMOVE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(CannotRemove);

#undef CW_SPACE


/* ### Smp::CannotRemove ### */
#ifndef CW_root_Smp_CannotRemove
#define CW_root_Smp_CannotRemove CW_BUILD_SPACE(CW_root_Smp, CannotRemove)
#endif /* CW_root_Smp_CannotRemove */
#define CW_SPACE CW_root_Smp_CannotRemove

void
CW(_CannotRemove)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetReferenceName)
(
    CW() * self
);

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetLowerLimit)
(
    CW() * self
);

/* Error while processing function "CannotRemove" at Smp/./CannotRemove.h:39:11 (exported to Smp-C/CannotRemove.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotRemove.h:39:11 (exported to Smp-C/CannotRemove.h) : Reference type is not supported: CannotRemove & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_CANNOTREMOVE_H */
