/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_COLLECTIONITERATOR_H
#define CWRAPPER_COLLECTIONITERATOR_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"
#include <stddef.h>
/* #include <iterator> */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ICollection);

typedef void CW(CollectionIterator);

#undef CW_SPACE


/* ### Smp::CollectionIterator ### */
#ifndef CW_root_Smp_CollectionIterator
#define CW_root_Smp_CollectionIterator CW_BUILD_SPACE(CW_root_Smp, CollectionIterator)
#endif /* CW_root_Smp_CollectionIterator */
#define CW_SPACE CW_root_Smp_CollectionIterator

/* Error while processing typedef "value_type" at Smp/./CollectionIterator.h:41:15 (exported to Smp-C/CollectionIterator.h) : Unsupported type: T * */

typedef ptrdiff_t CW(difference_type);

/* typedef CW(value_type) * CW(pointer); */

/* Error while processing typedef "reference" at Smp/./CollectionIterator.h:44:15 (exported to Smp-C/CollectionIterator.h) : Reference type is not supported: value_type & */

/* Error while processing function "CollectionIterator<T>" at Smp/./CollectionIterator.h:49:9 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "CollectionIterator<T>" at Smp/./CollectionIterator.h:58:9 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator=" at Smp/./CollectionIterator.h:63:29 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "CollectionIterator<T>" at Smp/./CollectionIterator.h:67:9 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator=" at Smp/./CollectionIterator.h:72:29 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator*" at Smp/./CollectionIterator.h:76:20 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator[]" at Smp/./CollectionIterator.h:84:20 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator++" at Smp/./CollectionIterator.h:91:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator++" at Smp/./CollectionIterator.h:99:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator--" at Smp/./CollectionIterator.h:108:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator--" at Smp/./CollectionIterator.h:116:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator+=" at Smp/./CollectionIterator.h:126:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator-=" at Smp/./CollectionIterator.h:135:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator+" at Smp/./CollectionIterator.h:144:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator-" at Smp/./CollectionIterator.h:152:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator!=" at Smp/./CollectionIterator.h:160:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator==" at Smp/./CollectionIterator.h:168:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator<" at Smp/./CollectionIterator.h:177:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator<=" at Smp/./CollectionIterator.h:186:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator>" at Smp/./CollectionIterator.h:195:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator>=" at Smp/./CollectionIterator.h:204:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "getIndex" at Smp/./CollectionIterator.h:212:16 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "getCollection" at Smp/./CollectionIterator.h:219:36 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

#undef CW_SPACE


/* ### std ### */
#ifndef CW_root_std
#define CW_root_std CW_BUILD_SPACE(CW_root, std)
#endif /* CW_root_std */
#define CW_SPACE CW_root_std

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_COLLECTIONITERATOR_H */
