/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_CONTAINERFULL_H
#define CWRAPPER_CONTAINERFULL_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ContainerFull);

#undef CW_SPACE


/* ### Smp::ContainerFull ### */
#ifndef CW_root_Smp_ContainerFull
#define CW_root_Smp_ContainerFull CW_BUILD_SPACE(CW_root_Smp, ContainerFull)
#endif /* CW_root_Smp_ContainerFull */
#define CW_SPACE CW_root_Smp_ContainerFull

void
CW(_ContainerFull)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetContainerName)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetContainerSize)
(
    CW() * self
);

/* Error while processing function "ContainerFull" at Smp/ContainerFull.h:29:11 (exported to Smp-C/ContainerFull.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/ContainerFull.h:29:11 (exported to Smp-C/ContainerFull.h) : Reference type is not supported: ContainerFull & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_CONTAINERFULL_H */
