/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_CWRAPPER_H
#define CWRAPPER_CWRAPPER_H

/* Parameters */
// #define CW_PREFIX pre /* uncomment to add a prefix to every name */
// #define CW_POSTFIX post /* uncomment to add a postfix to every name */
#define CW_SEPARATOR _ /* names' separator */

/* Utils */
#define CW_CONCAT3(a, b, c) a ## b ## c
#define CW_CC3EX(a, b, c) CW_CONCAT3(a, b, c)
#define CW_BUILD_SPACE_RELATIVE(a, b) CW_CC3EX(a, CW_SEPARATOR, b)
#define CW_BUILD_SPACE_ABSOLUTE(b) root_ ## b
#define CW_SWITCH_BUILD_SPACE(_1, _2, name, ...) name
#define CW_BUILD_SPACE(...) CW_SWITCH_BUILD_SPACE(__VA_ARGS__, CW_BUILD_SPACE_RELATIVE, CW_BUILD_SPACE_ABSOLUTE)(__VA_ARGS__)

/* Name Retrieving */
#if defined(CW_PREFIX) && defined(CW_POSTFIX)
    #define CW_NAME_SPACE() CW_CC3EX(CW_PREFIX, CW_SEPARATOR, CW_CC3EX(CW_SPACE, CW_SEPARATOR, CW_POSTFIX))
    #define CW_NAME_AT_SPACE(name) CW_CC3EX(CW_PREFIX, CW_SEPARATOR, CW_CC3EX(CW_SPACE, CW_SEPARATOR, CW_CC3EX(name, CW_SEPARATOR, CW_POSTFIX)))
    #define CW_NAME_WITH_SPACE(space, name) CW_CC3EX(CW_PREFIX, CW_SEPARATOR, CW_CC3EX(space, CW_SEPARATOR, CW_CC3EX(name, CW_SEPARATOR, CW_POSTFIX)))
#elif defined(CW_PREFIX)
    #define CW_NAME_SPACE() CW_CC3EX(CW_PREFIX, CW_SEPARATOR, CW_SPACE)
    #define CW_NAME_AT_SPACE(name) CW_CC3EX(CW_PREFIX, CW_SEPARATOR, CW_CC3EX(CW_SPACE, CW_SEPARATOR, name))
    #define CW_NAME_WITH_SPACE(space, name) CW_CC3EX(CW_PREFIX, CW_SEPARATOR, CW_CC3EX(space, CW_SEPARATOR, name))
#elif defined(CW_POSTFIX)
    #define CW_NAME_SPACE() CW_CC3EX(CW_SPACE, CW_SEPARATOR, CW_POSTFIX)
    #define CW_NAME_AT_SPACE(name) CW_CC3EX(CW_SPACE, CW_SEPARATOR, CW_CC3EX(name, CW_SEPARATOR, CW_POSTFIX))
    #define CW_NAME_WITH_SPACE(space, name) CW_CC3EX(space, CW_SEPARATOR, CW_CC3EX(name, CW_SEPARATOR, CW_POSTFIX))
#else
    #define CW_NAME_SPACE() CW_SPACE
    #define CW_NAME_AT_SPACE(name) CW_CC3EX(CW_SPACE, CW_SEPARATOR, name)
    #define CW_NAME_WITH_SPACE(space, name) CW_CC3EX(space, CW_SEPARATOR, name)
#endif
#define CW_SWITCH_NAME(_1, _2, name, ...) name
#define CW(...) CW_SWITCH_NAME(__VA_OPT__(__VA_ARGS__,) CW_NAME_WITH_SPACE, CW_NAME_AT_SPACE, CW_NAME_SPACE)(__VA_ARGS__)

#define CW_root root

#endif /* CWRAPPER_CWRAPPER_H */
