/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_DUPLICATEUUID_H
#define CWRAPPER_DUPLICATEUUID_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(DuplicateUuid);

#undef CW_SPACE


/* ### Smp::DuplicateUuid ### */
#ifndef CW_root_Smp_DuplicateUuid
#define CW_root_Smp_DuplicateUuid CW_BUILD_SPACE(CW_root_Smp, DuplicateUuid)
#endif /* CW_root_Smp_DuplicateUuid */
#define CW_SPACE CW_root_Smp_DuplicateUuid

void
CW(_DuplicateUuid)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetOldName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetNewName)
(
    CW() * self
);

/* Error while processing function "DuplicateUuid" at Smp/./DuplicateUuid.h:30:11 (exported to Smp-C/DuplicateUuid.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./DuplicateUuid.h:30:11 (exported to Smp-C/DuplicateUuid.h) : Reference type is not supported: DuplicateUuid & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_DUPLICATEUUID_H */
