/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_DUPLICATENAME_H
#define CWRAPPER_DUPLICATENAME_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(DuplicateName);

#undef CW_SPACE


/* ### Smp::DuplicateName ### */
#ifndef CW_root_Smp_DuplicateName
#define CW_root_Smp_DuplicateName CW_BUILD_SPACE(CW_root_Smp, DuplicateName)
#endif /* CW_root_Smp_DuplicateName */
#define CW_SPACE CW_root_Smp_DuplicateName

void
CW(_DuplicateName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetDuplicateName)
(
    CW() * self
);

/* Error while processing function "DuplicateName" at Smp/DuplicateName.h:31:11 (exported to Smp-C/DuplicateName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/DuplicateName.h:31:11 (exported to Smp-C/DuplicateName.h) : Reference type is not supported: DuplicateName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_DUPLICATENAME_H */
