/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_EVENTSINKNOTSUBSCRIBED_H
#define CWRAPPER_EVENTSINKNOTSUBSCRIBED_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSink);

typedef void CW(IEventSource);

typedef void CW(EventSinkNotSubscribed);

#undef CW_SPACE


/* ### Smp::EventSinkNotSubscribed ### */
#ifndef CW_root_Smp_EventSinkNotSubscribed
#define CW_root_Smp_EventSinkNotSubscribed CW_BUILD_SPACE(CW_root_Smp, EventSinkNotSubscribed)
#endif /* CW_root_Smp_EventSinkNotSubscribed */
#define CW_SPACE CW_root_Smp_EventSinkNotSubscribed

void
CW(_EventSinkNotSubscribed)
(
    CW() * self
);

const CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self
);

const CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self
);

/* Error while processing function "EventSinkNotSubscribed" at Smp/./EventSinkNotSubscribed.h:38:11 (exported to Smp-C/EventSinkNotSubscribed.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./EventSinkNotSubscribed.h:38:11 (exported to Smp-C/EventSinkNotSubscribed.h) : Reference type is not supported: EventSinkNotSubscribed & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_EVENTSINKNOTSUBSCRIBED_H */
