/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_EVENTSINKALREADYSUBSCRIBED_H
#define CWRAPPER_EVENTSINKALREADYSUBSCRIBED_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSink);

typedef void CW(IEventSource);

typedef void CW(EventSinkAlreadySubscribed);

#undef CW_SPACE


/* ### Smp::EventSinkAlreadySubscribed ### */
#ifndef CW_root_Smp_EventSinkAlreadySubscribed
#define CW_root_Smp_EventSinkAlreadySubscribed CW_BUILD_SPACE(CW_root_Smp, EventSinkAlreadySubscribed)
#endif /* CW_root_Smp_EventSinkAlreadySubscribed */
#define CW_SPACE CW_root_Smp_EventSinkAlreadySubscribed

void
CW(_EventSinkAlreadySubscribed)
(
    CW() * self
);

const CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self
);

const CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self
);

/* Error while processing function "EventSinkAlreadySubscribed" at Smp/./EventSinkAlreadySubscribed.h:38:11 (exported to Smp-C/EventSinkAlreadySubscribed.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./EventSinkAlreadySubscribed.h:38:11 (exported to Smp-C/EventSinkAlreadySubscribed.h) : Reference type is not supported: EventSinkAlreadySubscribed & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_EVENTSINKALREADYSUBSCRIBED_H */
