/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_EXCEPTION_H
#define CWRAPPER_EXCEPTION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"
/* #include <exception> */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IObject);

typedef void CW(Exception);

#undef CW_SPACE


/* ### Smp::Exception ### */
#ifndef CW_root_Smp_Exception
#define CW_root_Smp_Exception CW_BUILD_SPACE(CW_root_Smp, Exception)
#endif /* CW_root_Smp_Exception */
#define CW_SPACE CW_root_Smp_Exception

void
CW(_Exception)
(
    CW() * self
);

const CW(CW_root_Smp, Char8) *
CW(what)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetDescription)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetMessage)
(
    CW() * self
);

const CW(CW_root_Smp, IObject) *
CW(GetSender)
(
    CW() * self
);

/* Error while processing function "Exception" at Smp/Exception.h:39:11 (exported to Smp-C/Exception.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Exception.h:39:11 (exported to Smp-C/Exception.h) : Reference type is not supported: Exception & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_EXCEPTION_H */
