/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_FIELDNOTCONNECTED_H
#define CWRAPPER_FIELDNOTCONNECTED_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IField);

typedef void CW(IOutputField);

typedef void CW(FieldNotConnected);

#undef CW_SPACE


/* ### Smp::FieldNotConnected ### */
#ifndef CW_root_Smp_FieldNotConnected
#define CW_root_Smp_FieldNotConnected CW_BUILD_SPACE(CW_root_Smp, FieldNotConnected)
#endif /* CW_root_Smp_FieldNotConnected */
#define CW_SPACE CW_root_Smp_FieldNotConnected

void
CW(_FieldNotConnected)
(
    CW() * self
);

const CW(CW_root_Smp, IOutputField) *
CW(GetSource)
(
    CW() * self
);

const CW(CW_root_Smp, IField) *
CW(GetTarget)
(
    CW() * self
);

/* Error while processing function "FieldNotConnected" at Smp/./FieldNotConnected.h:38:11 (exported to Smp-C/FieldNotConnected.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./FieldNotConnected.h:38:11 (exported to Smp-C/FieldNotConnected.h) : Reference type is not supported: FieldNotConnected & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_FIELDNOTCONNECTED_H */
