/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_FIELDALREADYCONNECTED_H
#define CWRAPPER_FIELDALREADYCONNECTED_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IField);

typedef void CW(IOutputField);

typedef void CW(FieldAlreadyConnected);

#undef CW_SPACE


/* ### Smp::FieldAlreadyConnected ### */
#ifndef CW_root_Smp_FieldAlreadyConnected
#define CW_root_Smp_FieldAlreadyConnected CW_BUILD_SPACE(CW_root_Smp, FieldAlreadyConnected)
#endif /* CW_root_Smp_FieldAlreadyConnected */
#define CW_SPACE CW_root_Smp_FieldAlreadyConnected

void
CW(_FieldAlreadyConnected)
(
    CW() * self
);

const CW(CW_root_Smp, IOutputField) *
CW(GetSource)
(
    CW() * self
);

const CW(CW_root_Smp, IField) *
CW(GetTarget)
(
    CW() * self
);

/* Error while processing function "FieldAlreadyConnected" at Smp/./FieldAlreadyConnected.h:38:11 (exported to Smp-C/FieldAlreadyConnected.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./FieldAlreadyConnected.h:38:11 (exported to Smp-C/FieldAlreadyConnected.h) : Reference type is not supported: FieldAlreadyConnected & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_FIELDALREADYCONNECTED_H */
