/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_FILENOTFOUND_H
#define CWRAPPER_FILENOTFOUND_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(FileNotFound);

#undef CW_SPACE


/* ### Smp::FileNotFound ### */
#ifndef CW_root_Smp_FileNotFound
#define CW_root_Smp_FileNotFound CW_BUILD_SPACE(CW_root_Smp, FileNotFound)
#endif /* CW_root_Smp_FileNotFound */
#define CW_SPACE CW_root_Smp_FileNotFound

void
CW(_FileNotFound)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetFileName)
(
    CW() * self
);

/* Error while processing function "FileNotFound" at Smp/./FileNotFound.h:28:11 (exported to Smp-C/FileNotFound.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./FileNotFound.h:28:11 (exported to Smp-C/FileNotFound.h) : Reference type is not supported: FileNotFound & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_FILENOTFOUND_H */
