/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IAGGREGATE_H
#define CWRAPPER_IAGGREGATE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IComponent.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/ReferenceCollection.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IReference);

typedef void CW(IAggregate);

#undef CW_SPACE


/* ### Smp::IAggregate ### */
#ifndef CW_root_Smp_IAggregate
#define CW_root_Smp_IAggregate CW_BUILD_SPACE(CW_root_Smp, IAggregate)
#endif /* CW_root_Smp_IAggregate */
#define CW_SPACE CW_root_Smp_IAggregate

void
CW(_IAggregate)
(
    CW() * self
);

const CW(CW_root_Smp, ReferenceCollection) *
CW(GetReferences)
(
    CW() * self
);

CW(CW_root_Smp, IReference) *
CW(GetReference)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IAggregate" at Smp/./IAggregate.h:43:11 (exported to Smp-C/IAggregate.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IAggregate.h:43:11 (exported to Smp-C/IAggregate.h) : Reference type is not supported: IAggregate & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IAGGREGATE_H */
