/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IARRAYFIELD_H
#define CWRAPPER_IARRAYFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IField.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IArrayField);

#undef CW_SPACE


/* ### Smp::IArrayField ### */
#ifndef CW_root_Smp_IArrayField
#define CW_root_Smp_IArrayField CW_BUILD_SPACE(CW_root_Smp, IArrayField)
#endif /* CW_root_Smp_IArrayField */
#define CW_SPACE CW_root_Smp_IArrayField

void
CW(_IArrayField)
(
    CW() * self
);

CW(CW_root_Smp, UInt64)
CW(GetSize)
(
    CW() * self
);

CW(CW_root_Smp, IField) *
CW(GetItem)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) index
);

/* Error while processing function "IArrayField" at Smp/./IArrayField.h:28:11 (exported to Smp-C/IArrayField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IArrayField.h:28:11 (exported to Smp-C/IArrayField.h) : Reference type is not supported: IArrayField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IARRAYFIELD_H */
