/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ICOLLECTION_H
#define CWRAPPER_ICOLLECTION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/CollectionIterator.h"
#include "Smp-C/ICollectionBase.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ICollection);

#undef CW_SPACE


/* ### Smp::ICollection ### */
#ifndef CW_root_Smp_ICollection
#define CW_root_Smp_ICollection CW_BUILD_SPACE(CW_root_Smp, ICollection)
#endif /* CW_root_Smp_ICollection */
#define CW_SPACE CW_root_Smp_ICollection

/* Error while processing typedef "const_iterator" at Smp/ICollection.h:38:44 (exported to Smp-C/ICollection.h) : Unsupported type: Smp::CollectionIterator<T> */

/* Error while processing typedef "iterator" at Smp/ICollection.h:41:44 (exported to Smp-C/ICollection.h) : Unsupported type: Smp::CollectionIterator<T> */

/* Error while processing function "~ICollection<T>" at Smp/ICollection.h:44:17 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "at" at Smp/ICollection.h:49:20 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "at" at Smp/ICollection.h:56:20 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "size" at Smp/ICollection.h:61:24 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "empty" at Smp/ICollection.h:65:27 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "begin" at Smp/ICollection.h:69:32 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "end" at Smp/ICollection.h:73:32 (exported to Smp-C/ICollection.h) : Skipping templated function */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ICOLLECTION_H */
