/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ICOLLECTIONBASE_H
#define CWRAPPER_ICOLLECTIONBASE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ICollectionBase);

#undef CW_SPACE


/* ### Smp::ICollectionBase ### */
#ifndef CW_root_Smp_ICollectionBase
#define CW_root_Smp_ICollectionBase CW_BUILD_SPACE(CW_root_Smp, ICollectionBase)
#endif /* CW_root_Smp_ICollectionBase */
#define CW_SPACE CW_root_Smp_ICollectionBase

void
CW(_ICollectionBase)
(
    CW() * self
);

/* Error while processing function "operator=" at Smp/ICollectionBase.h:27:11 (exported to Smp-C/ICollectionBase.h) : Reference type is not supported: ICollectionBase & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ICOLLECTIONBASE_H */
