/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ICOMPOSITE_H
#define CWRAPPER_ICOMPOSITE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/ContainerCollection.h"
#include "Smp-C/IObject.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IContainer);

typedef void CW(IComposite);

#undef CW_SPACE


/* ### Smp::IComposite ### */
#ifndef CW_root_Smp_IComposite
#define CW_root_Smp_IComposite CW_BUILD_SPACE(CW_root_Smp, IComposite)
#endif /* CW_root_Smp_IComposite */
#define CW_SPACE CW_root_Smp_IComposite

void
CW(_IComposite)
(
    CW() * self
);

const CW(CW_root_Smp, ContainerCollection) *
CW(GetContainers)
(
    CW() * self
);

CW(CW_root_Smp, IContainer) *
CW(GetContainer)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IComposite" at Smp/./IComposite.h:43:11 (exported to Smp-C/IComposite.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IComposite.h:43:11 (exported to Smp-C/IComposite.h) : Reference type is not supported: IComposite & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ICOMPOSITE_H */
