/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ICONTAINER_H
#define CWRAPPER_ICONTAINER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/CannotDelete.h"
#include "Smp-C/ComponentCollection.h"
#include "Smp-C/ContainerFull.h"
#include "Smp-C/DuplicateName.h"
#include "Smp-C/InvalidObjectType.h"
#include "Smp-C/InvalidParent.h"
#include "Smp-C/IObject.h"
#include "Smp-C/NotContained.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(IContainer);

#undef CW_SPACE


/* ### Smp::IContainer ### */
#ifndef CW_root_Smp_IContainer
#define CW_root_Smp_IContainer CW_BUILD_SPACE(CW_root_Smp, IContainer)
#endif /* CW_root_Smp_IContainer */
#define CW_SPACE CW_root_Smp_IContainer

void
CW(_IContainer)
(
    CW() * self
);

const CW(CW_root_Smp, ComponentCollection) *
CW(GetComponents)
(
    CW() * self
);

CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

void
CW(AddComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
);

void
CW(DeleteComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
);

CW(CW_root_Smp, Int64)
CW(GetCount)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetUpper)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetLower)
(
    CW() * self
);

/* Error while processing function "IContainer" at Smp/IContainer.h:47:11 (exported to Smp-C/IContainer.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IContainer.h:47:11 (exported to Smp-C/IContainer.h) : Reference type is not supported: IContainer & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ICONTAINER_H */
