/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IDYNAMICINVOCATION_H
#define CWRAPPER_IDYNAMICINVOCATION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IComponent.h"
#include "Smp-C/InvalidOperationName.h"
#include "Smp-C/InvalidParameterCount.h"
#include "Smp-C/InvalidParameterValue.h"
#include "Smp-C/OperationCollection.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/PropertyCollection.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IOperation);

typedef void CW(IProperty);

typedef void CW(IRequest);

typedef void CW(IDynamicInvocation);

#undef CW_SPACE


/* ### Smp::IDynamicInvocation ### */
#ifndef CW_root_Smp_IDynamicInvocation
#define CW_root_Smp_IDynamicInvocation CW_BUILD_SPACE(CW_root_Smp, IDynamicInvocation)
#endif /* CW_root_Smp_IDynamicInvocation */
#define CW_SPACE CW_root_Smp_IDynamicInvocation

void
CW(_IDynamicInvocation)
(
    CW() * self
);

void
CW(Invoke)
(
    CW() * self,
    CW(CW_root_Smp, IRequest) * request
);

CW(CW_root_Smp, IProperty) *
CW(GetProperty)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

const CW(CW_root_Smp, PropertyCollection) *
CW(GetProperties)
(
    CW() * self
);

CW(CW_root_Smp, IOperation) *
CW(GetOperation)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

const CW(CW_root_Smp, OperationCollection) *
CW(GetOperations)
(
    CW() * self
);

/* Error while processing function "IDynamicInvocation" at Smp/./IDynamicInvocation.h:48:11 (exported to Smp-C/IDynamicInvocation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IDynamicInvocation.h:48:11 (exported to Smp-C/IDynamicInvocation.h) : Reference type is not supported: IDynamicInvocation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IDYNAMICINVOCATION_H */
