/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IENTRYPOINT_H
#define CWRAPPER_IENTRYPOINT_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IObject.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEntryPoint);

#undef CW_SPACE


/* ### Smp::IEntryPoint ### */
#ifndef CW_root_Smp_IEntryPoint
#define CW_root_Smp_IEntryPoint CW_BUILD_SPACE(CW_root_Smp, IEntryPoint)
#endif /* CW_root_Smp_IEntryPoint */
#define CW_SPACE CW_root_Smp_IEntryPoint

void
CW(_IEntryPoint)
(
    CW() * self
);

void
CW(Execute)
(
    CW() * self
);

/* Error while processing function "IEntryPoint" at Smp/IEntryPoint.h:30:11 (exported to Smp-C/IEntryPoint.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IEntryPoint.h:30:11 (exported to Smp-C/IEntryPoint.h) : Reference type is not supported: IEntryPoint & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IENTRYPOINT_H */
