/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IENTRYPOINTPUBLISHER_H
#define CWRAPPER_IENTRYPOINTPUBLISHER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/EntryPointCollection.h"
#include "Smp-C/IObject.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEntryPoint);

typedef void CW(IEntryPointPublisher);

#undef CW_SPACE


/* ### Smp::IEntryPointPublisher ### */
#ifndef CW_root_Smp_IEntryPointPublisher
#define CW_root_Smp_IEntryPointPublisher CW_BUILD_SPACE(CW_root_Smp, IEntryPointPublisher)
#endif /* CW_root_Smp_IEntryPointPublisher */
#define CW_SPACE CW_root_Smp_IEntryPointPublisher

void
CW(_IEntryPointPublisher)
(
    CW() * self
);

const CW(CW_root_Smp, EntryPointCollection) *
CW(GetEntryPoints)
(
    CW() * self
);

CW(CW_root_Smp, IEntryPoint) *
CW(GetEntryPoint)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IEntryPointPublisher" at Smp/./IEntryPointPublisher.h:43:11 (exported to Smp-C/IEntryPointPublisher.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IEntryPointPublisher.h:43:11 (exported to Smp-C/IEntryPointPublisher.h) : Reference type is not supported: IEntryPointPublisher & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IENTRYPOINTPUBLISHER_H */
