/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IEVENTPROVIDER_H
#define CWRAPPER_IEVENTPROVIDER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/EventSourceCollection.h"
#include "Smp-C/IComponent.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSource);

typedef void CW(IEventProvider);

#undef CW_SPACE


/* ### Smp::IEventProvider ### */
#ifndef CW_root_Smp_IEventProvider
#define CW_root_Smp_IEventProvider CW_BUILD_SPACE(CW_root_Smp, IEventProvider)
#endif /* CW_root_Smp_IEventProvider */
#define CW_SPACE CW_root_Smp_IEventProvider

void
CW(_IEventProvider)
(
    CW() * self
);

const CW(CW_root_Smp, EventSourceCollection) *
CW(GetEventSources)
(
    CW() * self
);

CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IEventProvider" at Smp/./IEventProvider.h:42:11 (exported to Smp-C/IEventProvider.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IEventProvider.h:42:11 (exported to Smp-C/IEventProvider.h) : Reference type is not supported: IEventProvider & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IEVENTPROVIDER_H */
