/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IEVENTSOURCE_H
#define CWRAPPER_IEVENTSOURCE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/EventSinkAlreadySubscribed.h"
#include "Smp-C/EventSinkCollection.h"
#include "Smp-C/EventSinkNotSubscribed.h"
#include "Smp-C/InvalidEventSink.h"
#include "Smp-C/IObject.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSink);

typedef void CW(IEventSource);

#undef CW_SPACE


/* ### Smp::IEventSource ### */
#ifndef CW_root_Smp_IEventSource
#define CW_root_Smp_IEventSource CW_BUILD_SPACE(CW_root_Smp, IEventSource)
#endif /* CW_root_Smp_IEventSource */
#define CW_SPACE CW_root_Smp_IEventSource

void
CW(_IEventSource)
(
    CW() * self
);

void
CW(Subscribe)
(
    CW() * self,
    CW(CW_root_Smp, IEventSink) * eventSink
);

void
CW(Unsubscribe)
(
    CW() * self,
    CW(CW_root_Smp, IEventSink) * eventSink
);

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetEventArgType)
(
    CW() * self
);

const CW(CW_root_Smp, EventSinkCollection) *
CW(GetEventSinks)
(
    CW() * self
);

/* Error while processing function "IEventSource" at Smp/IEventSource.h:44:11 (exported to Smp-C/IEventSource.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IEventSource.h:44:11 (exported to Smp-C/IEventSource.h) : Reference type is not supported: IEventSource & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IEVENTSOURCE_H */
