/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IEVENTSINK_H
#define CWRAPPER_IEVENTSINK_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AnySimple.h"
#include "Smp-C/IObject.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSink);

#undef CW_SPACE


/* ### Smp::IEventSink ### */
#ifndef CW_root_Smp_IEventSink
#define CW_root_Smp_IEventSink CW_BUILD_SPACE(CW_root_Smp, IEventSink)
#endif /* CW_root_Smp_IEventSink */
#define CW_SPACE CW_root_Smp_IEventSink

void
CW(_IEventSink)
(
    CW() * self
);

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetEventArgType)
(
    CW() * self
);

void
CW(Notify)
(
    CW() * self,
    CW(CW_root_Smp, IObject) * sender,
    CW(CW_root_Smp, AnySimple) * arg
);

/* Error while processing function "IEventSink" at Smp/IEventSink.h:32:11 (exported to Smp-C/IEventSink.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IEventSink.h:32:11 (exported to Smp-C/IEventSink.h) : Reference type is not supported: IEventSink & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IEVENTSINK_H */
