/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IEVENTCONSUMER_H
#define CWRAPPER_IEVENTCONSUMER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/EventSinkCollection.h"
#include "Smp-C/IComponent.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSink);

typedef void CW(IEventConsumer);

#undef CW_SPACE


/* ### Smp::IEventConsumer ### */
#ifndef CW_root_Smp_IEventConsumer
#define CW_root_Smp_IEventConsumer CW_BUILD_SPACE(CW_root_Smp, IEventConsumer)
#endif /* CW_root_Smp_IEventConsumer */
#define CW_SPACE CW_root_Smp_IEventConsumer

void
CW(_IEventConsumer)
(
    CW() * self
);

const CW(CW_root_Smp, EventSinkCollection) *
CW(GetEventSinks)
(
    CW() * self
);

CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IEventConsumer" at Smp/./IEventConsumer.h:42:11 (exported to Smp-C/IEventConsumer.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IEventConsumer.h:42:11 (exported to Smp-C/IEventConsumer.h) : Reference type is not supported: IEventConsumer & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IEVENTCONSUMER_H */
