/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IFACTORY_H
#define CWRAPPER_IFACTORY_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/InvalidObjectName.h"
#include "Smp-C/IObject.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Uuid.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(IComposite);

typedef void CW(IFactory);

#undef CW_SPACE


/* ### Smp::IFactory ### */
#ifndef CW_root_Smp_IFactory
#define CW_root_Smp_IFactory CW_BUILD_SPACE(CW_root_Smp, IFactory)
#endif /* CW_root_Smp_IFactory */
#define CW_SPACE CW_root_Smp_IFactory

void
CW(_IFactory)
(
    CW() * self
);

/* Error while processing function "GetUuid" at Smp/IFactory.h:50:27 (exported to Smp-C/IFactory.h) : Skipping function that returns a class/struct */

CW(CW_root_Smp, String8)
CW(GetTypeName)
(
    CW() * self
);

CW(CW_root_Smp, IComponent) *
CW(CreateInstance)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, IComposite) * parent
);

void
CW(DeleteInstance)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * instance
);

/* Error while processing function "IFactory" at Smp/IFactory.h:40:11 (exported to Smp-C/IFactory.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IFactory.h:40:11 (exported to Smp-C/IFactory.h) : Reference type is not supported: IFactory & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IFACTORY_H */
