/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IFAILURE_H
#define CWRAPPER_IFAILURE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IPersist.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IFailure);

#undef CW_SPACE


/* ### Smp::IFailure ### */
#ifndef CW_root_Smp_IFailure
#define CW_root_Smp_IFailure CW_BUILD_SPACE(CW_root_Smp, IFailure)
#endif /* CW_root_Smp_IFailure */
#define CW_SPACE CW_root_Smp_IFailure

void
CW(_IFailure)
(
    CW() * self
);

void
CW(Fail)
(
    CW() * self
);

void
CW(Unfail)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsFailed)
(
    CW() * self
);

/* Error while processing function "IFailure" at Smp/IFailure.h:33:11 (exported to Smp-C/IFailure.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IFailure.h:33:11 (exported to Smp-C/IFailure.h) : Reference type is not supported: IFailure & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IFAILURE_H */
