/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IFALLIBLEMODEL_H
#define CWRAPPER_IFALLIBLEMODEL_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/FailureCollection.h"
#include "Smp-C/IModel.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IFailure);

typedef void CW(IFallibleModel);

#undef CW_SPACE


/* ### Smp::IFallibleModel ### */
#ifndef CW_root_Smp_IFallibleModel
#define CW_root_Smp_IFallibleModel CW_BUILD_SPACE(CW_root_Smp, IFallibleModel)
#endif /* CW_root_Smp_IFallibleModel */
#define CW_SPACE CW_root_Smp_IFallibleModel

void
CW(_IFallibleModel)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsFailed)
(
    CW() * self
);

const CW(CW_root_Smp, FailureCollection) *
CW(GetFailures)
(
    CW() * self
);

CW(CW_root_Smp, IFailure) *
CW(GetFailure)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IFallibleModel" at Smp/./IFallibleModel.h:43:11 (exported to Smp-C/IFallibleModel.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IFallibleModel.h:43:11 (exported to Smp-C/IFallibleModel.h) : Reference type is not supported: IFallibleModel & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IFALLIBLEMODEL_H */
