/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IFIELD_H
#define CWRAPPER_IFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IPersist.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/ViewKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IType);

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IField);

#undef CW_SPACE


/* ### Smp::IField ### */
#ifndef CW_root_Smp_IField
#define CW_root_Smp_IField CW_BUILD_SPACE(CW_root_Smp, IField)
#endif /* CW_root_Smp_IField */
#define CW_SPACE CW_root_Smp_IField

void
CW(_IField)
(
    CW() * self
);

CW(CW_root_Smp, ViewKind)
CW(GetView)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsState)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsInput)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsOutput)
(
    CW() * self
);

const CW(CW_root_Smp_Publication, IType) *
CW(GetType)
(
    CW() * self
);

/* Error while processing function "IField" at Smp/IField.h:42:11 (exported to Smp-C/IField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IField.h:42:11 (exported to Smp-C/IField.h) : Reference type is not supported: IField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IFIELD_H */
