/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IFORCIBLEFIELD_H
#define CWRAPPER_IFORCIBLEFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AnySimple.h"
#include "Smp-C/InvalidFieldValue.h"
#include "Smp-C/ISimpleField.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IForcibleField);

#undef CW_SPACE


/* ### Smp::IForcibleField ### */
#ifndef CW_root_Smp_IForcibleField
#define CW_root_Smp_IForcibleField CW_BUILD_SPACE(CW_root_Smp, IForcibleField)
#endif /* CW_root_Smp_IForcibleField */
#define CW_SPACE CW_root_Smp_IForcibleField

void
CW(_IForcibleField)
(
    CW() * self
);

void
CW(Force)
(
    CW() * self,
    CW(CW_root_Smp, AnySimple) * value
);

void
CW(Unforce)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsForced)
(
    CW() * self
);

void
CW(Freeze)
(
    CW() * self
);

/* Error while processing function "IForcibleField" at Smp/./IForcibleField.h:30:11 (exported to Smp-C/IForcibleField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IForcibleField.h:30:11 (exported to Smp-C/IForcibleField.h) : Reference type is not supported: IForcibleField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IFORCIBLEFIELD_H */
