/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ILINKINGCOMPONENT_H
#define CWRAPPER_ILINKINGCOMPONENT_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IComponent.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ILinkingComponent);

#undef CW_SPACE


/* ### Smp::ILinkingComponent ### */
#ifndef CW_root_Smp_ILinkingComponent
#define CW_root_Smp_ILinkingComponent CW_BUILD_SPACE(CW_root_Smp, ILinkingComponent)
#endif /* CW_root_Smp_ILinkingComponent */
#define CW_SPACE CW_root_Smp_ILinkingComponent

void
CW(_ILinkingComponent)
(
    CW() * self
);

void
CW(RemoveLinks)
(
    CW() * self,
    const CW(CW_root_Smp, IComponent) * target
);

/* Error while processing function "ILinkingComponent" at Smp/./ILinkingComponent.h:37:11 (exported to Smp-C/ILinkingComponent.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./ILinkingComponent.h:37:11 (exported to Smp-C/ILinkingComponent.h) : Reference type is not supported: ILinkingComponent & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ILINKINGCOMPONENT_H */
