/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IMODEL_H
#define CWRAPPER_IMODEL_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IComponent.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IModel);

#undef CW_SPACE


/* ### Smp::IModel ### */
#ifndef CW_root_Smp_IModel
#define CW_root_Smp_IModel CW_BUILD_SPACE(CW_root_Smp, IModel)
#endif /* CW_root_Smp_IModel */
#define CW_SPACE CW_root_Smp_IModel

void
CW(_IModel)
(
    CW() * self
);

/* Error while processing function "IModel" at Smp/IModel.h:28:11 (exported to Smp-C/IModel.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IModel.h:28:11 (exported to Smp-C/IModel.h) : Reference type is not supported: IModel & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IMODEL_H */
