/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDOPERATIONNAME_H
#define CWRAPPER_INVALIDOPERATIONNAME_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidOperationName);

#undef CW_SPACE


/* ### Smp::InvalidOperationName ### */
#ifndef CW_root_Smp_InvalidOperationName
#define CW_root_Smp_InvalidOperationName CW_BUILD_SPACE(CW_root_Smp, InvalidOperationName)
#endif /* CW_root_Smp_InvalidOperationName */
#define CW_SPACE CW_root_Smp_InvalidOperationName

void
CW(_InvalidOperationName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
);

/* Error while processing function "InvalidOperationName" at Smp/InvalidOperationName.h:29:11 (exported to Smp-C/InvalidOperationName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidOperationName.h:29:11 (exported to Smp-C/InvalidOperationName.h) : Reference type is not supported: InvalidOperationName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDOPERATIONNAME_H */
