/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDACCESS_H
#define CWRAPPER_INVALIDACCESS_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidAccess);

#undef CW_SPACE


/* ### Smp::InvalidAccess ### */
#ifndef CW_root_Smp_InvalidAccess
#define CW_root_Smp_InvalidAccess CW_BUILD_SPACE(CW_root_Smp, InvalidAccess)
#endif /* CW_root_Smp_InvalidAccess */
#define CW_SPACE CW_root_Smp_InvalidAccess

void
CW(_InvalidAccess)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetPropertyName)
(
    CW() * self
);

/* Error while processing function "InvalidAccess" at Smp/InvalidAccess.h:29:11 (exported to Smp-C/InvalidAccess.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidAccess.h:29:11 (exported to Smp-C/InvalidAccess.h) : Reference type is not supported: InvalidAccess & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDACCESS_H */
