/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDOBJECTNAME_H
#define CWRAPPER_INVALIDOBJECTNAME_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidObjectName);

#undef CW_SPACE


/* ### Smp::InvalidObjectName ### */
#ifndef CW_root_Smp_InvalidObjectName
#define CW_root_Smp_InvalidObjectName CW_BUILD_SPACE(CW_root_Smp, InvalidObjectName)
#endif /* CW_root_Smp_InvalidObjectName */
#define CW_SPACE CW_root_Smp_InvalidObjectName

void
CW(_InvalidObjectName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetInvalidName)
(
    CW() * self
);

/* Error while processing function "InvalidObjectName" at Smp/InvalidObjectName.h:35:11 (exported to Smp-C/InvalidObjectName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidObjectName.h:35:11 (exported to Smp-C/InvalidObjectName.h) : Reference type is not supported: InvalidObjectName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDOBJECTNAME_H */
