/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDEVENTSINK_H
#define CWRAPPER_INVALIDEVENTSINK_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEventSink);

typedef void CW(IEventSource);

typedef void CW(InvalidEventSink);

#undef CW_SPACE


/* ### Smp::InvalidEventSink ### */
#ifndef CW_root_Smp_InvalidEventSink
#define CW_root_Smp_InvalidEventSink CW_BUILD_SPACE(CW_root_Smp, InvalidEventSink)
#endif /* CW_root_Smp_InvalidEventSink */
#define CW_SPACE CW_root_Smp_InvalidEventSink

void
CW(_InvalidEventSink)
(
    CW() * self
);

const CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self
);

const CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self
);

/* Error while processing function "InvalidEventSink" at Smp/InvalidEventSink.h:38:11 (exported to Smp-C/InvalidEventSink.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidEventSink.h:38:11 (exported to Smp-C/InvalidEventSink.h) : Reference type is not supported: InvalidEventSink & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDEVENTSINK_H */
