/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDTYPE_H
#define CWRAPPER_INVALIDTYPE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidType);

#undef CW_SPACE


/* ### Smp::InvalidType ### */
#ifndef CW_root_Smp_InvalidType
#define CW_root_Smp_InvalidType CW_BUILD_SPACE(CW_root_Smp, InvalidType)
#endif /* CW_root_Smp_InvalidType */
#define CW_SPACE CW_root_Smp_InvalidType

void
CW(_InvalidType)
(
    CW() * self
);

/* Error while processing function "InvalidType" at Smp/InvalidType.h:34:11 (exported to Smp-C/InvalidType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidType.h:34:11 (exported to Smp-C/InvalidType.h) : Reference type is not supported: InvalidType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDTYPE_H */
