/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDARRAYSIZE_H
#define CWRAPPER_INVALIDARRAYSIZE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidArraySize);

#undef CW_SPACE


/* ### Smp::InvalidArraySize ### */
#ifndef CW_root_Smp_InvalidArraySize
#define CW_root_Smp_InvalidArraySize CW_BUILD_SPACE(CW_root_Smp, InvalidArraySize)
#endif /* CW_root_Smp_InvalidArraySize */
#define CW_SPACE CW_root_Smp_InvalidArraySize

void
CW(_InvalidArraySize)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetArraySize)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetInvalidSize)
(
    CW() * self
);

/* Error while processing function "InvalidArraySize" at Smp/InvalidArraySize.h:28:11 (exported to Smp-C/InvalidArraySize.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidArraySize.h:28:11 (exported to Smp-C/InvalidArraySize.h) : Reference type is not supported: InvalidArraySize & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDARRAYSIZE_H */
