/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDARRAYINDEX_H
#define CWRAPPER_INVALIDARRAYINDEX_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidArrayIndex);

#undef CW_SPACE


/* ### Smp::InvalidArrayIndex ### */
#ifndef CW_root_Smp_InvalidArrayIndex
#define CW_root_Smp_InvalidArrayIndex CW_BUILD_SPACE(CW_root_Smp, InvalidArrayIndex)
#endif /* CW_root_Smp_InvalidArrayIndex */
#define CW_SPACE CW_root_Smp_InvalidArrayIndex

void
CW(_InvalidArrayIndex)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetInvalidIndex)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetArraySize)
(
    CW() * self
);

/* Error while processing function "InvalidArrayIndex" at Smp/InvalidArrayIndex.h:28:11 (exported to Smp-C/InvalidArrayIndex.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidArrayIndex.h:28:11 (exported to Smp-C/InvalidArrayIndex.h) : Reference type is not supported: InvalidArrayIndex & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDARRAYINDEX_H */
