/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDARRAYVALUE_H
#define CWRAPPER_INVALIDARRAYVALUE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/InvalidFieldValue.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidArrayValue);

#undef CW_SPACE


/* ### Smp::InvalidArrayValue ### */
#ifndef CW_root_Smp_InvalidArrayValue
#define CW_root_Smp_InvalidArrayValue CW_BUILD_SPACE(CW_root_Smp, InvalidArrayValue)
#endif /* CW_root_Smp_InvalidArrayValue */
#define CW_SPACE CW_root_Smp_InvalidArrayValue

void
CW(_InvalidArrayValue)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetInvalidValueIndex)
(
    CW() * self
);

/* Error while processing function "InvalidArrayValue" at Smp/InvalidArrayValue.h:29:11 (exported to Smp-C/InvalidArrayValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidArrayValue.h:29:11 (exported to Smp-C/InvalidArrayValue.h) : Reference type is not supported: InvalidArrayValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDARRAYVALUE_H */
