/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDFIELDNAME_H
#define CWRAPPER_INVALIDFIELDNAME_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidFieldName);

#undef CW_SPACE


/* ### Smp::InvalidFieldName ### */
#ifndef CW_root_Smp_InvalidFieldName
#define CW_root_Smp_InvalidFieldName CW_BUILD_SPACE(CW_root_Smp, InvalidFieldName)
#endif /* CW_root_Smp_InvalidFieldName */
#define CW_SPACE CW_root_Smp_InvalidFieldName

void
CW(_InvalidFieldName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetFieldName)
(
    CW() * self
);

/* Error while processing function "InvalidFieldName" at Smp/InvalidFieldName.h:28:11 (exported to Smp-C/InvalidFieldName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidFieldName.h:28:11 (exported to Smp-C/InvalidFieldName.h) : Reference type is not supported: InvalidFieldName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDFIELDNAME_H */
