/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDPROPERTYVALUE_H
#define CWRAPPER_INVALIDPROPERTYVALUE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/InvalidAnyType.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IProperty);

typedef void CW(InvalidPropertyValue);

#undef CW_SPACE


/* ### Smp::InvalidPropertyValue ### */
#ifndef CW_root_Smp_InvalidPropertyValue
#define CW_root_Smp_InvalidPropertyValue CW_BUILD_SPACE(CW_root_Smp, InvalidPropertyValue)
#endif /* CW_root_Smp_InvalidPropertyValue */
#define CW_SPACE CW_root_Smp_InvalidPropertyValue

void
CW(_InvalidPropertyValue)
(
    CW() * self
);

const CW(CW_root_Smp, IProperty) *
CW(GetProperty)
(
    CW() * self
);

/* Error while processing function "InvalidPropertyValue" at Smp/InvalidPropertyValue.h:37:11 (exported to Smp-C/InvalidPropertyValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidPropertyValue.h:37:11 (exported to Smp-C/InvalidPropertyValue.h) : Reference type is not supported: InvalidPropertyValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDPROPERTYVALUE_H */
