/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDOBJECTTYPE_H
#define CWRAPPER_INVALIDOBJECTTYPE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IObject);

typedef void CW(InvalidObjectType);

#undef CW_SPACE


/* ### Smp::InvalidObjectType ### */
#ifndef CW_root_Smp_InvalidObjectType
#define CW_root_Smp_InvalidObjectType CW_BUILD_SPACE(CW_root_Smp, InvalidObjectType)
#endif /* CW_root_Smp_InvalidObjectType */
#define CW_SPACE CW_root_Smp_InvalidObjectType

void
CW(_InvalidObjectType)
(
    CW() * self
);

const CW(CW_root_Smp, IObject) *
CW(GetInvalidObject)
(
    CW() * self
);

/* Error while processing function "InvalidObjectType" at Smp/InvalidObjectType.h:39:11 (exported to Smp-C/InvalidObjectType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidObjectType.h:39:11 (exported to Smp-C/InvalidObjectType.h) : Reference type is not supported: InvalidObjectType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDOBJECTTYPE_H */
