/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDANYTYPE_H
#define CWRAPPER_INVALIDANYTYPE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AnySimple.h"
#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidAnyType);

#undef CW_SPACE


/* ### Smp::InvalidAnyType ### */
#ifndef CW_root_Smp_InvalidAnyType
#define CW_root_Smp_InvalidAnyType CW_BUILD_SPACE(CW_root_Smp, InvalidAnyType)
#endif /* CW_root_Smp_InvalidAnyType */
#define CW_SPACE CW_root_Smp_InvalidAnyType

void
CW(_InvalidAnyType)
(
    CW() * self
);

/* Error while processing function "GetInvalidValue" at Smp/InvalidAnyType.h:41:32 (exported to Smp-C/InvalidAnyType.h) : Skipping function that returns a class/struct */

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetExpectedType)
(
    CW() * self
);

/* Error while processing function "InvalidAnyType" at Smp/InvalidAnyType.h:32:11 (exported to Smp-C/InvalidAnyType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidAnyType.h:32:11 (exported to Smp-C/InvalidAnyType.h) : Reference type is not supported: InvalidAnyType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDANYTYPE_H */
