/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDPARAMETERINDEX_H
#define CWRAPPER_INVALIDPARAMETERINDEX_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidParameterIndex);

#undef CW_SPACE


/* ### Smp::InvalidParameterIndex ### */
#ifndef CW_root_Smp_InvalidParameterIndex
#define CW_root_Smp_InvalidParameterIndex CW_BUILD_SPACE(CW_root_Smp, InvalidParameterIndex)
#endif /* CW_root_Smp_InvalidParameterIndex */
#define CW_SPACE CW_root_Smp_InvalidParameterIndex

void
CW(_InvalidParameterIndex)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetParameterIndex)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetParameterCount)
(
    CW() * self
);

/* Error while processing function "InvalidParameterIndex" at Smp/InvalidParameterIndex.h:30:11 (exported to Smp-C/InvalidParameterIndex.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParameterIndex.h:30:11 (exported to Smp-C/InvalidParameterIndex.h) : Reference type is not supported: InvalidParameterIndex & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDPARAMETERINDEX_H */
