/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDPARENT_H
#define CWRAPPER_INVALIDPARENT_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IObject);

typedef void CW(InvalidParent);

#undef CW_SPACE


/* ### Smp::InvalidParent ### */
#ifndef CW_root_Smp_InvalidParent
#define CW_root_Smp_InvalidParent CW_BUILD_SPACE(CW_root_Smp, InvalidParent)
#endif /* CW_root_Smp_InvalidParent */
#define CW_SPACE CW_root_Smp_InvalidParent

void
CW(_InvalidParent)
(
    CW() * self
);

const CW(CW_root_Smp, IObject) *
CW(GetParentFound)
(
    CW() * self
);

const CW(CW_root_Smp, IObject) *
CW(GetParentExpected)
(
    CW() * self
);

/* Error while processing function "InvalidParent" at Smp/InvalidParent.h:38:11 (exported to Smp-C/InvalidParent.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParent.h:38:11 (exported to Smp-C/InvalidParent.h) : Reference type is not supported: InvalidParent & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDPARENT_H */
