/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDCOMPONENTSTATE_H
#define CWRAPPER_INVALIDCOMPONENTSTATE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/ComponentStateKind.h"
#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidComponentState);

#undef CW_SPACE


/* ### Smp::InvalidComponentState ### */
#ifndef CW_root_Smp_InvalidComponentState
#define CW_root_Smp_InvalidComponentState CW_BUILD_SPACE(CW_root_Smp, InvalidComponentState)
#endif /* CW_root_Smp_InvalidComponentState */
#define CW_SPACE CW_root_Smp_InvalidComponentState

void
CW(_InvalidComponentState)
(
    CW() * self
);

CW(CW_root_Smp, ComponentStateKind)
CW(GetInvalidState)
(
    CW() * self
);

CW(CW_root_Smp, ComponentStateKind)
CW(GetExpectedState)
(
    CW() * self
);

/* Error while processing function "InvalidComponentState" at Smp/InvalidComponentState.h:29:11 (exported to Smp-C/InvalidComponentState.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidComponentState.h:29:11 (exported to Smp-C/InvalidComponentState.h) : Reference type is not supported: InvalidComponentState & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDCOMPONENTSTATE_H */
