/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDSIMULATORSTATE_H
#define CWRAPPER_INVALIDSIMULATORSTATE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/SimulatorStateKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidSimulatorState);

#undef CW_SPACE


/* ### Smp::InvalidSimulatorState ### */
#ifndef CW_root_Smp_InvalidSimulatorState
#define CW_root_Smp_InvalidSimulatorState CW_BUILD_SPACE(CW_root_Smp, InvalidSimulatorState)
#endif /* CW_root_Smp_InvalidSimulatorState */
#define CW_SPACE CW_root_Smp_InvalidSimulatorState

void
CW(_InvalidSimulatorState)
(
    CW() * self
);

CW(CW_root_Smp, SimulatorStateKind)
CW(GetInvalidState)
(
    CW() * self
);

/* Error while processing function "InvalidSimulatorState" at Smp/InvalidSimulatorState.h:29:11 (exported to Smp-C/InvalidSimulatorState.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidSimulatorState.h:29:11 (exported to Smp-C/InvalidSimulatorState.h) : Reference type is not supported: InvalidSimulatorState & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDSIMULATORSTATE_H */
