/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDSMPVERSION_H
#define CWRAPPER_INVALIDSMPVERSION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidSmpVersion);

#undef CW_SPACE


/* ### Smp::InvalidSmpVersion ### */
#ifndef CW_root_Smp_InvalidSmpVersion
#define CW_root_Smp_InvalidSmpVersion CW_BUILD_SPACE(CW_root_Smp, InvalidSmpVersion)
#endif /* CW_root_Smp_InvalidSmpVersion */
#define CW_SPACE CW_root_Smp_InvalidSmpVersion

void
CW(_InvalidSmpVersion)
(
    CW() * self
);

CW(CW_root_Smp, UInt64)
CW(GetLibrarySmpVersion)
(
    CW() * self
);

/* Error while processing function "InvalidSmpVersion" at Smp/InvalidSmpVersion.h:29:11 (exported to Smp-C/InvalidSmpVersion.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidSmpVersion.h:29:11 (exported to Smp-C/InvalidSmpVersion.h) : Reference type is not supported: InvalidSmpVersion & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDSMPVERSION_H */
