/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDFILE_H
#define CWRAPPER_INVALIDFILE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidFile);

#undef CW_SPACE


/* ### Smp::InvalidFile ### */
#ifndef CW_root_Smp_InvalidFile
#define CW_root_Smp_InvalidFile CW_BUILD_SPACE(CW_root_Smp, InvalidFile)
#endif /* CW_root_Smp_InvalidFile */
#define CW_SPACE CW_root_Smp_InvalidFile

void
CW(_InvalidFile)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetFileName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetErrorMessage)
(
    CW() * self
);

/* Error while processing function "InvalidFile" at Smp/InvalidFile.h:29:11 (exported to Smp-C/InvalidFile.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidFile.h:29:11 (exported to Smp-C/InvalidFile.h) : Reference type is not supported: InvalidFile & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDFILE_H */
