/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDTARGET_H
#define CWRAPPER_INVALIDTARGET_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IField);

typedef void CW(IOutputField);

typedef void CW(InvalidTarget);

#undef CW_SPACE


/* ### Smp::InvalidTarget ### */
#ifndef CW_root_Smp_InvalidTarget
#define CW_root_Smp_InvalidTarget CW_BUILD_SPACE(CW_root_Smp, InvalidTarget)
#endif /* CW_root_Smp_InvalidTarget */
#define CW_SPACE CW_root_Smp_InvalidTarget

void
CW(_InvalidTarget)
(
    CW() * self
);

const CW(CW_root_Smp, IOutputField) *
CW(GetSource)
(
    CW() * self
);

const CW(CW_root_Smp, IField) *
CW(GetTarget)
(
    CW() * self
);

/* Error while processing function "InvalidTarget" at Smp/InvalidTarget.h:38:11 (exported to Smp-C/InvalidTarget.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidTarget.h:38:11 (exported to Smp-C/InvalidTarget.h) : Reference type is not supported: InvalidTarget & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDTARGET_H */
