/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDFIELDVALUE_H
#define CWRAPPER_INVALIDFIELDVALUE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/InvalidAnyType.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IField);

typedef void CW(InvalidFieldValue);

#undef CW_SPACE


/* ### Smp::InvalidFieldValue ### */
#ifndef CW_root_Smp_InvalidFieldValue
#define CW_root_Smp_InvalidFieldValue CW_BUILD_SPACE(CW_root_Smp, InvalidFieldValue)
#endif /* CW_root_Smp_InvalidFieldValue */
#define CW_SPACE CW_root_Smp_InvalidFieldValue

void
CW(_InvalidFieldValue)
(
    CW() * self
);

const CW(CW_root_Smp, IField) *
CW(GetField)
(
    CW() * self
);

/* Error while processing function "InvalidFieldValue" at Smp/InvalidFieldValue.h:37:11 (exported to Smp-C/InvalidFieldValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidFieldValue.h:37:11 (exported to Smp-C/InvalidFieldValue.h) : Reference type is not supported: InvalidFieldValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDFIELDVALUE_H */
