/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDPARAMETERCOUNT_H
#define CWRAPPER_INVALIDPARAMETERCOUNT_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidParameterCount);

#undef CW_SPACE


/* ### Smp::InvalidParameterCount ### */
#ifndef CW_root_Smp_InvalidParameterCount
#define CW_root_Smp_InvalidParameterCount CW_BUILD_SPACE(CW_root_Smp, InvalidParameterCount)
#endif /* CW_root_Smp_InvalidParameterCount */
#define CW_SPACE CW_root_Smp_InvalidParameterCount

void
CW(_InvalidParameterCount)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetOperationParameters)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetRequestParameters)
(
    CW() * self
);

/* Error while processing function "InvalidParameterCount" at Smp/InvalidParameterCount.h:29:11 (exported to Smp-C/InvalidParameterCount.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParameterCount.h:29:11 (exported to Smp-C/InvalidParameterCount.h) : Reference type is not supported: InvalidParameterCount & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDPARAMETERCOUNT_H */
