/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDPARAMETERVALUE_H
#define CWRAPPER_INVALIDPARAMETERVALUE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/InvalidAnyType.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(InvalidParameterValue);

#undef CW_SPACE


/* ### Smp::InvalidParameterValue ### */
#ifndef CW_root_Smp_InvalidParameterValue
#define CW_root_Smp_InvalidParameterValue CW_BUILD_SPACE(CW_root_Smp, InvalidParameterValue)
#endif /* CW_root_Smp_InvalidParameterValue */
#define CW_SPACE CW_root_Smp_InvalidParameterValue

void
CW(_InvalidParameterValue)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetParameterName)
(
    CW() * self
);

/* Error while processing function "InvalidParameterValue" at Smp/InvalidParameterValue.h:31:11 (exported to Smp-C/InvalidParameterValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParameterValue.h:31:11 (exported to Smp-C/InvalidParameterValue.h) : Reference type is not supported: InvalidParameterValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDPARAMETERVALUE_H */
