/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IOBJECT_H
#define CWRAPPER_IOBJECT_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IObject);

#undef CW_SPACE


/* ### Smp::IObject ### */
#ifndef CW_root_Smp_IObject
#define CW_root_Smp_IObject CW_BUILD_SPACE(CW_root_Smp, IObject)
#endif /* CW_root_Smp_IObject */
#define CW_SPACE CW_root_Smp_IObject

void
CW(_IObject)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetDescription)
(
    CW() * self
);

CW(CW_root_Smp, IObject) *
CW(GetParent)
(
    CW() * self
);

CW(CW_root_Smp, IObject) *
CW(GetChild)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "operator=" at Smp/IObject.h:44:11 (exported to Smp-C/IObject.h) : Reference type is not supported: IObject & */

/* Error while processing function "IObject" at Smp/IObject.h:44:11 (exported to Smp-C/IObject.h) : Skipping constructor */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IOBJECT_H */
