/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IOPERATION_H
#define CWRAPPER_IOPERATION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/InvalidOperationName.h"
#include "Smp-C/InvalidParameterCount.h"
#include "Smp-C/InvalidParameterValue.h"
#include "Smp-C/IObject.h"
#include "Smp-C/ParameterCollection.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/ViewKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IParameter);

typedef void CW(IRequest);

typedef void CW(IOperation);

#undef CW_SPACE


/* ### Smp::IOperation ### */
#ifndef CW_root_Smp_IOperation
#define CW_root_Smp_IOperation CW_BUILD_SPACE(CW_root_Smp, IOperation)
#endif /* CW_root_Smp_IOperation */
#define CW_SPACE CW_root_Smp_IOperation

void
CW(_IOperation)
(
    CW() * self
);

const CW(CW_root_Smp, ParameterCollection) *
CW(GetParameters)
(
    CW() * self
);

CW(CW_root_Smp, IParameter) *
CW(GetParameter)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

CW(CW_root_Smp, IParameter) *
CW(GetReturnParameter)
(
    CW() * self
);

CW(CW_root_Smp, ViewKind)
CW(GetView)
(
    CW() * self
);

CW(CW_root_Smp, IRequest) *
CW(CreateRequest)
(
    CW() * self
);

void
CW(Invoke)
(
    CW() * self,
    CW(CW_root_Smp, IRequest) * request
);

void
CW(DeleteRequest)
(
    CW() * self,
    CW(CW_root_Smp, IRequest) * request
);

/* Error while processing function "IOperation" at Smp/IOperation.h:43:11 (exported to Smp-C/IOperation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IOperation.h:43:11 (exported to Smp-C/IOperation.h) : Reference type is not supported: IOperation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IOPERATION_H */
