/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IOUTPUTFIELD_H
#define CWRAPPER_IOUTPUTFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/FieldAlreadyConnected.h"
#include "Smp-C/FieldCollection.h"
#include "Smp-C/FieldNotConnected.h"
#include "Smp-C/IField.h"
#include "Smp-C/InvalidTarget.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IOutputField);

#undef CW_SPACE


/* ### Smp::IOutputField ### */
#ifndef CW_root_Smp_IOutputField
#define CW_root_Smp_IOutputField CW_BUILD_SPACE(CW_root_Smp, IOutputField)
#endif /* CW_root_Smp_IOutputField */
#define CW_SPACE CW_root_Smp_IOutputField

void
CW(_IOutputField)
(
    CW() * self
);

void
CW(Connect)
(
    CW() * self,
    CW(CW_root_Smp, IField) * target
);

void
CW(Disconnect)
(
    CW() * self,
    CW(CW_root_Smp, IField) * target
);

void
CW(Push)
(
    CW() * self
);

const CW(CW_root_Smp, FieldCollection) *
CW(GetInputFields)
(
    CW() * self
);

CW(CW_root_Smp, Bool)
CW(IsAutomatic)
(
    CW() * self
);

/* Error while processing function "IOutputField" at Smp/./IOutputField.h:33:11 (exported to Smp-C/IOutputField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IOutputField.h:33:11 (exported to Smp-C/IOutputField.h) : Reference type is not supported: IOutputField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IOUTPUTFIELD_H */
