/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IPARAMETER_H
#define CWRAPPER_IPARAMETER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IObject.h"
#include "Smp-C/Publication/ParameterDirectionKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IType);

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IParameter);

#undef CW_SPACE


/* ### Smp::IParameter ### */
#ifndef CW_root_Smp_IParameter
#define CW_root_Smp_IParameter CW_BUILD_SPACE(CW_root_Smp, IParameter)
#endif /* CW_root_Smp_IParameter */
#define CW_SPACE CW_root_Smp_IParameter

void
CW(_IParameter)
(
    CW() * self
);

const CW(CW_root_Smp_Publication, IType) *
CW(GetType)
(
    CW() * self
);

CW(CW_root_Smp_Publication, ParameterDirectionKind)
CW(GetDirection)
(
    CW() * self
);

/* Error while processing function "IParameter" at Smp/IParameter.h:41:11 (exported to Smp-C/IParameter.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IParameter.h:41:11 (exported to Smp-C/IParameter.h) : Reference type is not supported: IParameter & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IPARAMETER_H */
