/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IPERSIST_H
#define CWRAPPER_IPERSIST_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/CannotRestore.h"
#include "Smp-C/CannotStore.h"
#include "Smp-C/IObject.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IStorageReader);

typedef void CW(IStorageWriter);

typedef void CW(IPersist);

#undef CW_SPACE


/* ### Smp::IPersist ### */
#ifndef CW_root_Smp_IPersist
#define CW_root_Smp_IPersist CW_BUILD_SPACE(CW_root_Smp, IPersist)
#endif /* CW_root_Smp_IPersist */
#define CW_SPACE CW_root_Smp_IPersist

void
CW(_IPersist)
(
    CW() * self
);

void
CW(Restore)
(
    CW() * self,
    CW(CW_root_Smp, IStorageReader) * reader
);

void
CW(Store)
(
    CW() * self,
    CW(CW_root_Smp, IStorageWriter) * writer
);

/* Error while processing function "IPersist" at Smp/IPersist.h:43:11 (exported to Smp-C/IPersist.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IPersist.h:43:11 (exported to Smp-C/IPersist.h) : Reference type is not supported: IPersist & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IPERSIST_H */
