/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IPUBLICATION_H
#define CWRAPPER_IPUBLICATION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AccessKind.h"
#include "Smp-C/DuplicateName.h"
#include "Smp-C/InvalidObjectName.h"
#include "Smp-C/InvalidType.h"
#include "Smp-C/NoDynamicInvocation.h"
#include "Smp-C/OperationCollection.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/PropertyCollection.h"
#include "Smp-C/Publication/IPublishField.h"
#include "Smp-C/Publication/TypeNotRegistered.h"
#include "Smp-C/Uuid.h"
#include "Smp-C/ViewKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IOperation);

typedef void CW(IProperty);

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IPublishOperation);

typedef void CW(ITypeRegistry);

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IPublication);

#undef CW_SPACE


/* ### Smp::IPublication ### */
#ifndef CW_root_Smp_IPublication
#define CW_root_Smp_IPublication CW_BUILD_SPACE(CW_root_Smp, IPublication)
#endif /* CW_root_Smp_IPublication */
#define CW_SPACE CW_root_Smp_IPublication

void
CW(_IPublication)
(
    CW() * self
);

CW(CW_root_Smp_Publication, IPublishOperation) *
CW(PublishOperationRaw)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, ViewKind) view
);

void
CW(PublishOperation)
(
    CW() * self,
    CW(CW_root_Smp, IOperation) * operation
);

CW(CW_root_Smp, IProperty) *
CW(PublishPropertyRaw)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Uuid) * typeUuid,
    CW(CW_root_Smp, AccessKind) accessKind,
    CW(CW_root_Smp, ViewKind) view
);

void
CW(PublishProperty)
(
    CW() * self,
    CW(CW_root_Smp, IProperty) * property
);

CW(CW_root_Smp, IProperty) *
CW(GetProperty)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

const CW(CW_root_Smp, PropertyCollection) *
CW(GetProperties)
(
    CW() * self
);

CW(CW_root_Smp, IOperation) *
CW(GetOperation)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

const CW(CW_root_Smp, OperationCollection) *
CW(GetOperations)
(
    CW() * self
);

CW(CW_root_Smp_Publication, ITypeRegistry) *
CW(GetTypeRegistry)
(
    CW() * self
);

void
CW(Unpublish)
(
    CW() * self
);

/* Error while processing function "IPublication" at Smp/./IPublication.h:55:11 (exported to Smp-C/IPublication.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IPublication.h:55:11 (exported to Smp-C/IPublication.h) : Reference type is not supported: IPublication & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IPUBLICATION_H */
