/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IREFERENCE_H
#define CWRAPPER_IREFERENCE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/CannotRemove.h"
#include "Smp-C/ComponentCollection.h"
#include "Smp-C/InvalidObjectType.h"
#include "Smp-C/IObject.h"
#include "Smp-C/NotReferenced.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/ReferenceFull.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(IReference);

#undef CW_SPACE


/* ### Smp::IReference ### */
#ifndef CW_root_Smp_IReference
#define CW_root_Smp_IReference CW_BUILD_SPACE(CW_root_Smp, IReference)
#endif /* CW_root_Smp_IReference */
#define CW_SPACE CW_root_Smp_IReference

void
CW(_IReference)
(
    CW() * self
);

const CW(CW_root_Smp, ComponentCollection) *
CW(GetComponents)
(
    CW() * self
);

CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

void
CW(AddComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
);

void
CW(RemoveComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
);

CW(CW_root_Smp, Int64)
CW(GetCount)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetUpper)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetLower)
(
    CW() * self
);

/* Error while processing function "IReference" at Smp/IReference.h:45:11 (exported to Smp-C/IReference.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IReference.h:45:11 (exported to Smp-C/IReference.h) : Reference type is not supported: IReference & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IREFERENCE_H */
