/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IREQUEST_H
#define CWRAPPER_IREQUEST_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AnySimple.h"
#include "Smp-C/InvalidParameterIndex.h"
#include "Smp-C/InvalidParameterValue.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/RequestType.h"
#include "Smp-C/VoidOperation.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IRequest);

#undef CW_SPACE


/* ### Smp::IRequest ### */
#ifndef CW_root_Smp_IRequest
#define CW_root_Smp_IRequest CW_BUILD_SPACE(CW_root_Smp, IRequest)
#endif /* CW_root_Smp_IRequest */
#define CW_SPACE CW_root_Smp_IRequest

void
CW(_IRequest)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetName)
(
    CW() * self
);

CW(CW_root_Smp, RequestType)
CW(GetType)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetParameterCount)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetParameterIndex)
(
    CW() * self,
    CW(CW_root_Smp, String8) parameterName
);

void
CW(SetParameterValue)
(
    CW() * self,
    CW(CW_root_Smp, Int32) index,
    CW(CW_root_Smp, AnySimple) * value
);

/* Error while processing function "GetParameterValue" at Smp/./IRequest.h:102:32 (exported to Smp-C/IRequest.h) : Skipping function that returns a class/struct */

void
CW(SetReturnValue)
(
    CW() * self,
    CW(CW_root_Smp, AnySimple) * value
);

/* Error while processing function "GetReturnValue" at Smp/./IRequest.h:120:32 (exported to Smp-C/IRequest.h) : Skipping function that returns a class/struct */

/* Error while processing function "operator=" at Smp/./IRequest.h:34:11 (exported to Smp-C/IRequest.h) : Reference type is not supported: IRequest & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IREQUEST_H */
