/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISERVICE_H
#define CWRAPPER_ISERVICE_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IComponent.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IService);

#undef CW_SPACE


/* ### Smp::IService ### */
#ifndef CW_root_Smp_IService
#define CW_root_Smp_IService CW_BUILD_SPACE(CW_root_Smp, IService)
#endif /* CW_root_Smp_IService */
#define CW_SPACE CW_root_Smp_IService

void
CW(_IService)
(
    CW() * self
);

/* Error while processing function "IService" at Smp/./IService.h:28:11 (exported to Smp-C/IService.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IService.h:28:11 (exported to Smp-C/IService.h) : Reference type is not supported: IService & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISERVICE_H */
