/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISIMPLEFIELD_H
#define CWRAPPER_ISIMPLEFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AnySimple.h"
#include "Smp-C/IField.h"
#include "Smp-C/InvalidFieldValue.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ISimpleField);

#undef CW_SPACE


/* ### Smp::ISimpleField ### */
#ifndef CW_root_Smp_ISimpleField
#define CW_root_Smp_ISimpleField CW_BUILD_SPACE(CW_root_Smp, ISimpleField)
#endif /* CW_root_Smp_ISimpleField */
#define CW_SPACE CW_root_Smp_ISimpleField

void
CW(_ISimpleField)
(
    CW() * self
);

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetPrimitiveTypeKind)
(
    CW() * self
);

/* Error while processing function "GetValue" at Smp/ISimpleField.h:43:32 (exported to Smp-C/ISimpleField.h) : Skipping function that returns a class/struct */

void
CW(SetValue)
(
    CW() * self,
    CW(CW_root_Smp, AnySimple) * value
);

/* Error while processing function "ISimpleField" at Smp/ISimpleField.h:30:11 (exported to Smp-C/ISimpleField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/ISimpleField.h:30:11 (exported to Smp-C/ISimpleField.h) : Reference type is not supported: ISimpleField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISIMPLEFIELD_H */
