/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISIMPLEARRAYFIELD_H
#define CWRAPPER_ISIMPLEARRAYFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/AnySimple.h"
#include "Smp-C/AnySimpleArray.h"
#include "Smp-C/IField.h"
#include "Smp-C/InvalidArrayIndex.h"
#include "Smp-C/InvalidArraySize.h"
#include "Smp-C/InvalidArrayValue.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ISimpleArrayField);

#undef CW_SPACE


/* ### Smp::ISimpleArrayField ### */
#ifndef CW_root_Smp_ISimpleArrayField
#define CW_root_Smp_ISimpleArrayField CW_BUILD_SPACE(CW_root_Smp, ISimpleArrayField)
#endif /* CW_root_Smp_ISimpleArrayField */
#define CW_SPACE CW_root_Smp_ISimpleArrayField

void
CW(_ISimpleArrayField)
(
    CW() * self
);

CW(CW_root_Smp, UInt64)
CW(GetSize)
(
    CW() * self
);

/* Error while processing function "GetValue" at Smp/./ISimpleArrayField.h:50:32 (exported to Smp-C/ISimpleArrayField.h) : Skipping function that returns a class/struct */

void
CW(SetValue)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) index,
    CW(CW_root_Smp, AnySimple) * value
);

void
CW(GetValues)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) length,
    CW(CW_root_Smp, AnySimple) * values,
    CW(CW_root_Smp, UInt64) startIndex
);

void
CW(SetValues)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) length,
    CW(CW_root_Smp, AnySimpleArray) values,
    CW(CW_root_Smp, UInt64) startIndex
);

/* Error while processing function "ISimpleArrayField" at Smp/./ISimpleArrayField.h:33:11 (exported to Smp-C/ISimpleArrayField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./ISimpleArrayField.h:33:11 (exported to Smp-C/ISimpleArrayField.h) : Reference type is not supported: ISimpleArrayField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISIMPLEARRAYFIELD_H */
