/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISTORAGEWRITER_H
#define CWRAPPER_ISTORAGEWRITER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Void.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IStorageWriter);

#undef CW_SPACE


/* ### Smp::IStorageWriter ### */
#ifndef CW_root_Smp_IStorageWriter
#define CW_root_Smp_IStorageWriter CW_BUILD_SPACE(CW_root_Smp, IStorageWriter)
#endif /* CW_root_Smp_IStorageWriter */
#define CW_SPACE CW_root_Smp_IStorageWriter

void
CW(_IStorageWriter)
(
    CW() * self
);

void
CW(Store)
(
    CW() * self,
    const CW(CW_root_Smp, Void) * address,
    CW(CW_root_Smp, UInt64) size
);

CW(CW_root_Smp, String8)
CW(GetStateVectorFileName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetStateVectorFilePath)
(
    CW() * self
);

/* Error while processing function "operator=" at Smp/./IStorageWriter.h:32:11 (exported to Smp-C/IStorageWriter.h) : Reference type is not supported: IStorageWriter & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISTORAGEWRITER_H */
