/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISTORAGEREADER_H
#define CWRAPPER_ISTORAGEREADER_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Void.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IStorageReader);

#undef CW_SPACE


/* ### Smp::IStorageReader ### */
#ifndef CW_root_Smp_IStorageReader
#define CW_root_Smp_IStorageReader CW_BUILD_SPACE(CW_root_Smp, IStorageReader)
#endif /* CW_root_Smp_IStorageReader */
#define CW_SPACE CW_root_Smp_IStorageReader

void
CW(_IStorageReader)
(
    CW() * self
);

void
CW(Restore)
(
    CW() * self,
    CW(CW_root_Smp, Void) * address,
    CW(CW_root_Smp, UInt64) size
);

CW(CW_root_Smp, String8)
CW(GetStateVectorFileName)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetStateVectorFilePath)
(
    CW() * self
);

/* Error while processing function "operator=" at Smp/./IStorageReader.h:32:11 (exported to Smp-C/IStorageReader.h) : Reference type is not supported: IStorageReader & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISTORAGEREADER_H */
