/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISTRUCTUREFIELD_H
#define CWRAPPER_ISTRUCTUREFIELD_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/FieldCollection.h"
#include "Smp-C/IField.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IStructureField);

#undef CW_SPACE


/* ### Smp::IStructureField ### */
#ifndef CW_root_Smp_IStructureField
#define CW_root_Smp_IStructureField CW_BUILD_SPACE(CW_root_Smp, IStructureField)
#endif /* CW_root_Smp_IStructureField */
#define CW_SPACE CW_root_Smp_IStructureField

void
CW(_IStructureField)
(
    CW() * self
);

const CW(CW_root_Smp, FieldCollection) *
CW(GetFields)
(
    CW() * self
);

CW(CW_root_Smp, IField) *
CW(GetField)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
);

/* Error while processing function "IStructureField" at Smp/./IStructureField.h:29:11 (exported to Smp-C/IStructureField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IStructureField.h:29:11 (exported to Smp-C/IStructureField.h) : Reference type is not supported: IStructureField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISTRUCTUREFIELD_H */
