/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_LIBRARYLOADINGFLAG_H
#define CWRAPPER_LIBRARYLOADINGFLAG_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* #include <iosfwd> */
#include "Smp-C/Int32.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef CW(Int32) CW(LibraryLoadingFlag);

/* Error while processing function "operator<<" at Smp/LibraryLoadingFlag.h:48:19 (exported to Smp-C/LibraryLoadingFlag.h) : Reference type is not supported: std::ostream & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_LIBRARYLOADINGFLAG_H */
