/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_NODYNAMICINVOCATION_H
#define CWRAPPER_NODYNAMICINVOCATION_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(NoDynamicInvocation);

#undef CW_SPACE


/* ### Smp::NoDynamicInvocation ### */
#ifndef CW_root_Smp_NoDynamicInvocation
#define CW_root_Smp_NoDynamicInvocation CW_BUILD_SPACE(CW_root_Smp, NoDynamicInvocation)
#endif /* CW_root_Smp_NoDynamicInvocation */
#define CW_SPACE CW_root_Smp_NoDynamicInvocation

void
CW(_NoDynamicInvocation)
(
    CW() * self
);

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
);

/* Error while processing function "NoDynamicInvocation" at Smp/NoDynamicInvocation.h:37:11 (exported to Smp-C/NoDynamicInvocation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/NoDynamicInvocation.h:37:11 (exported to Smp-C/NoDynamicInvocation.h) : Reference type is not supported: NoDynamicInvocation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_NODYNAMICINVOCATION_H */
