/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_NOTCONTAINED_H
#define CWRAPPER_NOTCONTAINED_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(NotContained);

#undef CW_SPACE


/* ### Smp::NotContained ### */
#ifndef CW_root_Smp_NotContained
#define CW_root_Smp_NotContained CW_BUILD_SPACE(CW_root_Smp, NotContained)
#endif /* CW_root_Smp_NotContained */
#define CW_SPACE CW_root_Smp_NotContained

void
CW(_NotContained)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetContainerName)
(
    CW() * self
);

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
);

/* Error while processing function "NotContained" at Smp/NotContained.h:38:11 (exported to Smp-C/NotContained.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/NotContained.h:38:11 (exported to Smp-C/NotContained.h) : Reference type is not supported: NotContained & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_NOTCONTAINED_H */
