/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_NOTREFERENCED_H
#define CWRAPPER_NOTREFERENCED_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

typedef void CW(NotReferenced);

#undef CW_SPACE


/* ### Smp::NotReferenced ### */
#ifndef CW_root_Smp_NotReferenced
#define CW_root_Smp_NotReferenced CW_BUILD_SPACE(CW_root_Smp, NotReferenced)
#endif /* CW_root_Smp_NotReferenced */
#define CW_SPACE CW_root_Smp_NotReferenced

void
CW(_NotReferenced)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetReferenceName)
(
    CW() * self
);

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
);

/* Error while processing function "NotReferenced" at Smp/NotReferenced.h:38:11 (exported to Smp-C/NotReferenced.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/NotReferenced.h:38:11 (exported to Smp-C/NotReferenced.h) : Reference type is not supported: NotReferenced & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_NOTREFERENCED_H */
