/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_PRIMITIVETYPES_H
#define CWRAPPER_PRIMITIVETYPES_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* #include <climits> */
#include "Smp-C/Char8.h"
#include "Smp-C/Bool.h"
#include "Smp-C/Int8.h"
#include "Smp-C/UInt8.h"
#include "Smp-C/Int16.h"
#include "Smp-C/UInt16.h"
#include "Smp-C/Int32.h"
#include "Smp-C/UInt32.h"
#include "Smp-C/Int64.h"
#include "Smp-C/UInt64.h"
#include "Smp-C/Float32.h"
#include "Smp-C/Float64.h"
#include "Smp-C/Duration.h"
#include "Smp-C/DateTime.h"
#include "Smp-C/String8.h"
#include "Smp-C/PrimitiveTypeKind.h"
#include "Smp-C/Uuid.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(Uuids);

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_PRIMITIVETYPES_H */
