/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_REFERENCEFULL_H
#define CWRAPPER_REFERENCEFULL_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(ReferenceFull);

#undef CW_SPACE


/* ### Smp::ReferenceFull ### */
#ifndef CW_root_Smp_ReferenceFull
#define CW_root_Smp_ReferenceFull CW_BUILD_SPACE(CW_root_Smp, ReferenceFull)
#endif /* CW_root_Smp_ReferenceFull */
#define CW_SPACE CW_root_Smp_ReferenceFull

void
CW(_ReferenceFull)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetReferenceName)
(
    CW() * self
);

CW(CW_root_Smp, Int64)
CW(GetReferenceSize)
(
    CW() * self
);

/* Error while processing function "ReferenceFull" at Smp/ReferenceFull.h:29:11 (exported to Smp-C/ReferenceFull.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/ReferenceFull.h:29:11 (exported to Smp-C/ReferenceFull.h) : Reference type is not supported: ReferenceFull & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_REFERENCEFULL_H */
