/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_UUID_H
#define CWRAPPER_UUID_H

#include "./CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* #include <array> */
#include <stdint.h>
/* #include <iosfwd> */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### std ### */
#ifndef CW_root_std
#define CW_root_std CW_BUILD_SPACE(CW_root, std)
#endif /* CW_root_std */
#define CW_SPACE CW_root_std

typedef void CW(hash);

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(Uuid);

#undef CW_SPACE


/* ### Smp::Uuid ### */
#ifndef CW_root_Smp_Uuid
#define CW_root_Smp_Uuid CW_BUILD_SPACE(CW_root_Smp, Uuid)
#endif /* CW_root_Smp_Uuid */
#define CW_SPACE CW_root_Smp_Uuid

/* Error while processing function "Uuid" at Smp/Uuid.h:57:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:71:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:100:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:117:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:127:18 (exported to Smp-C/Uuid.h) : Skipping constructor */

void
CW(_Uuid)
(
    CW() * self
);

/* Error while processing function "Uuid" at Smp/Uuid.h:134:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:137:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Uuid.h:140:15 (exported to Smp-C/Uuid.h) : Reference type is not supported: Uuid & */

/* Error while processing function "operator=" at Smp/Uuid.h:143:15 (exported to Smp-C/Uuid.h) : Reference type is not supported: Uuid & */

/* Error while processing function "operator==" at Smp/Uuid.h:148:14 (exported to Smp-C/Uuid.h) : Reference type is not supported: const Smp::Uuid & */

/* Error while processing function "operator!=" at Smp/Uuid.h:154:14 (exported to Smp-C/Uuid.h) : Reference type is not supported: const Smp::Uuid & */

/* Error while processing function "operator<" at Smp/Uuid.h:160:14 (exported to Smp-C/Uuid.h) : Reference type is not supported: const Uuid & */

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

/* Error while processing function "operator<<" at Smp/Uuid.h:165:19 (exported to Smp-C/Uuid.h) : Reference type is not supported: std::ostream & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_UUID_H */
