/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_DUPLICATELITERAL_H
#define CWRAPPER_DUPLICATELITERAL_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(DuplicateLiteral);

#undef CW_SPACE


/* ### Smp::Publication::DuplicateLiteral ### */
#ifndef CW_root_Smp_Publication_DuplicateLiteral
#define CW_root_Smp_Publication_DuplicateLiteral CW_BUILD_SPACE(CW_root_Smp_Publication, DuplicateLiteral)
#endif /* CW_root_Smp_Publication_DuplicateLiteral */
#define CW_SPACE CW_root_Smp_Publication_DuplicateLiteral

void
CW(_DuplicateLiteral)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetLiteralName)
(
    CW() * self
);

CW(CW_root_Smp, Int32)
CW(GetLiteralValue)
(
    CW() * self
);

/* Error while processing function "DuplicateLiteral" at Smp/./Publication/DuplicateLiteral.h:33:15 (exported to Smp-C/Publication/DuplicateLiteral.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/DuplicateLiteral.h:33:15 (exported to Smp-C/Publication/DuplicateLiteral.h) : Reference type is not supported: DuplicateLiteral & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_DUPLICATELITERAL_H */
