/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IARRAYTYPE_H
#define CWRAPPER_IARRAYTYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Publication/IType.h"
#include "Smp-C/Publication/TypeNotRegistered.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IArrayType);

#undef CW_SPACE


/* ### Smp::Publication::IArrayType ### */
#ifndef CW_root_Smp_Publication_IArrayType
#define CW_root_Smp_Publication_IArrayType CW_BUILD_SPACE(CW_root_Smp_Publication, IArrayType)
#endif /* CW_root_Smp_Publication_IArrayType */
#define CW_SPACE CW_root_Smp_Publication_IArrayType

void
CW(_IArrayType)
(
    CW() * self
);

CW(CW_root_Smp, UInt64)
CW(GetSize)
(
    CW() * self
);

const CW(CW_root_Smp_Publication, IType) *
CW(GetItemType)
(
    CW() * self
);

/* Error while processing function "IArrayType" at Smp/./Publication/IArrayType.h:32:15 (exported to Smp-C/Publication/IArrayType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IArrayType.h:32:15 (exported to Smp-C/Publication/IArrayType.h) : Reference type is not supported: IArrayType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IARRAYTYPE_H */
