/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ICLASSTYPE_H
#define CWRAPPER_ICLASSTYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Publication/IStructureType.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IClassType);

#undef CW_SPACE


/* ### Smp::Publication::IClassType ### */
#ifndef CW_root_Smp_Publication_IClassType
#define CW_root_Smp_Publication_IClassType CW_BUILD_SPACE(CW_root_Smp_Publication, IClassType)
#endif /* CW_root_Smp_Publication_IClassType */
#define CW_SPACE CW_root_Smp_Publication_IClassType

void
CW(_IClassType)
(
    CW() * self
);

/* Error while processing function "IClassType" at Smp/./Publication/IClassType.h:30:15 (exported to Smp-C/Publication/IClassType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IClassType.h:30:15 (exported to Smp-C/Publication/IClassType.h) : Reference type is not supported: IClassType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ICLASSTYPE_H */
