/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IENUMERATIONTYPE_H
#define CWRAPPER_IENUMERATIONTYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/DuplicateName.h"
#include "Smp-C/InvalidObjectName.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Publication/DuplicateLiteral.h"
#include "Smp-C/Publication/IType.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IEnumerationType);

#undef CW_SPACE


/* ### Smp::Publication::IEnumerationType ### */
#ifndef CW_root_Smp_Publication_IEnumerationType
#define CW_root_Smp_Publication_IEnumerationType CW_BUILD_SPACE(CW_root_Smp_Publication, IEnumerationType)
#endif /* CW_root_Smp_Publication_IEnumerationType */
#define CW_SPACE CW_root_Smp_Publication_IEnumerationType

void
CW(_IEnumerationType)
(
    CW() * self
);

void
CW(AddLiteral)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Int32) value
);

/* Error while processing function "IEnumerationType" at Smp/./Publication/IEnumerationType.h:34:15 (exported to Smp-C/Publication/IEnumerationType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IEnumerationType.h:34:15 (exported to Smp-C/Publication/IEnumerationType.h) : Reference type is not supported: IEnumerationType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IENUMERATIONTYPE_H */
