/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDPARAMETERDIRECTION_H
#define CWRAPPER_INVALIDPARAMETERDIRECTION_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(InvalidParameterDirection);

#undef CW_SPACE


/* ### Smp::Publication::InvalidParameterDirection ### */
#ifndef CW_root_Smp_Publication_InvalidParameterDirection
#define CW_root_Smp_Publication_InvalidParameterDirection CW_BUILD_SPACE(CW_root_Smp_Publication, InvalidParameterDirection)
#endif /* CW_root_Smp_Publication_InvalidParameterDirection */
#define CW_SPACE CW_root_Smp_Publication_InvalidParameterDirection

void
CW(_InvalidParameterDirection)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetParameterName)
(
    CW() * self
);

/* Error while processing function "InvalidParameterDirection" at Smp/Publication/InvalidParameterDirection.h:32:15 (exported to Smp-C/Publication/InvalidParameterDirection.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/InvalidParameterDirection.h:32:15 (exported to Smp-C/Publication/InvalidParameterDirection.h) : Reference type is not supported: InvalidParameterDirection & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDPARAMETERDIRECTION_H */
