/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDARRAYITEMTYPE_H
#define CWRAPPER_INVALIDARRAYITEMTYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(InvalidArrayItemType);

#undef CW_SPACE


/* ### Smp::Publication::InvalidArrayItemType ### */
#ifndef CW_root_Smp_Publication_InvalidArrayItemType
#define CW_root_Smp_Publication_InvalidArrayItemType CW_BUILD_SPACE(CW_root_Smp_Publication, InvalidArrayItemType)
#endif /* CW_root_Smp_Publication_InvalidArrayItemType */
#define CW_SPACE CW_root_Smp_Publication_InvalidArrayItemType

void
CW(_InvalidArrayItemType)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetTypeName)
(
    CW() * self
);

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetType)
(
    CW() * self
);

/* Error while processing function "InvalidArrayItemType" at Smp/Publication/InvalidArrayItemType.h:32:15 (exported to Smp-C/Publication/InvalidArrayItemType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/InvalidArrayItemType.h:32:15 (exported to Smp-C/Publication/InvalidArrayItemType.h) : Reference type is not supported: InvalidArrayItemType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDARRAYITEMTYPE_H */
