/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IPUBLISHOPERATION_H
#define CWRAPPER_IPUBLISHOPERATION_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/DuplicateName.h"
#include "Smp-C/InvalidObjectName.h"
#include "Smp-C/InvalidType.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Publication/InvalidParameterDirection.h"
#include "Smp-C/Publication/ParameterDirectionKind.h"
#include "Smp-C/Publication/TypeNotRegistered.h"
#include "Smp-C/Uuid.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IPublishOperation);

#undef CW_SPACE


/* ### Smp::Publication::IPublishOperation ### */
#ifndef CW_root_Smp_Publication_IPublishOperation
#define CW_root_Smp_Publication_IPublishOperation CW_BUILD_SPACE(CW_root_Smp_Publication, IPublishOperation)
#endif /* CW_root_Smp_Publication_IPublishOperation */
#define CW_SPACE CW_root_Smp_Publication_IPublishOperation

void
CW(_IPublishOperation)
(
    CW() * self
);

void
CW(PublishParameter)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Uuid) * typeUuid,
    CW(CW_root_Smp_Publication, ParameterDirectionKind) direction
);

/* Error while processing function "operator=" at Smp/./Publication/IPublishOperation.h:38:15 (exported to Smp-C/Publication/IPublishOperation.h) : Reference type is not supported: IPublishOperation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IPUBLISHOPERATION_H */
