/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISTRUCTURETYPE_H
#define CWRAPPER_ISTRUCTURETYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/DuplicateName.h"
#include "Smp-C/InvalidObjectName.h"
#include "Smp-C/InvalidType.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Publication/IType.h"
#include "Smp-C/Publication/TypeNotRegistered.h"
#include "Smp-C/Uuid.h"
#include "Smp-C/ViewKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IStructureType);

#undef CW_SPACE


/* ### Smp::Publication::IStructureType ### */
#ifndef CW_root_Smp_Publication_IStructureType
#define CW_root_Smp_Publication_IStructureType CW_BUILD_SPACE(CW_root_Smp_Publication, IStructureType)
#endif /* CW_root_Smp_Publication_IStructureType */
#define CW_SPACE CW_root_Smp_Publication_IStructureType

void
CW(_IStructureType)
(
    CW() * self
);

void
CW(AddField)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Uuid) * uuid,
    CW(CW_root_Smp, UInt64) offset,
    CW(CW_root_Smp, ViewKind) view,
    CW(CW_root_Smp, Bool) state,
    CW(CW_root_Smp, Bool) input,
    CW(CW_root_Smp, Bool) output
);

/* Error while processing function "IStructureType" at Smp/Publication/IStructureType.h:37:15 (exported to Smp-C/Publication/IStructureType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/IStructureType.h:37:15 (exported to Smp-C/Publication/IStructureType.h) : Reference type is not supported: IStructureType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISTRUCTURETYPE_H */
