/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ISTRINGTYPE_H
#define CWRAPPER_ISTRINGTYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Publication/IType.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IStringType);

#undef CW_SPACE


/* ### Smp::Publication::IStringType ### */
#ifndef CW_root_Smp_Publication_IStringType
#define CW_root_Smp_Publication_IStringType CW_BUILD_SPACE(CW_root_Smp_Publication, IStringType)
#endif /* CW_root_Smp_Publication_IStringType */
#define CW_SPACE CW_root_Smp_Publication_IStringType

void
CW(_IStringType)
(
    CW() * self
);

CW(CW_root_Smp, UInt64)
CW(GetMaxLength)
(
    CW() * self
);

/* Error while processing function "IStringType" at Smp/./Publication/IStringType.h:31:15 (exported to Smp-C/Publication/IStringType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IStringType.h:31:15 (exported to Smp-C/Publication/IStringType.h) : Reference type is not supported: IStringType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ISTRINGTYPE_H */
