/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ITYPE_H
#define CWRAPPER_ITYPE_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/DuplicateName.h"
#include "Smp-C/InvalidObjectName.h"
#include "Smp-C/InvalidType.h"
#include "Smp-C/IObject.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Publication/TypeNotRegistered.h"
#include "Smp-C/Uuid.h"
#include "Smp-C/ViewKind.h"
#include "Smp-C/Void.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IField);

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IPublishField);

typedef void CW(IType);

#undef CW_SPACE


/* ### Smp::Publication::IType ### */
#ifndef CW_root_Smp_Publication_IType
#define CW_root_Smp_Publication_IType CW_BUILD_SPACE(CW_root_Smp_Publication, IType)
#endif /* CW_root_Smp_Publication_IType */
#define CW_SPACE CW_root_Smp_Publication_IType

void
CW(_IType)
(
    CW() * self
);

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetPrimitiveTypeKind)
(
    CW() * self
);

/* Error while processing function "GetUuid" at Smp/Publication/IType.h:67:31 (exported to Smp-C/Publication/IType.h) : Skipping function that returns a class/struct */

CW(CW_root_Smp, IField) *
CW(Publish)
(
    CW() * self,
    CW(CW_root_Smp_Publication, IPublishField) * receiver,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Void) * address,
    CW(CW_root_Smp, ViewKind) view,
    CW(CW_root_Smp, Bool) state,
    CW(CW_root_Smp, Bool) input,
    CW(CW_root_Smp, Bool) output
);

/* Error while processing function "IType" at Smp/Publication/IType.h:52:15 (exported to Smp-C/Publication/IType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/IType.h:52:15 (exported to Smp-C/Publication/IType.h) : Reference type is not supported: IType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ITYPE_H */
