/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_PARAMETERDIRECTIONKIND_H
#define CWRAPPER_PARAMETERDIRECTIONKIND_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* #include <iosfwd> */
#include "Smp-C/Int32.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef CW(CW_root_Smp, Int32) CW(ParameterDirectionKind);

/* Error while processing function "operator<<" at Smp/Publication/ParameterDirectionKind.h:54:23 (exported to Smp-C/Publication/ParameterDirectionKind.h) : Reference type is not supported: std::ostream & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_PARAMETERDIRECTIONKIND_H */
