/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_TYPEALREADYREGISTERED_H
#define CWRAPPER_TYPEALREADYREGISTERED_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(IType);

typedef void CW(TypeAlreadyRegistered);

#undef CW_SPACE


/* ### Smp::Publication::TypeAlreadyRegistered ### */
#ifndef CW_root_Smp_Publication_TypeAlreadyRegistered
#define CW_root_Smp_Publication_TypeAlreadyRegistered CW_BUILD_SPACE(CW_root_Smp_Publication, TypeAlreadyRegistered)
#endif /* CW_root_Smp_Publication_TypeAlreadyRegistered */
#define CW_SPACE CW_root_Smp_Publication_TypeAlreadyRegistered

void
CW(_TypeAlreadyRegistered)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetTypeName)
(
    CW() * self
);

const CW(CW_root_Smp_Publication, IType) *
CW(GetType)
(
    CW() * self
);

/* Error while processing function "TypeAlreadyRegistered" at Smp/Publication/TypeAlreadyRegistered.h:45:15 (exported to Smp-C/Publication/TypeAlreadyRegistered.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/TypeAlreadyRegistered.h:45:15 (exported to Smp-C/Publication/TypeAlreadyRegistered.h) : Reference type is not supported: TypeAlreadyRegistered & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_TYPEALREADYREGISTERED_H */
