/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_TYPENOTREGISTERED_H
#define CWRAPPER_TYPENOTREGISTERED_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/Uuid.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#ifndef CW_root_Smp_Publication
#define CW_root_Smp_Publication CW_BUILD_SPACE(CW_root_Smp, Publication)
#endif /* CW_root_Smp_Publication */
#define CW_SPACE CW_root_Smp_Publication

typedef void CW(TypeNotRegistered);

#undef CW_SPACE


/* ### Smp::Publication::TypeNotRegistered ### */
#ifndef CW_root_Smp_Publication_TypeNotRegistered
#define CW_root_Smp_Publication_TypeNotRegistered CW_BUILD_SPACE(CW_root_Smp_Publication, TypeNotRegistered)
#endif /* CW_root_Smp_Publication_TypeNotRegistered */
#define CW_SPACE CW_root_Smp_Publication_TypeNotRegistered

void
CW(_TypeNotRegistered)
(
    CW() * self
);

/* Error while processing function "GetUuid" at Smp/Publication/TypeNotRegistered.h:41:31 (exported to Smp-C/Publication/TypeNotRegistered.h) : Skipping function that returns a class/struct */

/* Error while processing function "TypeNotRegistered" at Smp/Publication/TypeNotRegistered.h:32:15 (exported to Smp-C/Publication/TypeNotRegistered.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/TypeNotRegistered.h:32:15 (exported to Smp-C/Publication/TypeNotRegistered.h) : Reference type is not supported: TypeNotRegistered & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_TYPENOTREGISTERED_H */
