/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/CannotRemove.h"
#include <Smp/CannotRemove.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::CannotRemove ### */
#define CW_SPACE CW_root_Smp_CannotRemove

void
CW(_CannotRemove)
(
    CW() * self
) {
    static_cast<Smp::CannotRemove *>(self)->~CannotRemove(
    );
}

CW(CW_root_Smp, String8)
CW(GetReferenceName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::CannotRemove *>(self)->GetReferenceName(
    ));
}

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::CannotRemove *>(self)->GetComponent(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetLowerLimit)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::CannotRemove *>(self)->GetLowerLimit(
    ));
}

/* Error while processing function "CannotRemove" at Smp/./CannotRemove.h:39:11 (exported to Smp-C/CannotRemove.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotRemove.h:39:11 (exported to Smp-C/CannotRemove.h) : Reference type is not supported: CannotRemove & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
