/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/CannotDelete.h"
#include <Smp/CannotDelete.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::CannotDelete ### */
#define CW_SPACE CW_root_Smp_CannotDelete

void
CW(_CannotDelete)
(
    CW() * self
) {
    static_cast<Smp::CannotDelete *>(self)->~CannotDelete(
    );
}

CW(CW_root_Smp, String8)
CW(GetContainerName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::CannotDelete *>(self)->GetContainerName(
    ));
}

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::CannotDelete *>(self)->GetComponent(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetLowerLimit)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::CannotDelete *>(self)->GetLowerLimit(
    ));
}

/* Error while processing function "CannotDelete" at Smp/./CannotDelete.h:39:11 (exported to Smp-C/CannotDelete.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotDelete.h:39:11 (exported to Smp-C/CannotDelete.h) : Reference type is not supported: CannotDelete & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
