/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/CannotRestore.h"
#include <Smp/CannotRestore.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::CannotRestore ### */
#define CW_SPACE CW_root_Smp_CannotRestore

void
CW(_CannotRestore)
(
    CW() * self
) {
    static_cast<Smp::CannotRestore *>(self)->~CannotRestore(
    );
}

/* Error while processing function "CannotRestore" at Smp/./CannotRestore.h:30:11 (exported to Smp-C/CannotRestore.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotRestore.h:30:11 (exported to Smp-C/CannotRestore.h) : Reference type is not supported: CannotRestore & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
