/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/CannotStore.h"
#include <Smp/CannotStore.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::CannotStore ### */
#define CW_SPACE CW_root_Smp_CannotStore

void
CW(_CannotStore)
(
    CW() * self
) {
    static_cast<Smp::CannotStore *>(self)->~CannotStore(
    );
}

/* Error while processing function "CannotStore" at Smp/./CannotStore.h:29:11 (exported to Smp-C/CannotStore.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./CannotStore.h:29:11 (exported to Smp-C/CannotStore.h) : Reference type is not supported: CannotStore & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
