/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/CollectionIterator.h"
#include <Smp/CollectionIterator.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::CollectionIterator ### */
#define CW_SPACE CW_root_Smp_CollectionIterator

/* Error while processing function "CollectionIterator<T>" at Smp/./CollectionIterator.h:49:9 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "CollectionIterator<T>" at Smp/./CollectionIterator.h:58:9 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator=" at Smp/./CollectionIterator.h:63:29 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "CollectionIterator<T>" at Smp/./CollectionIterator.h:67:9 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator=" at Smp/./CollectionIterator.h:72:29 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator*" at Smp/./CollectionIterator.h:76:20 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator[]" at Smp/./CollectionIterator.h:84:20 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator++" at Smp/./CollectionIterator.h:91:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator++" at Smp/./CollectionIterator.h:99:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator--" at Smp/./CollectionIterator.h:108:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator--" at Smp/./CollectionIterator.h:116:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator+=" at Smp/./CollectionIterator.h:126:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator-=" at Smp/./CollectionIterator.h:135:32 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator+" at Smp/./CollectionIterator.h:144:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator-" at Smp/./CollectionIterator.h:152:31 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator!=" at Smp/./CollectionIterator.h:160:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator==" at Smp/./CollectionIterator.h:168:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator<" at Smp/./CollectionIterator.h:177:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator<=" at Smp/./CollectionIterator.h:186:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator>" at Smp/./CollectionIterator.h:195:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "operator>=" at Smp/./CollectionIterator.h:204:19 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "getIndex" at Smp/./CollectionIterator.h:212:16 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

/* Error while processing function "getCollection" at Smp/./CollectionIterator.h:219:36 (exported to Smp-C/CollectionIterator.h) : Skipping templated function */

#undef CW_SPACE


/* ### std ### */
#define CW_SPACE CW_root_std

#undef CW_SPACE


/* ### std::__1 ### */
#define CW_SPACE CW_root_std___1

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
