/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ContainerFull.h"
#include <Smp/ContainerFull.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ContainerFull ### */
#define CW_SPACE CW_root_Smp_ContainerFull

void
CW(_ContainerFull)
(
    CW() * self
) {
    static_cast<Smp::ContainerFull *>(self)->~ContainerFull(
    );
}

CW(CW_root_Smp, String8)
CW(GetContainerName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::ContainerFull *>(self)->GetContainerName(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetContainerSize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::ContainerFull *>(self)->GetContainerSize(
    ));
}

/* Error while processing function "ContainerFull" at Smp/ContainerFull.h:29:11 (exported to Smp-C/ContainerFull.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/ContainerFull.h:29:11 (exported to Smp-C/ContainerFull.h) : Reference type is not supported: ContainerFull & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
