/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/DuplicateUuid.h"
#include <Smp/DuplicateUuid.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::DuplicateUuid ### */
#define CW_SPACE CW_root_Smp_DuplicateUuid

void
CW(_DuplicateUuid)
(
    CW() * self
) {
    static_cast<Smp::DuplicateUuid *>(self)->~DuplicateUuid(
    );
}

CW(CW_root_Smp, String8)
CW(GetOldName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::DuplicateUuid *>(self)->GetOldName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetNewName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::DuplicateUuid *>(self)->GetNewName(
    ));
}

/* Error while processing function "DuplicateUuid" at Smp/./DuplicateUuid.h:30:11 (exported to Smp-C/DuplicateUuid.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./DuplicateUuid.h:30:11 (exported to Smp-C/DuplicateUuid.h) : Reference type is not supported: DuplicateUuid & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
