/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/DuplicateName.h"
#include <Smp/DuplicateName.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::DuplicateName ### */
#define CW_SPACE CW_root_Smp_DuplicateName

void
CW(_DuplicateName)
(
    CW() * self
) {
    static_cast<Smp::DuplicateName *>(self)->~DuplicateName(
    );
}

CW(CW_root_Smp, String8)
CW(GetDuplicateName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::DuplicateName *>(self)->GetDuplicateName(
    ));
}

/* Error while processing function "DuplicateName" at Smp/DuplicateName.h:31:11 (exported to Smp-C/DuplicateName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/DuplicateName.h:31:11 (exported to Smp-C/DuplicateName.h) : Reference type is not supported: DuplicateName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
