/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/DuplicateLiteral.h"
#include <Smp/Publication/DuplicateLiteral.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::DuplicateLiteral ### */
#define CW_SPACE CW_root_Smp_Publication_DuplicateLiteral

void
CW(_DuplicateLiteral)
(
    CW() * self
) {
    static_cast<Smp::Publication::DuplicateLiteral *>(self)->~DuplicateLiteral(
    );
}

CW(CW_root_Smp, String8)
CW(GetLiteralName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Publication::DuplicateLiteral *>(self)->GetLiteralName(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetLiteralValue)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::Publication::DuplicateLiteral *>(self)->GetLiteralValue(
    ));
}

/* Error while processing function "DuplicateLiteral" at Smp/./Publication/DuplicateLiteral.h:33:15 (exported to Smp-C/Publication/DuplicateLiteral.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/DuplicateLiteral.h:33:15 (exported to Smp-C/Publication/DuplicateLiteral.h) : Reference type is not supported: DuplicateLiteral & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
