/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/EntryPointNotSubscribed.h"
#include <Smp/Services/EntryPointNotSubscribed.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::EntryPointNotSubscribed ### */
#define CW_SPACE CW_root_Smp_Services_EntryPointNotSubscribed

void
CW(_EntryPointNotSubscribed)
(
    CW() * self
) {
    static_cast<Smp::Services::EntryPointNotSubscribed *>(self)->~EntryPointNotSubscribed(
    );
}

const CW(CW_root_Smp, IEntryPoint) *
CW(GetEntryPoint)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEntryPoint) *>(
    static_cast<Smp::Services::EntryPointNotSubscribed *>(self)->GetEntryPoint(
    ));
}

CW(CW_root_Smp, String8)
CW(GetEventName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Services::EntryPointNotSubscribed *>(self)->GetEventName(
    ));
}

/* Error while processing function "EntryPointNotSubscribed" at Smp/./Services/EntryPointNotSubscribed.h:41:15 (exported to Smp-C/Services/EntryPointNotSubscribed.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/EntryPointNotSubscribed.h:41:15 (exported to Smp-C/Services/EntryPointNotSubscribed.h) : Reference type is not supported: EntryPointNotSubscribed & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
