/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/EventSinkNotSubscribed.h"
#include <Smp/EventSinkNotSubscribed.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::EventSinkNotSubscribed ### */
#define CW_SPACE CW_root_Smp_EventSinkNotSubscribed

void
CW(_EventSinkNotSubscribed)
(
    CW() * self
) {
    static_cast<Smp::EventSinkNotSubscribed *>(self)->~EventSinkNotSubscribed(
    );
}

const CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEventSource) *>(
    static_cast<Smp::EventSinkNotSubscribed *>(self)->GetEventSource(
    ));
}

const CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEventSink) *>(
    static_cast<Smp::EventSinkNotSubscribed *>(self)->GetEventSink(
    ));
}

/* Error while processing function "EventSinkNotSubscribed" at Smp/./EventSinkNotSubscribed.h:38:11 (exported to Smp-C/EventSinkNotSubscribed.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./EventSinkNotSubscribed.h:38:11 (exported to Smp-C/EventSinkNotSubscribed.h) : Reference type is not supported: EventSinkNotSubscribed & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
