/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/EventSinkAlreadySubscribed.h"
#include <Smp/EventSinkAlreadySubscribed.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::EventSinkAlreadySubscribed ### */
#define CW_SPACE CW_root_Smp_EventSinkAlreadySubscribed

void
CW(_EventSinkAlreadySubscribed)
(
    CW() * self
) {
    static_cast<Smp::EventSinkAlreadySubscribed *>(self)->~EventSinkAlreadySubscribed(
    );
}

const CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEventSink) *>(
    static_cast<Smp::EventSinkAlreadySubscribed *>(self)->GetEventSink(
    ));
}

const CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEventSource) *>(
    static_cast<Smp::EventSinkAlreadySubscribed *>(self)->GetEventSource(
    ));
}

/* Error while processing function "EventSinkAlreadySubscribed" at Smp/./EventSinkAlreadySubscribed.h:38:11 (exported to Smp-C/EventSinkAlreadySubscribed.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./EventSinkAlreadySubscribed.h:38:11 (exported to Smp-C/EventSinkAlreadySubscribed.h) : Reference type is not supported: EventSinkAlreadySubscribed & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
