/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Exception.h"
#include <Smp/Exception.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Exception ### */
#define CW_SPACE CW_root_Smp_Exception

void
CW(_Exception)
(
    CW() * self
) {
    static_cast<Smp::Exception *>(self)->~Exception(
    );
}

const CW(CW_root_Smp, Char8) *
CW(what)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, Char8) *>(
    static_cast<Smp::Exception *>(self)->what(
    ));
}

CW(CW_root_Smp, String8)
CW(GetName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Exception *>(self)->GetName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetDescription)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Exception *>(self)->GetDescription(
    ));
}

CW(CW_root_Smp, String8)
CW(GetMessage)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Exception *>(self)->GetMessage(
    ));
}

const CW(CW_root_Smp, IObject) *
CW(GetSender)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::Exception *>(self)->GetSender(
    ));
}

/* Error while processing function "Exception" at Smp/Exception.h:39:11 (exported to Smp-C/Exception.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Exception.h:39:11 (exported to Smp-C/Exception.h) : Reference type is not supported: Exception & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
