/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/FieldAlreadyConnected.h"
#include <Smp/FieldAlreadyConnected.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::FieldAlreadyConnected ### */
#define CW_SPACE CW_root_Smp_FieldAlreadyConnected

void
CW(_FieldAlreadyConnected)
(
    CW() * self
) {
    static_cast<Smp::FieldAlreadyConnected *>(self)->~FieldAlreadyConnected(
    );
}

const CW(CW_root_Smp, IOutputField) *
CW(GetSource)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IOutputField) *>(
    static_cast<Smp::FieldAlreadyConnected *>(self)->GetSource(
    ));
}

const CW(CW_root_Smp, IField) *
CW(GetTarget)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IField) *>(
    static_cast<Smp::FieldAlreadyConnected *>(self)->GetTarget(
    ));
}

/* Error while processing function "FieldAlreadyConnected" at Smp/./FieldAlreadyConnected.h:38:11 (exported to Smp-C/FieldAlreadyConnected.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./FieldAlreadyConnected.h:38:11 (exported to Smp-C/FieldAlreadyConnected.h) : Reference type is not supported: FieldAlreadyConnected & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
