/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/FieldNotConnected.h"
#include <Smp/FieldNotConnected.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::FieldNotConnected ### */
#define CW_SPACE CW_root_Smp_FieldNotConnected

void
CW(_FieldNotConnected)
(
    CW() * self
) {
    static_cast<Smp::FieldNotConnected *>(self)->~FieldNotConnected(
    );
}

const CW(CW_root_Smp, IOutputField) *
CW(GetSource)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IOutputField) *>(
    static_cast<Smp::FieldNotConnected *>(self)->GetSource(
    ));
}

const CW(CW_root_Smp, IField) *
CW(GetTarget)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IField) *>(
    static_cast<Smp::FieldNotConnected *>(self)->GetTarget(
    ));
}

/* Error while processing function "FieldNotConnected" at Smp/./FieldNotConnected.h:38:11 (exported to Smp-C/FieldNotConnected.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./FieldNotConnected.h:38:11 (exported to Smp-C/FieldNotConnected.h) : Reference type is not supported: FieldNotConnected & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
