/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/FileNotFound.h"
#include <Smp/FileNotFound.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::FileNotFound ### */
#define CW_SPACE CW_root_Smp_FileNotFound

void
CW(_FileNotFound)
(
    CW() * self
) {
    static_cast<Smp::FileNotFound *>(self)->~FileNotFound(
    );
}

CW(CW_root_Smp, String8)
CW(GetFileName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::FileNotFound *>(self)->GetFileName(
    ));
}

/* Error while processing function "FileNotFound" at Smp/./FileNotFound.h:28:11 (exported to Smp-C/FileNotFound.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./FileNotFound.h:28:11 (exported to Smp-C/FileNotFound.h) : Reference type is not supported: FileNotFound & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
