/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IAggregate.h"
#include <Smp/IAggregate.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IAggregate ### */
#define CW_SPACE CW_root_Smp_IAggregate

void
CW(_IAggregate)
(
    CW() * self
) {
    static_cast<Smp::IAggregate *>(self)->~IAggregate(
    );
}

const CW(CW_root_Smp, ReferenceCollection) *
CW(GetReferences)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, ReferenceCollection) *>(
    static_cast<Smp::IAggregate *>(self)->GetReferences(
    ));
}

CW(CW_root_Smp, IReference) *
CW(GetReference)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IReference) *>(
    static_cast<Smp::IAggregate *>(self)->GetReference(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IAggregate" at Smp/./IAggregate.h:43:11 (exported to Smp-C/IAggregate.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IAggregate.h:43:11 (exported to Smp-C/IAggregate.h) : Reference type is not supported: IAggregate & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
