/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IArrayField.h"
#include <Smp/IArrayField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IArrayField ### */
#define CW_SPACE CW_root_Smp_IArrayField

void
CW(_IArrayField)
(
    CW() * self
) {
    static_cast<Smp::IArrayField *>(self)->~IArrayField(
    );
}

CW(CW_root_Smp, UInt64)
CW(GetSize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, UInt64)>(
    static_cast<Smp::IArrayField *>(self)->GetSize(
    ));
}

CW(CW_root_Smp, IField) *
CW(GetItem)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) index
) {
    return static_cast<CW(CW_root_Smp, IField) *>(
    static_cast<Smp::IArrayField *>(self)->GetItem(
        static_cast<Smp::UInt64>(index)
    ));
}

/* Error while processing function "IArrayField" at Smp/./IArrayField.h:28:11 (exported to Smp-C/IArrayField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IArrayField.h:28:11 (exported to Smp-C/IArrayField.h) : Reference type is not supported: IArrayField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
