/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IArrayType.h"
#include <Smp/Publication/IArrayType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IArrayType ### */
#define CW_SPACE CW_root_Smp_Publication_IArrayType

void
CW(_IArrayType)
(
    CW() * self
) {
    static_cast<Smp::Publication::IArrayType *>(self)->~IArrayType(
    );
}

CW(CW_root_Smp, UInt64)
CW(GetSize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, UInt64)>(
    static_cast<Smp::Publication::IArrayType *>(self)->GetSize(
    ));
}

const CW(CW_root_Smp_Publication, IType) *
CW(GetItemType)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp_Publication, IType) *>(
    static_cast<Smp::Publication::IArrayType *>(self)->GetItemType(
    ));
}

/* Error while processing function "IArrayType" at Smp/./Publication/IArrayType.h:32:15 (exported to Smp-C/Publication/IArrayType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IArrayType.h:32:15 (exported to Smp-C/Publication/IArrayType.h) : Reference type is not supported: IArrayType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
