/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IClassType.h"
#include <Smp/Publication/IClassType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IClassType ### */
#define CW_SPACE CW_root_Smp_Publication_IClassType

void
CW(_IClassType)
(
    CW() * self
) {
    static_cast<Smp::Publication::IClassType *>(self)->~IClassType(
    );
}

/* Error while processing function "IClassType" at Smp/./Publication/IClassType.h:30:15 (exported to Smp-C/Publication/IClassType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IClassType.h:30:15 (exported to Smp-C/Publication/IClassType.h) : Reference type is not supported: IClassType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
