/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ICollectionBase.h"
#include <Smp/ICollectionBase.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ICollectionBase ### */
#define CW_SPACE CW_root_Smp_ICollectionBase

void
CW(_ICollectionBase)
(
    CW() * self
) {
    static_cast<Smp::ICollectionBase *>(self)->~ICollectionBase(
    );
}

/* Error while processing function "operator=" at Smp/ICollectionBase.h:27:11 (exported to Smp-C/ICollectionBase.h) : Reference type is not supported: ICollectionBase & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
