/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ICollection.h"
#include <Smp/ICollection.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ICollection ### */
#define CW_SPACE CW_root_Smp_ICollection

/* Error while processing function "~ICollection<T>" at Smp/ICollection.h:44:17 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "at" at Smp/ICollection.h:49:20 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "at" at Smp/ICollection.h:56:20 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "size" at Smp/ICollection.h:61:24 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "empty" at Smp/ICollection.h:65:27 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "begin" at Smp/ICollection.h:69:32 (exported to Smp-C/ICollection.h) : Skipping templated function */

/* Error while processing function "end" at Smp/ICollection.h:73:32 (exported to Smp-C/ICollection.h) : Skipping templated function */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
