/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IComposite.h"
#include <Smp/IComposite.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IComposite ### */
#define CW_SPACE CW_root_Smp_IComposite

void
CW(_IComposite)
(
    CW() * self
) {
    static_cast<Smp::IComposite *>(self)->~IComposite(
    );
}

const CW(CW_root_Smp, ContainerCollection) *
CW(GetContainers)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, ContainerCollection) *>(
    static_cast<Smp::IComposite *>(self)->GetContainers(
    ));
}

CW(CW_root_Smp, IContainer) *
CW(GetContainer)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IContainer) *>(
    static_cast<Smp::IComposite *>(self)->GetContainer(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IComposite" at Smp/./IComposite.h:43:11 (exported to Smp-C/IComposite.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IComposite.h:43:11 (exported to Smp-C/IComposite.h) : Reference type is not supported: IComposite & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
