/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IContainer.h"
#include <Smp/IContainer.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IContainer ### */
#define CW_SPACE CW_root_Smp_IContainer

void
CW(_IContainer)
(
    CW() * self
) {
    static_cast<Smp::IContainer *>(self)->~IContainer(
    );
}

const CW(CW_root_Smp, ComponentCollection) *
CW(GetComponents)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, ComponentCollection) *>(
    static_cast<Smp::IContainer *>(self)->GetComponents(
    ));
}

CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::IContainer *>(self)->GetComponent(
        static_cast<Smp::String8>(name)
    ));
}

void
CW(AddComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
) {
    static_cast<Smp::IContainer *>(self)->AddComponent(
        static_cast<Smp::IComponent *>(component)
    );
}

void
CW(DeleteComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
) {
    static_cast<Smp::IContainer *>(self)->DeleteComponent(
        static_cast<Smp::IComponent *>(component)
    );
}

CW(CW_root_Smp, Int64)
CW(GetCount)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::IContainer *>(self)->GetCount(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetUpper)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::IContainer *>(self)->GetUpper(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetLower)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::IContainer *>(self)->GetLower(
    ));
}

/* Error while processing function "IContainer" at Smp/IContainer.h:47:11 (exported to Smp-C/IContainer.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IContainer.h:47:11 (exported to Smp-C/IContainer.h) : Reference type is not supported: IContainer & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
