/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IDynamicInvocation.h"
#include <Smp/IDynamicInvocation.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IDynamicInvocation ### */
#define CW_SPACE CW_root_Smp_IDynamicInvocation

void
CW(_IDynamicInvocation)
(
    CW() * self
) {
    static_cast<Smp::IDynamicInvocation *>(self)->~IDynamicInvocation(
    );
}

void
CW(Invoke)
(
    CW() * self,
    CW(CW_root_Smp, IRequest) * request
) {
    static_cast<Smp::IDynamicInvocation *>(self)->Invoke(
        static_cast<Smp::IRequest *>(request)
    );
}

CW(CW_root_Smp, IProperty) *
CW(GetProperty)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IProperty) *>(
    static_cast<Smp::IDynamicInvocation *>(self)->GetProperty(
        static_cast<Smp::String8>(name)
    ));
}

const CW(CW_root_Smp, PropertyCollection) *
CW(GetProperties)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, PropertyCollection) *>(
    static_cast<Smp::IDynamicInvocation *>(self)->GetProperties(
    ));
}

CW(CW_root_Smp, IOperation) *
CW(GetOperation)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IOperation) *>(
    static_cast<Smp::IDynamicInvocation *>(self)->GetOperation(
        static_cast<Smp::String8>(name)
    ));
}

const CW(CW_root_Smp, OperationCollection) *
CW(GetOperations)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, OperationCollection) *>(
    static_cast<Smp::IDynamicInvocation *>(self)->GetOperations(
    ));
}

/* Error while processing function "IDynamicInvocation" at Smp/./IDynamicInvocation.h:48:11 (exported to Smp-C/IDynamicInvocation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IDynamicInvocation.h:48:11 (exported to Smp-C/IDynamicInvocation.h) : Reference type is not supported: IDynamicInvocation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
