/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IEntryPoint.h"
#include <Smp/IEntryPoint.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IEntryPoint ### */
#define CW_SPACE CW_root_Smp_IEntryPoint

void
CW(_IEntryPoint)
(
    CW() * self
) {
    static_cast<Smp::IEntryPoint *>(self)->~IEntryPoint(
    );
}

void
CW(Execute)
(
    CW() * self
) {
    static_cast<Smp::IEntryPoint *>(self)->Execute(
    );
}

/* Error while processing function "IEntryPoint" at Smp/IEntryPoint.h:30:11 (exported to Smp-C/IEntryPoint.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IEntryPoint.h:30:11 (exported to Smp-C/IEntryPoint.h) : Reference type is not supported: IEntryPoint & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
