/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IEntryPointPublisher.h"
#include <Smp/IEntryPointPublisher.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IEntryPointPublisher ### */
#define CW_SPACE CW_root_Smp_IEntryPointPublisher

void
CW(_IEntryPointPublisher)
(
    CW() * self
) {
    static_cast<Smp::IEntryPointPublisher *>(self)->~IEntryPointPublisher(
    );
}

const CW(CW_root_Smp, EntryPointCollection) *
CW(GetEntryPoints)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, EntryPointCollection) *>(
    static_cast<Smp::IEntryPointPublisher *>(self)->GetEntryPoints(
    ));
}

CW(CW_root_Smp, IEntryPoint) *
CW(GetEntryPoint)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IEntryPoint) *>(
    static_cast<Smp::IEntryPointPublisher *>(self)->GetEntryPoint(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IEntryPointPublisher" at Smp/./IEntryPointPublisher.h:43:11 (exported to Smp-C/IEntryPointPublisher.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IEntryPointPublisher.h:43:11 (exported to Smp-C/IEntryPointPublisher.h) : Reference type is not supported: IEntryPointPublisher & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
