/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IEnumerationType.h"
#include <Smp/Publication/IEnumerationType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IEnumerationType ### */
#define CW_SPACE CW_root_Smp_Publication_IEnumerationType

void
CW(_IEnumerationType)
(
    CW() * self
) {
    static_cast<Smp::Publication::IEnumerationType *>(self)->~IEnumerationType(
    );
}

void
CW(AddLiteral)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Int32) value
) {
    static_cast<Smp::Publication::IEnumerationType *>(self)->AddLiteral(
        static_cast<Smp::String8>(name),
        static_cast<Smp::String8>(description),
        static_cast<Smp::Int32>(value)
    );
}

/* Error while processing function "IEnumerationType" at Smp/./Publication/IEnumerationType.h:34:15 (exported to Smp-C/Publication/IEnumerationType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IEnumerationType.h:34:15 (exported to Smp-C/Publication/IEnumerationType.h) : Reference type is not supported: IEnumerationType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
