/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IEventConsumer.h"
#include <Smp/IEventConsumer.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IEventConsumer ### */
#define CW_SPACE CW_root_Smp_IEventConsumer

void
CW(_IEventConsumer)
(
    CW() * self
) {
    static_cast<Smp::IEventConsumer *>(self)->~IEventConsumer(
    );
}

const CW(CW_root_Smp, EventSinkCollection) *
CW(GetEventSinks)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, EventSinkCollection) *>(
    static_cast<Smp::IEventConsumer *>(self)->GetEventSinks(
    ));
}

CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IEventSink) *>(
    static_cast<Smp::IEventConsumer *>(self)->GetEventSink(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IEventConsumer" at Smp/./IEventConsumer.h:42:11 (exported to Smp-C/IEventConsumer.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IEventConsumer.h:42:11 (exported to Smp-C/IEventConsumer.h) : Reference type is not supported: IEventConsumer & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
