/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IEventSink.h"
#include <Smp/IEventSink.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IEventSink ### */
#define CW_SPACE CW_root_Smp_IEventSink

void
CW(_IEventSink)
(
    CW() * self
) {
    static_cast<Smp::IEventSink *>(self)->~IEventSink(
    );
}

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetEventArgType)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, PrimitiveTypeKind)>(
    static_cast<Smp::IEventSink *>(self)->GetEventArgType(
    ));
}

void
CW(Notify)
(
    CW() * self,
    CW(CW_root_Smp, IObject) * sender,
    CW(CW_root_Smp, AnySimple) * arg
) {
    static_cast<Smp::IEventSink *>(self)->Notify(
        static_cast<Smp::IObject *>(sender),
        *static_cast<Smp::AnySimple*>(arg)
    );
}

/* Error while processing function "IEventSink" at Smp/IEventSink.h:32:11 (exported to Smp-C/IEventSink.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IEventSink.h:32:11 (exported to Smp-C/IEventSink.h) : Reference type is not supported: IEventSink & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
