/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IEventProvider.h"
#include <Smp/IEventProvider.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IEventProvider ### */
#define CW_SPACE CW_root_Smp_IEventProvider

void
CW(_IEventProvider)
(
    CW() * self
) {
    static_cast<Smp::IEventProvider *>(self)->~IEventProvider(
    );
}

const CW(CW_root_Smp, EventSourceCollection) *
CW(GetEventSources)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, EventSourceCollection) *>(
    static_cast<Smp::IEventProvider *>(self)->GetEventSources(
    ));
}

CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IEventSource) *>(
    static_cast<Smp::IEventProvider *>(self)->GetEventSource(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IEventProvider" at Smp/./IEventProvider.h:42:11 (exported to Smp-C/IEventProvider.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IEventProvider.h:42:11 (exported to Smp-C/IEventProvider.h) : Reference type is not supported: IEventProvider & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
