/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/IEventManager.h"
#include <Smp/Services/IEventManager.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::IEventManager ### */
#define CW_SPACE CW_root_Smp_Services_IEventManager

void
CW(_IEventManager)
(
    CW() * self
) {
    static_cast<Smp::Services::IEventManager *>(self)->~IEventManager(
    );
}

CW(CW_root_Smp_Services, EventId)
CW(QueryEventId)
(
    CW() * self,
    CW(CW_root_Smp, String8) eventName
) {
    return static_cast<CW(CW_root_Smp_Services, EventId)>(
    static_cast<Smp::Services::IEventManager *>(self)->QueryEventId(
        static_cast<Smp::String8>(eventName)
    ));
}

void
CW(Subscribe)
(
    CW() * self,
    CW(CW_root_Smp_Services, EventId) event,
    const CW(CW_root_Smp, IEntryPoint) * entryPoint
) {
    static_cast<Smp::Services::IEventManager *>(self)->Subscribe(
        static_cast<Smp::Services::EventId>(event),
        static_cast<const Smp::IEntryPoint *>(entryPoint)
    );
}

void
CW(Unsubscribe)
(
    CW() * self,
    CW(CW_root_Smp_Services, EventId) event,
    const CW(CW_root_Smp, IEntryPoint) * entryPoint
) {
    static_cast<Smp::Services::IEventManager *>(self)->Unsubscribe(
        static_cast<Smp::Services::EventId>(event),
        static_cast<const Smp::IEntryPoint *>(entryPoint)
    );
}

void
CW(Emit)
(
    CW() * self,
    CW(CW_root_Smp_Services, EventId) event,
    CW(CW_root_Smp, Bool) synchronous
) {
    static_cast<Smp::Services::IEventManager *>(self)->Emit(
        static_cast<Smp::Services::EventId>(event),
        static_cast<Smp::Bool>(synchronous)
    );
}

/* Error while processing function "IEventManager" at Smp/./Services/IEventManager.h:47:15 (exported to Smp-C/Services/IEventManager.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/IEventManager.h:47:15 (exported to Smp-C/Services/IEventManager.h) : Reference type is not supported: IEventManager & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
