/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IFactory.h"
#include <Smp/IFactory.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IFactory ### */
#define CW_SPACE CW_root_Smp_IFactory

void
CW(_IFactory)
(
    CW() * self
) {
    static_cast<Smp::IFactory *>(self)->~IFactory(
    );
}

/* Error while processing function "GetUuid" at Smp/IFactory.h:50:27 (exported to Smp-C/IFactory.h) : Skipping function that returns a class/struct */

CW(CW_root_Smp, String8)
CW(GetTypeName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IFactory *>(self)->GetTypeName(
    ));
}

CW(CW_root_Smp, IComponent) *
CW(CreateInstance)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, IComposite) * parent
) {
    return static_cast<CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::IFactory *>(self)->CreateInstance(
        static_cast<Smp::String8>(name),
        static_cast<Smp::String8>(description),
        static_cast<Smp::IComposite *>(parent)
    ));
}

void
CW(DeleteInstance)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * instance
) {
    static_cast<Smp::IFactory *>(self)->DeleteInstance(
        static_cast<Smp::IComponent *>(instance)
    );
}

/* Error while processing function "IFactory" at Smp/IFactory.h:40:11 (exported to Smp-C/IFactory.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IFactory.h:40:11 (exported to Smp-C/IFactory.h) : Reference type is not supported: IFactory & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
