/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IFailure.h"
#include <Smp/IFailure.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IFailure ### */
#define CW_SPACE CW_root_Smp_IFailure

void
CW(_IFailure)
(
    CW() * self
) {
    static_cast<Smp::IFailure *>(self)->~IFailure(
    );
}

void
CW(Fail)
(
    CW() * self
) {
    static_cast<Smp::IFailure *>(self)->Fail(
    );
}

void
CW(Unfail)
(
    CW() * self
) {
    static_cast<Smp::IFailure *>(self)->Unfail(
    );
}

CW(CW_root_Smp, Bool)
CW(IsFailed)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IFailure *>(self)->IsFailed(
    ));
}

/* Error while processing function "IFailure" at Smp/IFailure.h:33:11 (exported to Smp-C/IFailure.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IFailure.h:33:11 (exported to Smp-C/IFailure.h) : Reference type is not supported: IFailure & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
