/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IFallibleModel.h"
#include <Smp/IFallibleModel.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IFallibleModel ### */
#define CW_SPACE CW_root_Smp_IFallibleModel

void
CW(_IFallibleModel)
(
    CW() * self
) {
    static_cast<Smp::IFallibleModel *>(self)->~IFallibleModel(
    );
}

CW(CW_root_Smp, Bool)
CW(IsFailed)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IFallibleModel *>(self)->IsFailed(
    ));
}

const CW(CW_root_Smp, FailureCollection) *
CW(GetFailures)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, FailureCollection) *>(
    static_cast<Smp::IFallibleModel *>(self)->GetFailures(
    ));
}

CW(CW_root_Smp, IFailure) *
CW(GetFailure)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IFailure) *>(
    static_cast<Smp::IFallibleModel *>(self)->GetFailure(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IFallibleModel" at Smp/./IFallibleModel.h:43:11 (exported to Smp-C/IFallibleModel.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IFallibleModel.h:43:11 (exported to Smp-C/IFallibleModel.h) : Reference type is not supported: IFallibleModel & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
