/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IField.h"
#include <Smp/IField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IField ### */
#define CW_SPACE CW_root_Smp_IField

void
CW(_IField)
(
    CW() * self
) {
    static_cast<Smp::IField *>(self)->~IField(
    );
}

CW(CW_root_Smp, ViewKind)
CW(GetView)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, ViewKind)>(
    static_cast<Smp::IField *>(self)->GetView(
    ));
}

CW(CW_root_Smp, Bool)
CW(IsState)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IField *>(self)->IsState(
    ));
}

CW(CW_root_Smp, Bool)
CW(IsInput)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IField *>(self)->IsInput(
    ));
}

CW(CW_root_Smp, Bool)
CW(IsOutput)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IField *>(self)->IsOutput(
    ));
}

const CW(CW_root_Smp_Publication, IType) *
CW(GetType)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp_Publication, IType) *>(
    static_cast<Smp::IField *>(self)->GetType(
    ));
}

/* Error while processing function "IField" at Smp/IField.h:42:11 (exported to Smp-C/IField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IField.h:42:11 (exported to Smp-C/IField.h) : Reference type is not supported: IField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
