/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IForcibleField.h"
#include <Smp/IForcibleField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IForcibleField ### */
#define CW_SPACE CW_root_Smp_IForcibleField

void
CW(_IForcibleField)
(
    CW() * self
) {
    static_cast<Smp::IForcibleField *>(self)->~IForcibleField(
    );
}

void
CW(Force)
(
    CW() * self,
    CW(CW_root_Smp, AnySimple) * value
) {
    static_cast<Smp::IForcibleField *>(self)->Force(
        *static_cast<Smp::AnySimple*>(value)
    );
}

void
CW(Unforce)
(
    CW() * self
) {
    static_cast<Smp::IForcibleField *>(self)->Unforce(
    );
}

CW(CW_root_Smp, Bool)
CW(IsForced)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IForcibleField *>(self)->IsForced(
    ));
}

void
CW(Freeze)
(
    CW() * self
) {
    static_cast<Smp::IForcibleField *>(self)->Freeze(
    );
}

/* Error while processing function "IForcibleField" at Smp/./IForcibleField.h:30:11 (exported to Smp-C/IForcibleField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IForcibleField.h:30:11 (exported to Smp-C/IForcibleField.h) : Reference type is not supported: IForcibleField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
