/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ILinkingComponent.h"
#include <Smp/ILinkingComponent.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ILinkingComponent ### */
#define CW_SPACE CW_root_Smp_ILinkingComponent

void
CW(_ILinkingComponent)
(
    CW() * self
) {
    static_cast<Smp::ILinkingComponent *>(self)->~ILinkingComponent(
    );
}

void
CW(RemoveLinks)
(
    CW() * self,
    const CW(CW_root_Smp, IComponent) * target
) {
    static_cast<Smp::ILinkingComponent *>(self)->RemoveLinks(
        static_cast<const Smp::IComponent *>(target)
    );
}

/* Error while processing function "ILinkingComponent" at Smp/./ILinkingComponent.h:37:11 (exported to Smp-C/ILinkingComponent.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./ILinkingComponent.h:37:11 (exported to Smp-C/ILinkingComponent.h) : Reference type is not supported: ILinkingComponent & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
