/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/ILogger.h"
#include <Smp/Services/ILogger.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::ILogger ### */
#define CW_SPACE CW_root_Smp_Services_ILogger

void
CW(_ILogger)
(
    CW() * self
) {
    static_cast<Smp::Services::ILogger *>(self)->~ILogger(
    );
}

CW(CW_root_Smp_Services, LogMessageKind)
CW(QueryLogMessageKind)
(
    CW() * self,
    CW(CW_root_Smp, String8) messageKindName
) {
    return static_cast<CW(CW_root_Smp_Services, LogMessageKind)>(
    static_cast<Smp::Services::ILogger *>(self)->QueryLogMessageKind(
        static_cast<Smp::String8>(messageKindName)
    ));
}

void
CW(Log)
(
    CW() * self,
    const CW(CW_root_Smp, IObject) * sender,
    CW(CW_root_Smp, String8) message,
    CW(CW_root_Smp_Services, LogMessageKind) kind
) {
    static_cast<Smp::Services::ILogger *>(self)->Log(
        static_cast<const Smp::IObject *>(sender),
        static_cast<Smp::String8>(message),
        static_cast<Smp::Services::LogMessageKind>(kind)
    );
}

/* Error while processing function "ILogger" at Smp/./Services/ILogger.h:44:15 (exported to Smp-C/Services/ILogger.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/ILogger.h:44:15 (exported to Smp-C/Services/ILogger.h) : Reference type is not supported: ILogger & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
