/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IModel.h"
#include <Smp/IModel.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IModel ### */
#define CW_SPACE CW_root_Smp_IModel

void
CW(_IModel)
(
    CW() * self
) {
    static_cast<Smp::IModel *>(self)->~IModel(
    );
}

/* Error while processing function "IModel" at Smp/IModel.h:28:11 (exported to Smp-C/IModel.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IModel.h:28:11 (exported to Smp-C/IModel.h) : Reference type is not supported: IModel & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
