/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidComponentState.h"
#include <Smp/InvalidComponentState.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidComponentState ### */
#define CW_SPACE CW_root_Smp_InvalidComponentState

void
CW(_InvalidComponentState)
(
    CW() * self
) {
    static_cast<Smp::InvalidComponentState *>(self)->~InvalidComponentState(
    );
}

CW(CW_root_Smp, ComponentStateKind)
CW(GetInvalidState)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, ComponentStateKind)>(
    static_cast<Smp::InvalidComponentState *>(self)->GetInvalidState(
    ));
}

CW(CW_root_Smp, ComponentStateKind)
CW(GetExpectedState)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, ComponentStateKind)>(
    static_cast<Smp::InvalidComponentState *>(self)->GetExpectedState(
    ));
}

/* Error while processing function "InvalidComponentState" at Smp/InvalidComponentState.h:29:11 (exported to Smp-C/InvalidComponentState.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidComponentState.h:29:11 (exported to Smp-C/InvalidComponentState.h) : Reference type is not supported: InvalidComponentState & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
