/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidFile.h"
#include <Smp/InvalidFile.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidFile ### */
#define CW_SPACE CW_root_Smp_InvalidFile

void
CW(_InvalidFile)
(
    CW() * self
) {
    static_cast<Smp::InvalidFile *>(self)->~InvalidFile(
    );
}

CW(CW_root_Smp, String8)
CW(GetFileName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidFile *>(self)->GetFileName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetErrorMessage)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidFile *>(self)->GetErrorMessage(
    ));
}

/* Error while processing function "InvalidFile" at Smp/InvalidFile.h:29:11 (exported to Smp-C/InvalidFile.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidFile.h:29:11 (exported to Smp-C/InvalidFile.h) : Reference type is not supported: InvalidFile & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
