/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidAccess.h"
#include <Smp/InvalidAccess.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidAccess ### */
#define CW_SPACE CW_root_Smp_InvalidAccess

void
CW(_InvalidAccess)
(
    CW() * self
) {
    static_cast<Smp::InvalidAccess *>(self)->~InvalidAccess(
    );
}

CW(CW_root_Smp, String8)
CW(GetPropertyName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidAccess *>(self)->GetPropertyName(
    ));
}

/* Error while processing function "InvalidAccess" at Smp/InvalidAccess.h:29:11 (exported to Smp-C/InvalidAccess.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidAccess.h:29:11 (exported to Smp-C/InvalidAccess.h) : Reference type is not supported: InvalidAccess & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
