/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidFieldName.h"
#include <Smp/InvalidFieldName.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidFieldName ### */
#define CW_SPACE CW_root_Smp_InvalidFieldName

void
CW(_InvalidFieldName)
(
    CW() * self
) {
    static_cast<Smp::InvalidFieldName *>(self)->~InvalidFieldName(
    );
}

CW(CW_root_Smp, String8)
CW(GetFieldName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidFieldName *>(self)->GetFieldName(
    ));
}

/* Error while processing function "InvalidFieldName" at Smp/InvalidFieldName.h:28:11 (exported to Smp-C/InvalidFieldName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidFieldName.h:28:11 (exported to Smp-C/InvalidFieldName.h) : Reference type is not supported: InvalidFieldName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
