/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidSimulatorState.h"
#include <Smp/InvalidSimulatorState.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidSimulatorState ### */
#define CW_SPACE CW_root_Smp_InvalidSimulatorState

void
CW(_InvalidSimulatorState)
(
    CW() * self
) {
    static_cast<Smp::InvalidSimulatorState *>(self)->~InvalidSimulatorState(
    );
}

CW(CW_root_Smp, SimulatorStateKind)
CW(GetInvalidState)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, SimulatorStateKind)>(
    static_cast<Smp::InvalidSimulatorState *>(self)->GetInvalidState(
    ));
}

/* Error while processing function "InvalidSimulatorState" at Smp/InvalidSimulatorState.h:29:11 (exported to Smp-C/InvalidSimulatorState.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidSimulatorState.h:29:11 (exported to Smp-C/InvalidSimulatorState.h) : Reference type is not supported: InvalidSimulatorState & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
