/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidSmpVersion.h"
#include <Smp/InvalidSmpVersion.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidSmpVersion ### */
#define CW_SPACE CW_root_Smp_InvalidSmpVersion

void
CW(_InvalidSmpVersion)
(
    CW() * self
) {
    static_cast<Smp::InvalidSmpVersion *>(self)->~InvalidSmpVersion(
    );
}

CW(CW_root_Smp, UInt64)
CW(GetLibrarySmpVersion)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, UInt64)>(
    static_cast<Smp::InvalidSmpVersion *>(self)->GetLibrarySmpVersion(
    ));
}

/* Error while processing function "InvalidSmpVersion" at Smp/InvalidSmpVersion.h:29:11 (exported to Smp-C/InvalidSmpVersion.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidSmpVersion.h:29:11 (exported to Smp-C/InvalidSmpVersion.h) : Reference type is not supported: InvalidSmpVersion & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
