/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidFieldValue.h"
#include <Smp/InvalidFieldValue.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidFieldValue ### */
#define CW_SPACE CW_root_Smp_InvalidFieldValue

void
CW(_InvalidFieldValue)
(
    CW() * self
) {
    static_cast<Smp::InvalidFieldValue *>(self)->~InvalidFieldValue(
    );
}

const CW(CW_root_Smp, IField) *
CW(GetField)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IField) *>(
    static_cast<Smp::InvalidFieldValue *>(self)->GetField(
    ));
}

/* Error while processing function "InvalidFieldValue" at Smp/InvalidFieldValue.h:37:11 (exported to Smp-C/InvalidFieldValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidFieldValue.h:37:11 (exported to Smp-C/InvalidFieldValue.h) : Reference type is not supported: InvalidFieldValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
