/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/InvalidCycleTime.h"
#include <Smp/Services/InvalidCycleTime.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::InvalidCycleTime ### */
#define CW_SPACE CW_root_Smp_Services_InvalidCycleTime

void
CW(_InvalidCycleTime)
(
    CW() * self
) {
    static_cast<Smp::Services::InvalidCycleTime *>(self)->~InvalidCycleTime(
    );
}

/* Error while processing function "InvalidCycleTime" at Smp/Services/InvalidCycleTime.h:32:15 (exported to Smp-C/Services/InvalidCycleTime.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidCycleTime.h:32:15 (exported to Smp-C/Services/InvalidCycleTime.h) : Reference type is not supported: InvalidCycleTime & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
