/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/InvalidSimulationTime.h"
#include <Smp/Services/InvalidSimulationTime.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::InvalidSimulationTime ### */
#define CW_SPACE CW_root_Smp_Services_InvalidSimulationTime

void
CW(_InvalidSimulationTime)
(
    CW() * self
) {
    static_cast<Smp::Services::InvalidSimulationTime *>(self)->~InvalidSimulationTime(
    );
}

CW(CW_root_Smp, Duration)
CW(GetCurrentTime)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Duration)>(
    static_cast<Smp::Services::InvalidSimulationTime *>(self)->GetCurrentTime(
    ));
}

CW(CW_root_Smp, Duration)
CW(GetProvidedTime)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Duration)>(
    static_cast<Smp::Services::InvalidSimulationTime *>(self)->GetProvidedTime(
    ));
}

CW(CW_root_Smp, Duration)
CW(GetMaximumTime)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Duration)>(
    static_cast<Smp::Services::InvalidSimulationTime *>(self)->GetMaximumTime(
    ));
}

/* Error while processing function "InvalidSimulationTime" at Smp/Services/InvalidSimulationTime.h:33:15 (exported to Smp-C/Services/InvalidSimulationTime.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidSimulationTime.h:33:15 (exported to Smp-C/Services/InvalidSimulationTime.h) : Reference type is not supported: InvalidSimulationTime & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
