/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidEventSink.h"
#include <Smp/InvalidEventSink.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidEventSink ### */
#define CW_SPACE CW_root_Smp_InvalidEventSink

void
CW(_InvalidEventSink)
(
    CW() * self
) {
    static_cast<Smp::InvalidEventSink *>(self)->~InvalidEventSink(
    );
}

const CW(CW_root_Smp, IEventSource) *
CW(GetEventSource)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEventSource) *>(
    static_cast<Smp::InvalidEventSink *>(self)->GetEventSource(
    ));
}

const CW(CW_root_Smp, IEventSink) *
CW(GetEventSink)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IEventSink) *>(
    static_cast<Smp::InvalidEventSink *>(self)->GetEventSink(
    ));
}

/* Error while processing function "InvalidEventSink" at Smp/InvalidEventSink.h:38:11 (exported to Smp-C/InvalidEventSink.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidEventSink.h:38:11 (exported to Smp-C/InvalidEventSink.h) : Reference type is not supported: InvalidEventSink & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
