/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidParameterCount.h"
#include <Smp/InvalidParameterCount.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidParameterCount ### */
#define CW_SPACE CW_root_Smp_InvalidParameterCount

void
CW(_InvalidParameterCount)
(
    CW() * self
) {
    static_cast<Smp::InvalidParameterCount *>(self)->~InvalidParameterCount(
    );
}

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidParameterCount *>(self)->GetOperationName(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetOperationParameters)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::InvalidParameterCount *>(self)->GetOperationParameters(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetRequestParameters)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::InvalidParameterCount *>(self)->GetRequestParameters(
    ));
}

/* Error while processing function "InvalidParameterCount" at Smp/InvalidParameterCount.h:29:11 (exported to Smp-C/InvalidParameterCount.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParameterCount.h:29:11 (exported to Smp-C/InvalidParameterCount.h) : Reference type is not supported: InvalidParameterCount & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
