/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/InvalidEventId.h"
#include <Smp/Services/InvalidEventId.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::InvalidEventId ### */
#define CW_SPACE CW_root_Smp_Services_InvalidEventId

void
CW(_InvalidEventId)
(
    CW() * self
) {
    static_cast<Smp::Services::InvalidEventId *>(self)->~InvalidEventId(
    );
}

CW(CW_root_Smp_Services, EventId)
CW(GetInvalidEventId)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp_Services, EventId)>(
    static_cast<Smp::Services::InvalidEventId *>(self)->GetInvalidEventId(
    ));
}

/* Error while processing function "InvalidEventId" at Smp/Services/InvalidEventId.h:37:15 (exported to Smp-C/Services/InvalidEventId.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidEventId.h:37:15 (exported to Smp-C/Services/InvalidEventId.h) : Reference type is not supported: InvalidEventId & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
