/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidArrayIndex.h"
#include <Smp/InvalidArrayIndex.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidArrayIndex ### */
#define CW_SPACE CW_root_Smp_InvalidArrayIndex

void
CW(_InvalidArrayIndex)
(
    CW() * self
) {
    static_cast<Smp::InvalidArrayIndex *>(self)->~InvalidArrayIndex(
    );
}

CW(CW_root_Smp, Int64)
CW(GetInvalidIndex)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::InvalidArrayIndex *>(self)->GetInvalidIndex(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetArraySize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::InvalidArrayIndex *>(self)->GetArraySize(
    ));
}

/* Error while processing function "InvalidArrayIndex" at Smp/InvalidArrayIndex.h:28:11 (exported to Smp-C/InvalidArrayIndex.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidArrayIndex.h:28:11 (exported to Smp-C/InvalidArrayIndex.h) : Reference type is not supported: InvalidArrayIndex & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
