/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/InvalidEventTime.h"
#include <Smp/Services/InvalidEventTime.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::InvalidEventTime ### */
#define CW_SPACE CW_root_Smp_Services_InvalidEventTime

void
CW(_InvalidEventTime)
(
    CW() * self
) {
    static_cast<Smp::Services::InvalidEventTime *>(self)->~InvalidEventTime(
    );
}

/* Error while processing function "InvalidEventTime" at Smp/Services/InvalidEventTime.h:32:15 (exported to Smp-C/Services/InvalidEventTime.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidEventTime.h:32:15 (exported to Smp-C/Services/InvalidEventTime.h) : Reference type is not supported: InvalidEventTime & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
