/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidPropertyValue.h"
#include <Smp/InvalidPropertyValue.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidPropertyValue ### */
#define CW_SPACE CW_root_Smp_InvalidPropertyValue

void
CW(_InvalidPropertyValue)
(
    CW() * self
) {
    static_cast<Smp::InvalidPropertyValue *>(self)->~InvalidPropertyValue(
    );
}

const CW(CW_root_Smp, IProperty) *
CW(GetProperty)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IProperty) *>(
    static_cast<Smp::InvalidPropertyValue *>(self)->GetProperty(
    ));
}

/* Error while processing function "InvalidPropertyValue" at Smp/InvalidPropertyValue.h:37:11 (exported to Smp-C/InvalidPropertyValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidPropertyValue.h:37:11 (exported to Smp-C/InvalidPropertyValue.h) : Reference type is not supported: InvalidPropertyValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
