/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidObjectName.h"
#include <Smp/InvalidObjectName.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidObjectName ### */
#define CW_SPACE CW_root_Smp_InvalidObjectName

void
CW(_InvalidObjectName)
(
    CW() * self
) {
    static_cast<Smp::InvalidObjectName *>(self)->~InvalidObjectName(
    );
}

CW(CW_root_Smp, String8)
CW(GetInvalidName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidObjectName *>(self)->GetInvalidName(
    ));
}

/* Error while processing function "InvalidObjectName" at Smp/InvalidObjectName.h:35:11 (exported to Smp-C/InvalidObjectName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidObjectName.h:35:11 (exported to Smp-C/InvalidObjectName.h) : Reference type is not supported: InvalidObjectName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
