/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidParameterValue.h"
#include <Smp/InvalidParameterValue.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidParameterValue ### */
#define CW_SPACE CW_root_Smp_InvalidParameterValue

void
CW(_InvalidParameterValue)
(
    CW() * self
) {
    static_cast<Smp::InvalidParameterValue *>(self)->~InvalidParameterValue(
    );
}

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidParameterValue *>(self)->GetOperationName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetParameterName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidParameterValue *>(self)->GetParameterName(
    ));
}

/* Error while processing function "InvalidParameterValue" at Smp/InvalidParameterValue.h:31:11 (exported to Smp-C/InvalidParameterValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParameterValue.h:31:11 (exported to Smp-C/InvalidParameterValue.h) : Reference type is not supported: InvalidParameterValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
