/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/InvalidParameterDirection.h"
#include <Smp/Publication/InvalidParameterDirection.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::InvalidParameterDirection ### */
#define CW_SPACE CW_root_Smp_Publication_InvalidParameterDirection

void
CW(_InvalidParameterDirection)
(
    CW() * self
) {
    static_cast<Smp::Publication::InvalidParameterDirection *>(self)->~InvalidParameterDirection(
    );
}

CW(CW_root_Smp, String8)
CW(GetParameterName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Publication::InvalidParameterDirection *>(self)->GetParameterName(
    ));
}

/* Error while processing function "InvalidParameterDirection" at Smp/Publication/InvalidParameterDirection.h:32:15 (exported to Smp-C/Publication/InvalidParameterDirection.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/InvalidParameterDirection.h:32:15 (exported to Smp-C/Publication/InvalidParameterDirection.h) : Reference type is not supported: InvalidParameterDirection & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
