/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/InvalidPrimitiveType.h"
#include <Smp/Publication/InvalidPrimitiveType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::InvalidPrimitiveType ### */
#define CW_SPACE CW_root_Smp_Publication_InvalidPrimitiveType

void
CW(_InvalidPrimitiveType)
(
    CW() * self
) {
    static_cast<Smp::Publication::InvalidPrimitiveType *>(self)->~InvalidPrimitiveType(
    );
}

CW(CW_root_Smp, String8)
CW(GetTypeName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Publication::InvalidPrimitiveType *>(self)->GetTypeName(
    ));
}

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetType)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, PrimitiveTypeKind)>(
    static_cast<Smp::Publication::InvalidPrimitiveType *>(self)->GetType(
    ));
}

/* Error while processing function "InvalidPrimitiveType" at Smp/Publication/InvalidPrimitiveType.h:32:15 (exported to Smp-C/Publication/InvalidPrimitiveType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/InvalidPrimitiveType.h:32:15 (exported to Smp-C/Publication/InvalidPrimitiveType.h) : Reference type is not supported: InvalidPrimitiveType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
