/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidArraySize.h"
#include <Smp/InvalidArraySize.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidArraySize ### */
#define CW_SPACE CW_root_Smp_InvalidArraySize

void
CW(_InvalidArraySize)
(
    CW() * self
) {
    static_cast<Smp::InvalidArraySize *>(self)->~InvalidArraySize(
    );
}

CW(CW_root_Smp, Int64)
CW(GetArraySize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::InvalidArraySize *>(self)->GetArraySize(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetInvalidSize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::InvalidArraySize *>(self)->GetInvalidSize(
    ));
}

/* Error while processing function "InvalidArraySize" at Smp/InvalidArraySize.h:28:11 (exported to Smp-C/InvalidArraySize.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidArraySize.h:28:11 (exported to Smp-C/InvalidArraySize.h) : Reference type is not supported: InvalidArraySize & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
