/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidAnyType.h"
#include <Smp/InvalidAnyType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidAnyType ### */
#define CW_SPACE CW_root_Smp_InvalidAnyType

void
CW(_InvalidAnyType)
(
    CW() * self
) {
    static_cast<Smp::InvalidAnyType *>(self)->~InvalidAnyType(
    );
}

/* Error while processing function "GetInvalidValue" at Smp/InvalidAnyType.h:41:32 (exported to Smp-C/InvalidAnyType.h) : Skipping function that returns a class/struct */

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetExpectedType)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, PrimitiveTypeKind)>(
    static_cast<Smp::InvalidAnyType *>(self)->GetExpectedType(
    ));
}

/* Error while processing function "InvalidAnyType" at Smp/InvalidAnyType.h:32:11 (exported to Smp-C/InvalidAnyType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidAnyType.h:32:11 (exported to Smp-C/InvalidAnyType.h) : Reference type is not supported: InvalidAnyType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
