/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidObjectType.h"
#include <Smp/InvalidObjectType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidObjectType ### */
#define CW_SPACE CW_root_Smp_InvalidObjectType

void
CW(_InvalidObjectType)
(
    CW() * self
) {
    static_cast<Smp::InvalidObjectType *>(self)->~InvalidObjectType(
    );
}

const CW(CW_root_Smp, IObject) *
CW(GetInvalidObject)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::InvalidObjectType *>(self)->GetInvalidObject(
    ));
}

/* Error while processing function "InvalidObjectType" at Smp/InvalidObjectType.h:39:11 (exported to Smp-C/InvalidObjectType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidObjectType.h:39:11 (exported to Smp-C/InvalidObjectType.h) : Reference type is not supported: InvalidObjectType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
