/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidParameterIndex.h"
#include <Smp/InvalidParameterIndex.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidParameterIndex ### */
#define CW_SPACE CW_root_Smp_InvalidParameterIndex

void
CW(_InvalidParameterIndex)
(
    CW() * self
) {
    static_cast<Smp::InvalidParameterIndex *>(self)->~InvalidParameterIndex(
    );
}

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidParameterIndex *>(self)->GetOperationName(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetParameterIndex)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::InvalidParameterIndex *>(self)->GetParameterIndex(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetParameterCount)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::InvalidParameterIndex *>(self)->GetParameterCount(
    ));
}

/* Error while processing function "InvalidParameterIndex" at Smp/InvalidParameterIndex.h:30:11 (exported to Smp-C/InvalidParameterIndex.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParameterIndex.h:30:11 (exported to Smp-C/InvalidParameterIndex.h) : Reference type is not supported: InvalidParameterIndex & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
