/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidType.h"
#include <Smp/InvalidType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidType ### */
#define CW_SPACE CW_root_Smp_InvalidType

void
CW(_InvalidType)
(
    CW() * self
) {
    static_cast<Smp::InvalidType *>(self)->~InvalidType(
    );
}

/* Error while processing function "InvalidType" at Smp/InvalidType.h:34:11 (exported to Smp-C/InvalidType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidType.h:34:11 (exported to Smp-C/InvalidType.h) : Reference type is not supported: InvalidType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
