/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidArrayValue.h"
#include <Smp/InvalidArrayValue.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidArrayValue ### */
#define CW_SPACE CW_root_Smp_InvalidArrayValue

void
CW(_InvalidArrayValue)
(
    CW() * self
) {
    static_cast<Smp::InvalidArrayValue *>(self)->~InvalidArrayValue(
    );
}

CW(CW_root_Smp, Int64)
CW(GetInvalidValueIndex)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::InvalidArrayValue *>(self)->GetInvalidValueIndex(
    ));
}

/* Error while processing function "InvalidArrayValue" at Smp/InvalidArrayValue.h:29:11 (exported to Smp-C/InvalidArrayValue.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidArrayValue.h:29:11 (exported to Smp-C/InvalidArrayValue.h) : Reference type is not supported: InvalidArrayValue & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
