/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/InvalidEventName.h"
#include <Smp/Services/InvalidEventName.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::InvalidEventName ### */
#define CW_SPACE CW_root_Smp_Services_InvalidEventName

void
CW(_InvalidEventName)
(
    CW() * self
) {
    static_cast<Smp::Services::InvalidEventName *>(self)->~InvalidEventName(
    );
}

/* Error while processing function "InvalidEventName" at Smp/Services/InvalidEventName.h:31:15 (exported to Smp-C/Services/InvalidEventName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidEventName.h:31:15 (exported to Smp-C/Services/InvalidEventName.h) : Reference type is not supported: InvalidEventName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
