/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidParent.h"
#include <Smp/InvalidParent.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidParent ### */
#define CW_SPACE CW_root_Smp_InvalidParent

void
CW(_InvalidParent)
(
    CW() * self
) {
    static_cast<Smp::InvalidParent *>(self)->~InvalidParent(
    );
}

const CW(CW_root_Smp, IObject) *
CW(GetParentFound)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::InvalidParent *>(self)->GetParentFound(
    ));
}

const CW(CW_root_Smp, IObject) *
CW(GetParentExpected)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::InvalidParent *>(self)->GetParentExpected(
    ));
}

/* Error while processing function "InvalidParent" at Smp/InvalidParent.h:38:11 (exported to Smp-C/InvalidParent.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidParent.h:38:11 (exported to Smp-C/InvalidParent.h) : Reference type is not supported: InvalidParent & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
