/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidOperationName.h"
#include <Smp/InvalidOperationName.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidOperationName ### */
#define CW_SPACE CW_root_Smp_InvalidOperationName

void
CW(_InvalidOperationName)
(
    CW() * self
) {
    static_cast<Smp::InvalidOperationName *>(self)->~InvalidOperationName(
    );
}

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::InvalidOperationName *>(self)->GetOperationName(
    ));
}

/* Error while processing function "InvalidOperationName" at Smp/InvalidOperationName.h:29:11 (exported to Smp-C/InvalidOperationName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidOperationName.h:29:11 (exported to Smp-C/InvalidOperationName.h) : Reference type is not supported: InvalidOperationName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
