/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/InvalidTarget.h"
#include <Smp/InvalidTarget.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::InvalidTarget ### */
#define CW_SPACE CW_root_Smp_InvalidTarget

void
CW(_InvalidTarget)
(
    CW() * self
) {
    static_cast<Smp::InvalidTarget *>(self)->~InvalidTarget(
    );
}

const CW(CW_root_Smp, IOutputField) *
CW(GetSource)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IOutputField) *>(
    static_cast<Smp::InvalidTarget *>(self)->GetSource(
    ));
}

const CW(CW_root_Smp, IField) *
CW(GetTarget)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IField) *>(
    static_cast<Smp::InvalidTarget *>(self)->GetTarget(
    ));
}

/* Error while processing function "InvalidTarget" at Smp/InvalidTarget.h:38:11 (exported to Smp-C/InvalidTarget.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/InvalidTarget.h:38:11 (exported to Smp-C/InvalidTarget.h) : Reference type is not supported: InvalidTarget & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
