/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IObject.h"
#include <Smp/IObject.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IObject ### */
#define CW_SPACE CW_root_Smp_IObject

void
CW(_IObject)
(
    CW() * self
) {
    static_cast<Smp::IObject *>(self)->~IObject(
    );
}

CW(CW_root_Smp, String8)
CW(GetName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IObject *>(self)->GetName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetDescription)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IObject *>(self)->GetDescription(
    ));
}

CW(CW_root_Smp, IObject) *
CW(GetParent)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::IObject *>(self)->GetParent(
    ));
}

CW(CW_root_Smp, IObject) *
CW(GetChild)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::IObject *>(self)->GetChild(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "operator=" at Smp/IObject.h:44:11 (exported to Smp-C/IObject.h) : Reference type is not supported: IObject & */

/* Error while processing function "IObject" at Smp/IObject.h:44:11 (exported to Smp-C/IObject.h) : Skipping constructor */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
