/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IOperation.h"
#include <Smp/IOperation.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IOperation ### */
#define CW_SPACE CW_root_Smp_IOperation

void
CW(_IOperation)
(
    CW() * self
) {
    static_cast<Smp::IOperation *>(self)->~IOperation(
    );
}

const CW(CW_root_Smp, ParameterCollection) *
CW(GetParameters)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, ParameterCollection) *>(
    static_cast<Smp::IOperation *>(self)->GetParameters(
    ));
}

CW(CW_root_Smp, IParameter) *
CW(GetParameter)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IParameter) *>(
    static_cast<Smp::IOperation *>(self)->GetParameter(
        static_cast<Smp::String8>(name)
    ));
}

CW(CW_root_Smp, IParameter) *
CW(GetReturnParameter)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, IParameter) *>(
    static_cast<Smp::IOperation *>(self)->GetReturnParameter(
    ));
}

CW(CW_root_Smp, ViewKind)
CW(GetView)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, ViewKind)>(
    static_cast<Smp::IOperation *>(self)->GetView(
    ));
}

CW(CW_root_Smp, IRequest) *
CW(CreateRequest)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, IRequest) *>(
    static_cast<Smp::IOperation *>(self)->CreateRequest(
    ));
}

void
CW(Invoke)
(
    CW() * self,
    CW(CW_root_Smp, IRequest) * request
) {
    static_cast<Smp::IOperation *>(self)->Invoke(
        static_cast<Smp::IRequest *>(request)
    );
}

void
CW(DeleteRequest)
(
    CW() * self,
    CW(CW_root_Smp, IRequest) * request
) {
    static_cast<Smp::IOperation *>(self)->DeleteRequest(
        static_cast<Smp::IRequest *>(request)
    );
}

/* Error while processing function "IOperation" at Smp/IOperation.h:43:11 (exported to Smp-C/IOperation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IOperation.h:43:11 (exported to Smp-C/IOperation.h) : Reference type is not supported: IOperation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
