/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IOutputField.h"
#include <Smp/IOutputField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IOutputField ### */
#define CW_SPACE CW_root_Smp_IOutputField

void
CW(_IOutputField)
(
    CW() * self
) {
    static_cast<Smp::IOutputField *>(self)->~IOutputField(
    );
}

void
CW(Connect)
(
    CW() * self,
    CW(CW_root_Smp, IField) * target
) {
    static_cast<Smp::IOutputField *>(self)->Connect(
        static_cast<Smp::IField *>(target)
    );
}

void
CW(Disconnect)
(
    CW() * self,
    CW(CW_root_Smp, IField) * target
) {
    static_cast<Smp::IOutputField *>(self)->Disconnect(
        static_cast<Smp::IField *>(target)
    );
}

void
CW(Push)
(
    CW() * self
) {
    static_cast<Smp::IOutputField *>(self)->Push(
    );
}

const CW(CW_root_Smp, FieldCollection) *
CW(GetInputFields)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, FieldCollection) *>(
    static_cast<Smp::IOutputField *>(self)->GetInputFields(
    ));
}

CW(CW_root_Smp, Bool)
CW(IsAutomatic)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Bool)>(
    static_cast<Smp::IOutputField *>(self)->IsAutomatic(
    ));
}

/* Error while processing function "IOutputField" at Smp/./IOutputField.h:33:11 (exported to Smp-C/IOutputField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IOutputField.h:33:11 (exported to Smp-C/IOutputField.h) : Reference type is not supported: IOutputField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
