/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IParameter.h"
#include <Smp/IParameter.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IParameter ### */
#define CW_SPACE CW_root_Smp_IParameter

void
CW(_IParameter)
(
    CW() * self
) {
    static_cast<Smp::IParameter *>(self)->~IParameter(
    );
}

const CW(CW_root_Smp_Publication, IType) *
CW(GetType)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp_Publication, IType) *>(
    static_cast<Smp::IParameter *>(self)->GetType(
    ));
}

CW(CW_root_Smp_Publication, ParameterDirectionKind)
CW(GetDirection)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp_Publication, ParameterDirectionKind)>(
    static_cast<Smp::IParameter *>(self)->GetDirection(
    ));
}

/* Error while processing function "IParameter" at Smp/IParameter.h:41:11 (exported to Smp-C/IParameter.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IParameter.h:41:11 (exported to Smp-C/IParameter.h) : Reference type is not supported: IParameter & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
