/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IPersist.h"
#include <Smp/IPersist.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IPersist ### */
#define CW_SPACE CW_root_Smp_IPersist

void
CW(_IPersist)
(
    CW() * self
) {
    static_cast<Smp::IPersist *>(self)->~IPersist(
    );
}

void
CW(Restore)
(
    CW() * self,
    CW(CW_root_Smp, IStorageReader) * reader
) {
    static_cast<Smp::IPersist *>(self)->Restore(
        static_cast<Smp::IStorageReader *>(reader)
    );
}

void
CW(Store)
(
    CW() * self,
    CW(CW_root_Smp, IStorageWriter) * writer
) {
    static_cast<Smp::IPersist *>(self)->Store(
        static_cast<Smp::IStorageWriter *>(writer)
    );
}

/* Error while processing function "IPersist" at Smp/IPersist.h:43:11 (exported to Smp-C/IPersist.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IPersist.h:43:11 (exported to Smp-C/IPersist.h) : Reference type is not supported: IPersist & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
