/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IPublishOperation.h"
#include <Smp/Publication/IPublishOperation.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IPublishOperation ### */
#define CW_SPACE CW_root_Smp_Publication_IPublishOperation

void
CW(_IPublishOperation)
(
    CW() * self
) {
    static_cast<Smp::Publication::IPublishOperation *>(self)->~IPublishOperation(
    );
}

void
CW(PublishParameter)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Uuid) * typeUuid,
    CW(CW_root_Smp_Publication, ParameterDirectionKind) direction
) {
    static_cast<Smp::Publication::IPublishOperation *>(self)->PublishParameter(
        static_cast<Smp::String8>(name),
        static_cast<Smp::String8>(description),
        *static_cast<Smp::Uuid*>(typeUuid),
        static_cast<Smp::Publication::ParameterDirectionKind>(direction)
    );
}

/* Error while processing function "operator=" at Smp/./Publication/IPublishOperation.h:38:15 (exported to Smp-C/Publication/IPublishOperation.h) : Reference type is not supported: IPublishOperation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
