/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IReference.h"
#include <Smp/IReference.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IReference ### */
#define CW_SPACE CW_root_Smp_IReference

void
CW(_IReference)
(
    CW() * self
) {
    static_cast<Smp::IReference *>(self)->~IReference(
    );
}

const CW(CW_root_Smp, ComponentCollection) *
CW(GetComponents)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, ComponentCollection) *>(
    static_cast<Smp::IReference *>(self)->GetComponents(
    ));
}

CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::IReference *>(self)->GetComponent(
        static_cast<Smp::String8>(name)
    ));
}

void
CW(AddComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
) {
    static_cast<Smp::IReference *>(self)->AddComponent(
        static_cast<Smp::IComponent *>(component)
    );
}

void
CW(RemoveComponent)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * component
) {
    static_cast<Smp::IReference *>(self)->RemoveComponent(
        static_cast<Smp::IComponent *>(component)
    );
}

CW(CW_root_Smp, Int64)
CW(GetCount)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::IReference *>(self)->GetCount(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetUpper)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::IReference *>(self)->GetUpper(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetLower)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::IReference *>(self)->GetLower(
    ));
}

/* Error while processing function "IReference" at Smp/IReference.h:45:11 (exported to Smp-C/IReference.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/IReference.h:45:11 (exported to Smp-C/IReference.h) : Reference type is not supported: IReference & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
