/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IRequest.h"
#include <Smp/IRequest.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IRequest ### */
#define CW_SPACE CW_root_Smp_IRequest

void
CW(_IRequest)
(
    CW() * self
) {
    static_cast<Smp::IRequest *>(self)->~IRequest(
    );
}

CW(CW_root_Smp, String8)
CW(GetName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IRequest *>(self)->GetName(
    ));
}

CW(CW_root_Smp, RequestType)
CW(GetType)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, RequestType)>(
    static_cast<Smp::IRequest *>(self)->GetType(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetParameterCount)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::IRequest *>(self)->GetParameterCount(
    ));
}

CW(CW_root_Smp, Int32)
CW(GetParameterIndex)
(
    CW() * self,
    CW(CW_root_Smp, String8) parameterName
) {
    return static_cast<CW(CW_root_Smp, Int32)>(
    static_cast<Smp::IRequest *>(self)->GetParameterIndex(
        static_cast<Smp::String8>(parameterName)
    ));
}

void
CW(SetParameterValue)
(
    CW() * self,
    CW(CW_root_Smp, Int32) index,
    CW(CW_root_Smp, AnySimple) * value
) {
    static_cast<Smp::IRequest *>(self)->SetParameterValue(
        static_cast<Smp::Int32>(index),
        *static_cast<Smp::AnySimple*>(value)
    );
}

/* Error while processing function "GetParameterValue" at Smp/./IRequest.h:102:32 (exported to Smp-C/IRequest.h) : Skipping function that returns a class/struct */

void
CW(SetReturnValue)
(
    CW() * self,
    CW(CW_root_Smp, AnySimple) * value
) {
    static_cast<Smp::IRequest *>(self)->SetReturnValue(
        *static_cast<Smp::AnySimple*>(value)
    );
}

/* Error while processing function "GetReturnValue" at Smp/./IRequest.h:120:32 (exported to Smp-C/IRequest.h) : Skipping function that returns a class/struct */

/* Error while processing function "operator=" at Smp/./IRequest.h:34:11 (exported to Smp-C/IRequest.h) : Reference type is not supported: IRequest & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
