/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Services/IResolver.h"
#include <Smp/Services/IResolver.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#define CW_SPACE CW_root_Smp_Services

#undef CW_SPACE


/* ### Smp::Services::IResolver ### */
#define CW_SPACE CW_root_Smp_Services_IResolver

void
CW(_IResolver)
(
    CW() * self
) {
    static_cast<Smp::Services::IResolver *>(self)->~IResolver(
    );
}

CW(CW_root_Smp, IObject) *
CW(ResolveAbsolute)
(
    CW() * self,
    CW(CW_root_Smp, String8) absolutePath
) {
    return static_cast<CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::Services::IResolver *>(self)->ResolveAbsolute(
        static_cast<Smp::String8>(absolutePath)
    ));
}

CW(CW_root_Smp, IObject) *
CW(ResolveRelative)
(
    CW() * self,
    CW(CW_root_Smp, String8) relativePath,
    CW(CW_root_Smp, IObject) * relativeRoot
) {
    return static_cast<CW(CW_root_Smp, IObject) *>(
    static_cast<Smp::Services::IResolver *>(self)->ResolveRelative(
        static_cast<Smp::String8>(relativePath),
        static_cast<Smp::IObject *>(relativeRoot)
    ));
}

/* Error while processing function "IResolver" at Smp/./Services/IResolver.h:40:15 (exported to Smp-C/Services/IResolver.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/IResolver.h:40:15 (exported to Smp-C/Services/IResolver.h) : Reference type is not supported: IResolver & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
