/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IService.h"
#include <Smp/IService.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IService ### */
#define CW_SPACE CW_root_Smp_IService

void
CW(_IService)
(
    CW() * self
) {
    static_cast<Smp::IService *>(self)->~IService(
    );
}

/* Error while processing function "IService" at Smp/./IService.h:28:11 (exported to Smp-C/IService.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IService.h:28:11 (exported to Smp-C/IService.h) : Reference type is not supported: IService & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
