/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ISimpleArrayField.h"
#include <Smp/ISimpleArrayField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ISimpleArrayField ### */
#define CW_SPACE CW_root_Smp_ISimpleArrayField

void
CW(_ISimpleArrayField)
(
    CW() * self
) {
    static_cast<Smp::ISimpleArrayField *>(self)->~ISimpleArrayField(
    );
}

CW(CW_root_Smp, UInt64)
CW(GetSize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, UInt64)>(
    static_cast<Smp::ISimpleArrayField *>(self)->GetSize(
    ));
}

/* Error while processing function "GetValue" at Smp/./ISimpleArrayField.h:50:32 (exported to Smp-C/ISimpleArrayField.h) : Skipping function that returns a class/struct */

void
CW(SetValue)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) index,
    CW(CW_root_Smp, AnySimple) * value
) {
    static_cast<Smp::ISimpleArrayField *>(self)->SetValue(
        static_cast<Smp::UInt64>(index),
        *static_cast<Smp::AnySimple*>(value)
    );
}

void
CW(GetValues)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) length,
    CW(CW_root_Smp, AnySimple) * values,
    CW(CW_root_Smp, UInt64) startIndex
) {
    static_cast<Smp::ISimpleArrayField *>(self)->GetValues(
        static_cast<Smp::UInt64>(length),
        static_cast<Smp::AnySimple *>(values),
        static_cast<Smp::UInt64>(startIndex)
    );
}

void
CW(SetValues)
(
    CW() * self,
    CW(CW_root_Smp, UInt64) length,
    CW(CW_root_Smp, AnySimpleArray) values,
    CW(CW_root_Smp, UInt64) startIndex
) {
    static_cast<Smp::ISimpleArrayField *>(self)->SetValues(
        static_cast<Smp::UInt64>(length),
        static_cast<Smp::AnySimpleArray>(values),
        static_cast<Smp::UInt64>(startIndex)
    );
}

/* Error while processing function "ISimpleArrayField" at Smp/./ISimpleArrayField.h:33:11 (exported to Smp-C/ISimpleArrayField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./ISimpleArrayField.h:33:11 (exported to Smp-C/ISimpleArrayField.h) : Reference type is not supported: ISimpleArrayField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
