/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ISimpleField.h"
#include <Smp/ISimpleField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ISimpleField ### */
#define CW_SPACE CW_root_Smp_ISimpleField

void
CW(_ISimpleField)
(
    CW() * self
) {
    static_cast<Smp::ISimpleField *>(self)->~ISimpleField(
    );
}

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetPrimitiveTypeKind)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, PrimitiveTypeKind)>(
    static_cast<Smp::ISimpleField *>(self)->GetPrimitiveTypeKind(
    ));
}

/* Error while processing function "GetValue" at Smp/ISimpleField.h:43:32 (exported to Smp-C/ISimpleField.h) : Skipping function that returns a class/struct */

void
CW(SetValue)
(
    CW() * self,
    CW(CW_root_Smp, AnySimple) * value
) {
    static_cast<Smp::ISimpleField *>(self)->SetValue(
        *static_cast<Smp::AnySimple*>(value)
    );
}

/* Error while processing function "ISimpleField" at Smp/ISimpleField.h:30:11 (exported to Smp-C/ISimpleField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/ISimpleField.h:30:11 (exported to Smp-C/ISimpleField.h) : Reference type is not supported: ISimpleField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
