/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IStorageReader.h"
#include <Smp/IStorageReader.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IStorageReader ### */
#define CW_SPACE CW_root_Smp_IStorageReader

void
CW(_IStorageReader)
(
    CW() * self
) {
    static_cast<Smp::IStorageReader *>(self)->~IStorageReader(
    );
}

void
CW(Restore)
(
    CW() * self,
    CW(CW_root_Smp, Void) * address,
    CW(CW_root_Smp, UInt64) size
) {
    static_cast<Smp::IStorageReader *>(self)->Restore(
        static_cast<Smp::Void *>(address),
        static_cast<Smp::UInt64>(size)
    );
}

CW(CW_root_Smp, String8)
CW(GetStateVectorFileName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IStorageReader *>(self)->GetStateVectorFileName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetStateVectorFilePath)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IStorageReader *>(self)->GetStateVectorFilePath(
    ));
}

/* Error while processing function "operator=" at Smp/./IStorageReader.h:32:11 (exported to Smp-C/IStorageReader.h) : Reference type is not supported: IStorageReader & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
