/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IStorageWriter.h"
#include <Smp/IStorageWriter.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IStorageWriter ### */
#define CW_SPACE CW_root_Smp_IStorageWriter

void
CW(_IStorageWriter)
(
    CW() * self
) {
    static_cast<Smp::IStorageWriter *>(self)->~IStorageWriter(
    );
}

void
CW(Store)
(
    CW() * self,
    const CW(CW_root_Smp, Void) * address,
    CW(CW_root_Smp, UInt64) size
) {
    static_cast<Smp::IStorageWriter *>(self)->Store(
        static_cast<const Smp::Void *>(address),
        static_cast<Smp::UInt64>(size)
    );
}

CW(CW_root_Smp, String8)
CW(GetStateVectorFileName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IStorageWriter *>(self)->GetStateVectorFileName(
    ));
}

CW(CW_root_Smp, String8)
CW(GetStateVectorFilePath)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::IStorageWriter *>(self)->GetStateVectorFilePath(
    ));
}

/* Error while processing function "operator=" at Smp/./IStorageWriter.h:32:11 (exported to Smp-C/IStorageWriter.h) : Reference type is not supported: IStorageWriter & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
