/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/IStructureField.h"
#include <Smp/IStructureField.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::IStructureField ### */
#define CW_SPACE CW_root_Smp_IStructureField

void
CW(_IStructureField)
(
    CW() * self
) {
    static_cast<Smp::IStructureField *>(self)->~IStructureField(
    );
}

const CW(CW_root_Smp, FieldCollection) *
CW(GetFields)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, FieldCollection) *>(
    static_cast<Smp::IStructureField *>(self)->GetFields(
    ));
}

CW(CW_root_Smp, IField) *
CW(GetField)
(
    CW() * self,
    CW(CW_root_Smp, String8) name
) {
    return static_cast<CW(CW_root_Smp, IField) *>(
    static_cast<Smp::IStructureField *>(self)->GetField(
        static_cast<Smp::String8>(name)
    ));
}

/* Error while processing function "IStructureField" at Smp/./IStructureField.h:29:11 (exported to Smp-C/IStructureField.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./IStructureField.h:29:11 (exported to Smp-C/IStructureField.h) : Reference type is not supported: IStructureField & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
