/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IStructureType.h"
#include <Smp/Publication/IStructureType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IStructureType ### */
#define CW_SPACE CW_root_Smp_Publication_IStructureType

void
CW(_IStructureType)
(
    CW() * self
) {
    static_cast<Smp::Publication::IStructureType *>(self)->~IStructureType(
    );
}

void
CW(AddField)
(
    CW() * self,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Uuid) * uuid,
    CW(CW_root_Smp, UInt64) offset,
    CW(CW_root_Smp, ViewKind) view,
    CW(CW_root_Smp, Bool) state,
    CW(CW_root_Smp, Bool) input,
    CW(CW_root_Smp, Bool) output
) {
    static_cast<Smp::Publication::IStructureType *>(self)->AddField(
        static_cast<Smp::String8>(name),
        static_cast<Smp::String8>(description),
        *static_cast<Smp::Uuid*>(uuid),
        static_cast<Smp::UInt64>(offset),
        static_cast<Smp::ViewKind>(view),
        static_cast<Smp::Bool>(state),
        static_cast<Smp::Bool>(input),
        static_cast<Smp::Bool>(output)
    );
}

/* Error while processing function "IStructureType" at Smp/Publication/IStructureType.h:37:15 (exported to Smp-C/Publication/IStructureType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/IStructureType.h:37:15 (exported to Smp-C/Publication/IStructureType.h) : Reference type is not supported: IStructureType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
