/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IStringType.h"
#include <Smp/Publication/IStringType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IStringType ### */
#define CW_SPACE CW_root_Smp_Publication_IStringType

void
CW(_IStringType)
(
    CW() * self
) {
    static_cast<Smp::Publication::IStringType *>(self)->~IStringType(
    );
}

CW(CW_root_Smp, UInt64)
CW(GetMaxLength)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, UInt64)>(
    static_cast<Smp::Publication::IStringType *>(self)->GetMaxLength(
    ));
}

/* Error while processing function "IStringType" at Smp/./Publication/IStringType.h:31:15 (exported to Smp-C/Publication/IStringType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Publication/IStringType.h:31:15 (exported to Smp-C/Publication/IStringType.h) : Reference type is not supported: IStringType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
