/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/IType.h"
#include <Smp/Publication/IType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::IType ### */
#define CW_SPACE CW_root_Smp_Publication_IType

void
CW(_IType)
(
    CW() * self
) {
    static_cast<Smp::Publication::IType *>(self)->~IType(
    );
}

CW(CW_root_Smp, PrimitiveTypeKind)
CW(GetPrimitiveTypeKind)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, PrimitiveTypeKind)>(
    static_cast<Smp::Publication::IType *>(self)->GetPrimitiveTypeKind(
    ));
}

/* Error while processing function "GetUuid" at Smp/Publication/IType.h:67:31 (exported to Smp-C/Publication/IType.h) : Skipping function that returns a class/struct */

CW(CW_root_Smp, IField) *
CW(Publish)
(
    CW() * self,
    CW(CW_root_Smp_Publication, IPublishField) * receiver,
    CW(CW_root_Smp, String8) name,
    CW(CW_root_Smp, String8) description,
    CW(CW_root_Smp, Void) * address,
    CW(CW_root_Smp, ViewKind) view,
    CW(CW_root_Smp, Bool) state,
    CW(CW_root_Smp, Bool) input,
    CW(CW_root_Smp, Bool) output
) {
    return static_cast<CW(CW_root_Smp, IField) *>(
    static_cast<Smp::Publication::IType *>(self)->Publish(
        static_cast<Smp::Publication::IPublishField *>(receiver),
        static_cast<Smp::String8>(name),
        static_cast<Smp::String8>(description),
        static_cast<Smp::Void *>(address),
        static_cast<Smp::ViewKind>(view),
        static_cast<Smp::Bool>(state),
        static_cast<Smp::Bool>(input),
        static_cast<Smp::Bool>(output)
    ));
}

/* Error while processing function "IType" at Smp/Publication/IType.h:52:15 (exported to Smp-C/Publication/IType.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/IType.h:52:15 (exported to Smp-C/Publication/IType.h) : Reference type is not supported: IType & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
