/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/NoDynamicInvocation.h"
#include <Smp/NoDynamicInvocation.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::NoDynamicInvocation ### */
#define CW_SPACE CW_root_Smp_NoDynamicInvocation

void
CW(_NoDynamicInvocation)
(
    CW() * self
) {
    static_cast<Smp::NoDynamicInvocation *>(self)->~NoDynamicInvocation(
    );
}

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::NoDynamicInvocation *>(self)->GetComponent(
    ));
}

/* Error while processing function "NoDynamicInvocation" at Smp/NoDynamicInvocation.h:37:11 (exported to Smp-C/NoDynamicInvocation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/NoDynamicInvocation.h:37:11 (exported to Smp-C/NoDynamicInvocation.h) : Reference type is not supported: NoDynamicInvocation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
