/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/NotContained.h"
#include <Smp/NotContained.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::NotContained ### */
#define CW_SPACE CW_root_Smp_NotContained

void
CW(_NotContained)
(
    CW() * self
) {
    static_cast<Smp::NotContained *>(self)->~NotContained(
    );
}

CW(CW_root_Smp, String8)
CW(GetContainerName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::NotContained *>(self)->GetContainerName(
    ));
}

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::NotContained *>(self)->GetComponent(
    ));
}

/* Error while processing function "NotContained" at Smp/NotContained.h:38:11 (exported to Smp-C/NotContained.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/NotContained.h:38:11 (exported to Smp-C/NotContained.h) : Reference type is not supported: NotContained & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
