/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/NotReferenced.h"
#include <Smp/NotReferenced.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::NotReferenced ### */
#define CW_SPACE CW_root_Smp_NotReferenced

void
CW(_NotReferenced)
(
    CW() * self
) {
    static_cast<Smp::NotReferenced *>(self)->~NotReferenced(
    );
}

CW(CW_root_Smp, String8)
CW(GetReferenceName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::NotReferenced *>(self)->GetReferenceName(
    ));
}

const CW(CW_root_Smp, IComponent) *
CW(GetComponent)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp, IComponent) *>(
    static_cast<Smp::NotReferenced *>(self)->GetComponent(
    ));
}

/* Error while processing function "NotReferenced" at Smp/NotReferenced.h:38:11 (exported to Smp-C/NotReferenced.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/NotReferenced.h:38:11 (exported to Smp-C/NotReferenced.h) : Reference type is not supported: NotReferenced & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
