/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/ReferenceFull.h"
#include <Smp/ReferenceFull.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::ReferenceFull ### */
#define CW_SPACE CW_root_Smp_ReferenceFull

void
CW(_ReferenceFull)
(
    CW() * self
) {
    static_cast<Smp::ReferenceFull *>(self)->~ReferenceFull(
    );
}

CW(CW_root_Smp, String8)
CW(GetReferenceName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::ReferenceFull *>(self)->GetReferenceName(
    ));
}

CW(CW_root_Smp, Int64)
CW(GetReferenceSize)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, Int64)>(
    static_cast<Smp::ReferenceFull *>(self)->GetReferenceSize(
    ));
}

/* Error while processing function "ReferenceFull" at Smp/ReferenceFull.h:29:11 (exported to Smp-C/ReferenceFull.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/ReferenceFull.h:29:11 (exported to Smp-C/ReferenceFull.h) : Reference type is not supported: ReferenceFull & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
