/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/RequestType.h"
#include <Smp/RequestType.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

/* Error while processing function "operator<<" at Smp/RequestType.h:44:19 (exported to Smp-C/RequestType.h) : Reference type is not supported: std::ostream & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
