/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/TypeNotRegistered.h"
#include <Smp/Publication/TypeNotRegistered.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::TypeNotRegistered ### */
#define CW_SPACE CW_root_Smp_Publication_TypeNotRegistered

void
CW(_TypeNotRegistered)
(
    CW() * self
) {
    static_cast<Smp::Publication::TypeNotRegistered *>(self)->~TypeNotRegistered(
    );
}

/* Error while processing function "GetUuid" at Smp/Publication/TypeNotRegistered.h:41:31 (exported to Smp-C/Publication/TypeNotRegistered.h) : Skipping function that returns a class/struct */

/* Error while processing function "TypeNotRegistered" at Smp/Publication/TypeNotRegistered.h:32:15 (exported to Smp-C/Publication/TypeNotRegistered.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/TypeNotRegistered.h:32:15 (exported to Smp-C/Publication/TypeNotRegistered.h) : Reference type is not supported: TypeNotRegistered & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
