/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Publication/TypeAlreadyRegistered.h"
#include <Smp/Publication/TypeAlreadyRegistered.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Publication ### */
#define CW_SPACE CW_root_Smp_Publication

#undef CW_SPACE


/* ### Smp::Publication::TypeAlreadyRegistered ### */
#define CW_SPACE CW_root_Smp_Publication_TypeAlreadyRegistered

void
CW(_TypeAlreadyRegistered)
(
    CW() * self
) {
    static_cast<Smp::Publication::TypeAlreadyRegistered *>(self)->~TypeAlreadyRegistered(
    );
}

CW(CW_root_Smp, String8)
CW(GetTypeName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::Publication::TypeAlreadyRegistered *>(self)->GetTypeName(
    ));
}

const CW(CW_root_Smp_Publication, IType) *
CW(GetType)
(
    CW() * self
) {
    return static_cast<const CW(CW_root_Smp_Publication, IType) *>(
    static_cast<Smp::Publication::TypeAlreadyRegistered *>(self)->GetType(
    ));
}

/* Error while processing function "TypeAlreadyRegistered" at Smp/Publication/TypeAlreadyRegistered.h:45:15 (exported to Smp-C/Publication/TypeAlreadyRegistered.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Publication/TypeAlreadyRegistered.h:45:15 (exported to Smp-C/Publication/TypeAlreadyRegistered.h) : Reference type is not supported: TypeAlreadyRegistered & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
