/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/Uuid.h"
#include <Smp/Uuid.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### std ### */
#define CW_SPACE CW_root_std

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Uuid ### */
#define CW_SPACE CW_root_Smp_Uuid

/* Error while processing function "Uuid" at Smp/Uuid.h:57:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:71:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:100:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:117:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:127:18 (exported to Smp-C/Uuid.h) : Skipping constructor */

void
CW(_Uuid)
(
    CW() * self
) {
    static_cast<Smp::Uuid *>(self)->~Uuid(
    );
}

/* Error while processing function "Uuid" at Smp/Uuid.h:134:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "Uuid" at Smp/Uuid.h:137:19 (exported to Smp-C/Uuid.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Uuid.h:140:15 (exported to Smp-C/Uuid.h) : Reference type is not supported: Uuid & */

/* Error while processing function "operator=" at Smp/Uuid.h:143:15 (exported to Smp-C/Uuid.h) : Reference type is not supported: Uuid & */

/* Error while processing function "operator==" at Smp/Uuid.h:148:14 (exported to Smp-C/Uuid.h) : Reference type is not supported: const Smp::Uuid & */

/* Error while processing function "operator!=" at Smp/Uuid.h:154:14 (exported to Smp-C/Uuid.h) : Reference type is not supported: const Smp::Uuid & */

/* Error while processing function "operator<" at Smp/Uuid.h:160:14 (exported to Smp-C/Uuid.h) : Reference type is not supported: const Uuid & */

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

/* Error while processing function "operator<<" at Smp/Uuid.h:165:19 (exported to Smp-C/Uuid.h) : Reference type is not supported: std::ostream & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
