/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#include "Smp-C/VoidOperation.h"
#include <Smp/VoidOperation.h>

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::VoidOperation ### */
#define CW_SPACE CW_root_Smp_VoidOperation

void
CW(_VoidOperation)
(
    CW() * self
) {
    static_cast<Smp::VoidOperation *>(self)->~VoidOperation(
    );
}

CW(CW_root_Smp, String8)
CW(GetOperationName)
(
    CW() * self
) {
    return static_cast<CW(CW_root_Smp, String8)>(
    static_cast<Smp::VoidOperation *>(self)->GetOperationName(
    ));
}

/* Error while processing function "VoidOperation" at Smp/VoidOperation.h:29:11 (exported to Smp-C/VoidOperation.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/VoidOperation.h:29:11 (exported to Smp-C/VoidOperation.h) : Reference type is not supported: VoidOperation & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */
