/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ENTRYPOINTNOTSUBSCRIBED_H
#define CWRAPPER_ENTRYPOINTNOTSUBSCRIBED_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEntryPoint);

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(EntryPointNotSubscribed);

#undef CW_SPACE


/* ### Smp::Services::EntryPointNotSubscribed ### */
#ifndef CW_root_Smp_Services_EntryPointNotSubscribed
#define CW_root_Smp_Services_EntryPointNotSubscribed CW_BUILD_SPACE(CW_root_Smp_Services, EntryPointNotSubscribed)
#endif /* CW_root_Smp_Services_EntryPointNotSubscribed */
#define CW_SPACE CW_root_Smp_Services_EntryPointNotSubscribed

void
CW(_EntryPointNotSubscribed)
(
    CW() * self
);

const CW(CW_root_Smp, IEntryPoint) *
CW(GetEntryPoint)
(
    CW() * self
);

CW(CW_root_Smp, String8)
CW(GetEventName)
(
    CW() * self
);

/* Error while processing function "EntryPointNotSubscribed" at Smp/./Services/EntryPointNotSubscribed.h:41:15 (exported to Smp-C/Services/EntryPointNotSubscribed.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/EntryPointNotSubscribed.h:41:15 (exported to Smp-C/Services/EntryPointNotSubscribed.h) : Reference type is not supported: EntryPointNotSubscribed & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ENTRYPOINTNOTSUBSCRIBED_H */
