/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IEVENTMANAGER_H
#define CWRAPPER_IEVENTMANAGER_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IService.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Services/EntryPointAlreadySubscribed.h"
#include "Smp-C/Services/EntryPointNotSubscribed.h"
#include "Smp-C/Services/EventId.h"
#include "Smp-C/Services/InvalidEventId.h"
#include "Smp-C/Services/InvalidEventName.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IEntryPoint);

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(IEventManager);

#undef CW_SPACE


/* ### Smp::Services::IEventManager ### */
#ifndef CW_root_Smp_Services_IEventManager
#define CW_root_Smp_Services_IEventManager CW_BUILD_SPACE(CW_root_Smp_Services, IEventManager)
#endif /* CW_root_Smp_Services_IEventManager */
#define CW_SPACE CW_root_Smp_Services_IEventManager

void
CW(_IEventManager)
(
    CW() * self
);

CW(CW_root_Smp_Services, EventId)
CW(QueryEventId)
(
    CW() * self,
    CW(CW_root_Smp, String8) eventName
);

void
CW(Subscribe)
(
    CW() * self,
    CW(CW_root_Smp_Services, EventId) event,
    const CW(CW_root_Smp, IEntryPoint) * entryPoint
);

void
CW(Unsubscribe)
(
    CW() * self,
    CW(CW_root_Smp_Services, EventId) event,
    const CW(CW_root_Smp, IEntryPoint) * entryPoint
);

void
CW(Emit)
(
    CW() * self,
    CW(CW_root_Smp_Services, EventId) event,
    CW(CW_root_Smp, Bool) synchronous
);

/* Error while processing function "IEventManager" at Smp/./Services/IEventManager.h:47:15 (exported to Smp-C/Services/IEventManager.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/IEventManager.h:47:15 (exported to Smp-C/Services/IEventManager.h) : Reference type is not supported: IEventManager & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IEVENTMANAGER_H */
