/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ILINKREGISTRY_H
#define CWRAPPER_ILINKREGISTRY_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/ComponentCollection.h"
#include "Smp-C/IService.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IComponent);

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(ILinkRegistry);

#undef CW_SPACE


/* ### Smp::Services::ILinkRegistry ### */
#ifndef CW_root_Smp_Services_ILinkRegistry
#define CW_root_Smp_Services_ILinkRegistry CW_BUILD_SPACE(CW_root_Smp_Services, ILinkRegistry)
#endif /* CW_root_Smp_Services_ILinkRegistry */
#define CW_SPACE CW_root_Smp_Services_ILinkRegistry

void
CW(_ILinkRegistry)
(
    CW() * self
);

void
CW(AddLink)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * source,
    const CW(CW_root_Smp, IComponent) * target
);

CW(CW_root_Smp, UInt32)
CW(GetLinkCount)
(
    CW() * self,
    const CW(CW_root_Smp, IComponent) * source,
    const CW(CW_root_Smp, IComponent) * target
);

CW(CW_root_Smp, Bool)
CW(RemoveLink)
(
    CW() * self,
    CW(CW_root_Smp, IComponent) * source,
    const CW(CW_root_Smp, IComponent) * target
);

const CW(CW_root_Smp, ComponentCollection) *
CW(GetLinkSources)
(
    CW() * self,
    const CW(CW_root_Smp, IComponent) * target
);

CW(CW_root_Smp, Bool)
CW(CanRemove)
(
    CW() * self,
    const CW(CW_root_Smp, IComponent) * target
);

void
CW(RemoveLinks)
(
    CW() * self,
    const CW(CW_root_Smp, IComponent) * target
);

/* Error while processing function "ILinkRegistry" at Smp/./Services/ILinkRegistry.h:45:15 (exported to Smp-C/Services/ILinkRegistry.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/ILinkRegistry.h:45:15 (exported to Smp-C/Services/ILinkRegistry.h) : Reference type is not supported: ILinkRegistry & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ILINKREGISTRY_H */
