/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ILOGGER_H
#define CWRAPPER_ILOGGER_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IService.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Services/LogMessageKind.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IObject);

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(ILogger);

#undef CW_SPACE


/* ### Smp::Services::ILogger ### */
#ifndef CW_root_Smp_Services_ILogger
#define CW_root_Smp_Services_ILogger CW_BUILD_SPACE(CW_root_Smp_Services, ILogger)
#endif /* CW_root_Smp_Services_ILogger */
#define CW_SPACE CW_root_Smp_Services_ILogger

void
CW(_ILogger)
(
    CW() * self
);

CW(CW_root_Smp_Services, LogMessageKind)
CW(QueryLogMessageKind)
(
    CW() * self,
    CW(CW_root_Smp, String8) messageKindName
);

void
CW(Log)
(
    CW() * self,
    const CW(CW_root_Smp, IObject) * sender,
    CW(CW_root_Smp, String8) message,
    CW(CW_root_Smp_Services, LogMessageKind) kind
);

/* Error while processing function "ILogger" at Smp/./Services/ILogger.h:44:15 (exported to Smp-C/Services/ILogger.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/ILogger.h:44:15 (exported to Smp-C/Services/ILogger.h) : Reference type is not supported: ILogger & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ILOGGER_H */
