/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDSIMULATIONTIME_H
#define CWRAPPER_INVALIDSIMULATIONTIME_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(InvalidSimulationTime);

#undef CW_SPACE


/* ### Smp::Services::InvalidSimulationTime ### */
#ifndef CW_root_Smp_Services_InvalidSimulationTime
#define CW_root_Smp_Services_InvalidSimulationTime CW_BUILD_SPACE(CW_root_Smp_Services, InvalidSimulationTime)
#endif /* CW_root_Smp_Services_InvalidSimulationTime */
#define CW_SPACE CW_root_Smp_Services_InvalidSimulationTime

void
CW(_InvalidSimulationTime)
(
    CW() * self
);

CW(CW_root_Smp, Duration)
CW(GetCurrentTime)
(
    CW() * self
);

CW(CW_root_Smp, Duration)
CW(GetProvidedTime)
(
    CW() * self
);

CW(CW_root_Smp, Duration)
CW(GetMaximumTime)
(
    CW() * self
);

/* Error while processing function "InvalidSimulationTime" at Smp/Services/InvalidSimulationTime.h:33:15 (exported to Smp-C/Services/InvalidSimulationTime.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidSimulationTime.h:33:15 (exported to Smp-C/Services/InvalidSimulationTime.h) : Reference type is not supported: InvalidSimulationTime & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDSIMULATIONTIME_H */
