/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDEVENTID_H
#define CWRAPPER_INVALIDEVENTID_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"
#include "Smp-C/Services/EventId.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(InvalidEventId);

#undef CW_SPACE


/* ### Smp::Services::InvalidEventId ### */
#ifndef CW_root_Smp_Services_InvalidEventId
#define CW_root_Smp_Services_InvalidEventId CW_BUILD_SPACE(CW_root_Smp_Services, InvalidEventId)
#endif /* CW_root_Smp_Services_InvalidEventId */
#define CW_SPACE CW_root_Smp_Services_InvalidEventId

void
CW(_InvalidEventId)
(
    CW() * self
);

CW(CW_root_Smp_Services, EventId)
CW(GetInvalidEventId)
(
    CW() * self
);

/* Error while processing function "InvalidEventId" at Smp/Services/InvalidEventId.h:37:15 (exported to Smp-C/Services/InvalidEventId.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidEventId.h:37:15 (exported to Smp-C/Services/InvalidEventId.h) : Reference type is not supported: InvalidEventId & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDEVENTID_H */
