/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDCYCLETIME_H
#define CWRAPPER_INVALIDCYCLETIME_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(InvalidCycleTime);

#undef CW_SPACE


/* ### Smp::Services::InvalidCycleTime ### */
#ifndef CW_root_Smp_Services_InvalidCycleTime
#define CW_root_Smp_Services_InvalidCycleTime CW_BUILD_SPACE(CW_root_Smp_Services, InvalidCycleTime)
#endif /* CW_root_Smp_Services_InvalidCycleTime */
#define CW_SPACE CW_root_Smp_Services_InvalidCycleTime

void
CW(_InvalidCycleTime)
(
    CW() * self
);

/* Error while processing function "InvalidCycleTime" at Smp/Services/InvalidCycleTime.h:32:15 (exported to Smp-C/Services/InvalidCycleTime.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidCycleTime.h:32:15 (exported to Smp-C/Services/InvalidCycleTime.h) : Reference type is not supported: InvalidCycleTime & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDCYCLETIME_H */
