/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDEVENTTIME_H
#define CWRAPPER_INVALIDEVENTTIME_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(InvalidEventTime);

#undef CW_SPACE


/* ### Smp::Services::InvalidEventTime ### */
#ifndef CW_root_Smp_Services_InvalidEventTime
#define CW_root_Smp_Services_InvalidEventTime CW_BUILD_SPACE(CW_root_Smp_Services, InvalidEventTime)
#endif /* CW_root_Smp_Services_InvalidEventTime */
#define CW_SPACE CW_root_Smp_Services_InvalidEventTime

void
CW(_InvalidEventTime)
(
    CW() * self
);

/* Error while processing function "InvalidEventTime" at Smp/Services/InvalidEventTime.h:32:15 (exported to Smp-C/Services/InvalidEventTime.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidEventTime.h:32:15 (exported to Smp-C/Services/InvalidEventTime.h) : Reference type is not supported: InvalidEventTime & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDEVENTTIME_H */
