/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_INVALIDEVENTNAME_H
#define CWRAPPER_INVALIDEVENTNAME_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/Exception.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(InvalidEventName);

#undef CW_SPACE


/* ### Smp::Services::InvalidEventName ### */
#ifndef CW_root_Smp_Services_InvalidEventName
#define CW_root_Smp_Services_InvalidEventName CW_BUILD_SPACE(CW_root_Smp_Services, InvalidEventName)
#endif /* CW_root_Smp_Services_InvalidEventName */
#define CW_SPACE CW_root_Smp_Services_InvalidEventName

void
CW(_InvalidEventName)
(
    CW() * self
);

/* Error while processing function "InvalidEventName" at Smp/Services/InvalidEventName.h:31:15 (exported to Smp-C/Services/InvalidEventName.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/Services/InvalidEventName.h:31:15 (exported to Smp-C/Services/InvalidEventName.h) : Reference type is not supported: InvalidEventName & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_INVALIDEVENTNAME_H */
