/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_IRESOLVER_H
#define CWRAPPER_IRESOLVER_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IService.h"
#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

typedef void CW(IObject);

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(IResolver);

#undef CW_SPACE


/* ### Smp::Services::IResolver ### */
#ifndef CW_root_Smp_Services_IResolver
#define CW_root_Smp_Services_IResolver CW_BUILD_SPACE(CW_root_Smp_Services, IResolver)
#endif /* CW_root_Smp_Services_IResolver */
#define CW_SPACE CW_root_Smp_Services_IResolver

void
CW(_IResolver)
(
    CW() * self
);

CW(CW_root_Smp, IObject) *
CW(ResolveAbsolute)
(
    CW() * self,
    CW(CW_root_Smp, String8) absolutePath
);

CW(CW_root_Smp, IObject) *
CW(ResolveRelative)
(
    CW() * self,
    CW(CW_root_Smp, String8) relativePath,
    CW(CW_root_Smp, IObject) * relativeRoot
);

/* Error while processing function "IResolver" at Smp/./Services/IResolver.h:40:15 (exported to Smp-C/Services/IResolver.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/IResolver.h:40:15 (exported to Smp-C/Services/IResolver.h) : Reference type is not supported: IResolver & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_IRESOLVER_H */
