/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_ITIMEKEEPER_H
#define CWRAPPER_ITIMEKEEPER_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/IService.h"
#include "Smp-C/PrimitiveTypes.h"
#include "Smp-C/Services/InvalidSimulationTime.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef void CW(ITimeKeeper);

#undef CW_SPACE


/* ### Smp::Services::ITimeKeeper ### */
#ifndef CW_root_Smp_Services_ITimeKeeper
#define CW_root_Smp_Services_ITimeKeeper CW_BUILD_SPACE(CW_root_Smp_Services, ITimeKeeper)
#endif /* CW_root_Smp_Services_ITimeKeeper */
#define CW_SPACE CW_root_Smp_Services_ITimeKeeper

void
CW(_ITimeKeeper)
(
    CW() * self
);

CW(CW_root_Smp, Duration)
CW(GetSimulationTime)
(
    CW() * self
);

CW(CW_root_Smp, DateTime)
CW(GetEpochTime)
(
    CW() * self
);

CW(CW_root_Smp, DateTime)
CW(GetMissionStartTime)
(
    CW() * self
);

CW(CW_root_Smp, Duration)
CW(GetMissionTime)
(
    CW() * self
);

CW(CW_root_Smp, DateTime)
CW(GetZuluTime)
(
    CW() * self
);

void
CW(SetSimulationTime)
(
    CW() * self,
    CW(CW_root_Smp, Duration) simulationTime
);

void
CW(SetEpochTime)
(
    CW() * self,
    CW(CW_root_Smp, DateTime) epochTime
);

void
CW(SetMissionStartTime)
(
    CW() * self,
    CW(CW_root_Smp, DateTime) missionStart
);

void
CW(SetMissionTime)
(
    CW() * self,
    CW(CW_root_Smp, Duration) missionTime
);

/* Error while processing function "ITimeKeeper" at Smp/./Services/ITimeKeeper.h:34:15 (exported to Smp-C/Services/ITimeKeeper.h) : Skipping constructor */

/* Error while processing function "operator=" at Smp/./Services/ITimeKeeper.h:34:15 (exported to Smp-C/Services/ITimeKeeper.h) : Reference type is not supported: ITimeKeeper & */

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_ITIMEKEEPER_H */
