/**
 * This file was auto-generated by https://github.com/abadiet/CWraPPer/
 */
#ifndef CWRAPPER_LOGMESSAGEKIND_H
#define CWRAPPER_LOGMESSAGEKIND_H

#include "../CWraPPer.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#include "Smp-C/PrimitiveTypes.h"


/* ### root ### */
#define CW_SPACE CW_root

#undef CW_SPACE


/* ### Smp ### */
#ifndef CW_root_Smp
#define CW_root_Smp CW_BUILD_SPACE(CW_root, Smp)
#endif /* CW_root_Smp */
#define CW_SPACE CW_root_Smp

#undef CW_SPACE


/* ### Smp::Services ### */
#ifndef CW_root_Smp_Services
#define CW_root_Smp_Services CW_BUILD_SPACE(CW_root_Smp, Services)
#endif /* CW_root_Smp_Services */
#define CW_SPACE CW_root_Smp_Services

typedef CW(CW_root_Smp, Int32) CW(LogMessageKind);

#undef CW_SPACE


#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif /* CWRAPPER_LOGMESSAGEKIND_H */
